### ISSUE TITLE
repo migration failing when attempting to update to ipfs v0.4.16-rc1

### ISSUE THREAD

**Issue by lanzafame** [ipfs/go-ipfs#5191] opened 2018-07-05 04:29 UTC
#### Version information:
Current:
go-ipfs version: 0.4.15-
Repo version: 6
System version: amd64/darwin
Golang version: go1.10.2

attempting to update to:
go-ipfs version: 0.4.16-rc1
Repo version: 7
System version: amd64/darwin
Golang version: go1.10.2

#### Type:
Bug

#### Description:
Attempting to install `go-ipfs` v0.4.16-rc1 via the latest version of `ipfs-update` v1.5.3 and I am getting the following error. The ipfs daemon was not running whilst I ran `ipfs update install v0.4.16-rc1`.

```
$ ipfs update install v0.4.16-rc1                                                                                                                                                       
fetching go-ipfs version v0.4.16-rc1
binary downloaded, verifying...
success! tests all passed.
stashing old binary
installing new binary to /usr/local/bin/ipfs
checking if repo migration is needed...
  check complete, migration required.
fetching fs-repo-migrations version v1.4.0
running migration: '/var/folders/kh/zhltnfr93bq3tl5n11vj3s680000gn/T/ipfs-update-migrate487519237/fs-repo-migrations -to 7 -y'
Found fs-repo version 6 at /Users/lanzafame/.ipfs
===> Running migration 6 to 7...
applying 6-to-7 repo migration
ipfs migration:  migration 6 to 7 failed: cannot acquire lock: Lock FcntlFlock of /Users/lanzafame/.ipfs/repo.lock failed: resource temporarily unavailable
ERROR: Migration Failed:  migration failed: exit status 1
install failed, reverting changes...
ERROR: migration failed: exit status 1
Error: exit status 1
```

Not sure if this is related to #5179 or fs-repo-migrations.

**Comment by Stebalien** [comment] 2018-07-05 19:36
I can confirm. Manually running ipfs-update works (what I've been doing) but the `ipfs update` command doesn't.

**Comment by Stebalien** [comment] 2018-07-05 19:50
I believe this may have been broken in the original commands lib update but never noticed. Updating from v0.4.10 to v0.5.15 fails with the same error.

**Comment by Stebalien** [comment] 2018-07-05 19:51
Basically, we're now opening the repo every time we run every command.

**Comment by magik6k** [comment] 2018-07-05 19:58
Should be fixable by adding the command to https://github.com/ipfs/go-ipfs/blob/master/cmd/ipfs/ipfs.go#L89

**Comment by Stebalien** [comment] 2018-07-05 20:43
A quick inspection indicates that that won't be sufficient.

However, I'm not sure how this has ever worked properly. Looking at the `ExternalBinary` code, it always calls `GetNode()` (which should lock construct a node and lock the repo).

**Comment by Stebalien** [comment] 2018-07-05 21:04
Yeah... this has been a bug since at least 0.4.6. Upgrading 0.4.6 - 0.4.11 fails.

**Comment by Stebalien** [comment] 2018-07-05 22:10
@lanzafame by the way, thanks for finding this!

**Comment by lanzafame** [comment] 2018-07-06 00:58
@Stebalien no worries, thanks for fixing 👍

**Comment by Stebalien** [comment] 2018-07-09 09:13
So. Bad news. While this bug *has* been fixed, it's a bug in the *current* version of go-ipfs so the fix won't help users of go-ipfs 0.4.15 upgrading to 0.4.16.

**Comment by schomatis** [comment] 2018-08-20 13:43
> So. Bad news. While this bug has been fixed, it's a bug in the current version of go-ipfs so the fix won't help users of go-ipfs 0.4.15 upgrading to 0.4.16.

I'll reopen this issue as the bug still manifests itself to `go-ipfs` users (https://github.com/ipfs/fs-repo-migrations/issues/79).

**Comment by Stebalien** [comment] 2018-08-20 21:11
Unfortunately, there isn't really anything we can do as it's a bug in shipped code. I guess we could have done an intermediate release that fixed the bug without the migration but we didn't want to delay the migration as it fixed a burning IPNS issue.

**Comment by TonyGranato** [comment] 2018-09-19 06:36
Dear all, 

any news on that issue. it still does not work, even manually...:

sh-3.2# ipfs-update install v0.4.17
fetching go-ipfs version v0.4.17
binary downloaded, verifying...
success! tests all passed.
stashing old binary
installing new binary to /usr/local/bin/ipfs
checking if repo migration is needed...
  check complete, migration required.
fetching fs-repo-migrations version v1.4.0
running migration: '/tmp/ipfs-update-migrate196980155/fs-repo-migrations -to 7 -y'
Found fs-repo version 6 at /var/root/.ipfs
===> Running migration 6 to 7...
applying 6-to-7 repo migration
ipfs migration:  migration 6 to 7 failed: cannot acquire lock: Lock FcntlFlock of /var/root/.ipfs/repo.lock failed: resource temporarily unavailable
ERROR: Migration Failed:  migration failed: exit status 1
install failed, reverting changes...
ERROR: migration failed: exit status 1

**Comment by Stebalien** [comment] 2018-12-05 22:40
A bit late but make sure you're mot running IPFS in another process.

(closing as we're not going to be able to do anything about this issue other than field support requests)

**Closed by Stebalien** 2018-12-05 22:40 UTC
Labels: bug
