### ISSUE TITLE
Panic on Ctrl-C to ipfs add

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#4426] opened 2017-11-25 01:31 UTC
#### Description:

```
> cd $GOPATH/src/github.com/ipfs/go-ipfs
> ipfs add -r .
added QmNxgZ2uqh12m9Y2q7gRHQa8hCgXmwf3ZBu2mDz3L6ocUb go-ipfs/CHANGELOG.md
[snip]
 135.70 KB / ? [------------------------------------=---------------------------------------------------------------------------------] ^C
Error: context canceled
panic: context canceled

goroutine 66 [running]:
gx/ipfs/QmamUWYjFeYYzFDFPTvnmGkozJigsoDWUA4zoifTRFTnwK/go-ipfs-cmds.(*chanResponseEmitter).SetError(0xc4201dbda0, 0x12c3420, 0xc420046a10, 0x4)
	/home/user/workspace/gopath/src/gx/ipfs/QmamUWYjFeYYzFDFPTvnmGkozJigsoDWUA4zoifTRFTnwK/go-ipfs-cmds/chan.go:186 +0x121
main.callCommand.func1(0xc4201d0b90, 0x1cb55e0, 0xc4201dbda0, 0x1cb6a40, 0xc4202f0000)
	/home/user/protocol/ipfs/go-ipfs/cmd/ipfs/main.go:369 +0xa6
created by main.callCommand
	/home/user/protocol/ipfs/go-ipfs/cmd/ipfs/main.go:366 +0x9e8
```

**Comment by keks** [comment] 2017-11-27 11:32
Whoopsie! Looking into it

**Comment by keks** [comment] 2017-11-27 14:08
I'm not sure whether this is the right way to do it yet. The issue is that the same error fires at two different places, one of them closes the ResponseEmitter and the other one tries to write, which panics.

A better solution is probably to use `Emit` instead of `SetError`, because that doesn't panic but returns an error. If that error is nil, we can just go on, if there is an error, the responseemitter has already been closed due to an error so we can probably ignore it? I'm not sure though.

This will be cleanly fixed in [cmds1.0], as this is part of "put less burden on the caller". When we are there, this won't even be in main.go anymore.

[cmds1.0]: https://github.com/ipfs/go-ipfs-cmds/issues/25

**Comment by keks** [comment] 2017-11-27 14:13
The branch https://github.com/ipfs/go-ipfs/tree/fix/add-abort-panic currently (i.e. at db32ded) does not panic anymore and it passes the tests. I'm not sure we can consider it fixed though, as it now ignores the error that made this panic in the first place instead of handling it better.

**Comment by keks** [comment] 2017-11-27 14:56
Okay, e654d0c also passes. Here I first try to emit the error and then log it as as error if it fails. That way we at least don't panic anymore, but it's far from a clean solution. @lgierth Do you think we should merge this for now (to get rid if the panic) and clean this up with the cmds1.0 release?

**Comment by lgierth** [comment] 2017-11-28 01:07
I think that LGTM 👍

**Closed** 2017-11-30 12:40 UTC
Labels: commands:add, panic
