### ISSUE TITLE
Add application/json content-type for json files

### ISSUE THREAD

**Issue by andrej-zirko** [ipfs/go-ipfs#5831] opened 2018-12-10 15:50 UTC
Currently IPFS gateway sets text/plain content type for json file. It would be beneficial to detect JSON content. Consumers can then directly parse json IPFS content with application/json content types.

**Comment by Stebalien** [comment] 2018-12-10 17:24
This looks like a duplicate of: https://github.com/ipfs/go-ipfs/issues/2164

(please comment if that's not the case)

**Closed by Stebalien** 2018-12-10 17:24 UTC
