### ISSUE TITLE
ipfs daemon segfault

### ISSUE THREAD

**Issue by myf** [ipfs/go-ipfs#4483] opened 2017-12-13 04:11 UTC
#### Version information:
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2

#### Description:
running ipfs daemon for a few minutes results in segfault
```

API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x17 pc=0x55d286447f83]
```
full err message at https://gist.github.com/myf/3977d92f4459ac5f2e2f5ffa26495176

**Comment by Stebalien** [comment] 2017-12-13 04:53
Well... that's not something you see every day. Looks like a go runtime bug.

I've reported it upstream: https://github.com/golang/go/issues/23114

1. Can you reproduce this reliably?
2. Are you running out of memory? Check `dmesg` for evidence of oom kills (doesn't look like it but let's check).

**Comment by myf** [comment] 2017-12-13 05:23
1. yes just reproduced a couple of times
2. don't think i am running out of memory

**Comment by Stebalien** [comment] 2017-12-13 05:43
That's odd. Normally, bugs like this are really hard to reproduce. Could you try initializing a new repo and reproducing it there (don't blow away your old one, being able to reproduce a bug like this is quite useful).

**Comment by odeke-em** [comment] 2017-12-13 06:54
@myf could you please provide perhaps a link to the source code that's running? Or is it just straight from this repo? If so, what version?

**Comment by odeke-em** [comment] 2017-12-13 07:05
oh nvm, the version information is in the report, thanks @myf.

**Comment by Stebalien** [comment] 2017-12-13 17:56
Would you mind posting your config (`ipfs config show`) sand sensitive information. I'm primarily interested in your repo config and whether or not you have any experimental features enabled.

**Comment by Stebalien** [comment] 2017-12-13 18:04
Do you have fuse enabled by any chance?

**Comment by Stebalien** [comment] 2017-12-13 18:19
If disabling fuse doesn't fix this, try running ipfs with `IPFS_REUSEPORT=false` set (it's an environment variable). That is:

```
> IPFS_REUSEPORT=false ipfs daemon
```

**Comment by myf** [comment] 2017-12-16 00:47
@Stebalien I have just tried running it with `IPFS_REUSERPORT=false` and it crashes again. the crash message is a bit different this time:
```
panic: failed to parse ipfs: ipfs failed to parse ipfs addr: ipfs uvarint: buffer too small

goroutine 113461 [running]:
gx/ipfs/Qmf7GSJ4omRJsvA9uzTqzbnVhq4RWLPzjzW4xJzUta4dKE/go-libp2p-circuit.(*RelayListener).Multiaddr(0xc42027ca50, 0x1, 0x56190a9789c0)
	/build/go-ipfs/src/.gopath/src/gx/ipfs/Qmf7GSJ4omRJsvA9uzTqzbnVhq4RWLPzjzW4xJzUta4dKE/go-libp2p-circuit/listen.go:55 +0x123
gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn.(*listener).Multiaddr(0xc42048c300, 0x7fe13f90b650, 0xc42048c300)
	/build/go-ipfs/src/.gopath/src/gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn/listen.go:122 +0x35
gx/ipfs/QmdQFrFnPrKRQtpeHKjZ3cVNwxmGKKS2TvhJTuN9C9yduh/go-libp2p-swarm.(*Swarm).ListenAddresses(0xc420176700, 0xc4226e4448, 0x1200098de583, 0x78)
	/build/go-ipfs/src/.gopath/src/gx/ipfs/QmdQFrFnPrKRQtpeHKjZ3cVNwxmGKKS2TvhJTuN9C9yduh/go-libp2p-swarm/swarm_addr.go:15 +0x12d
gx/ipfs/QmdQFrFnPrKRQtpeHKjZ3cVNwxmGKKS2TvhJTuN9C9yduh/go-libp2p-swarm.(*Swarm).InterfaceListenAddresses(0xc420176700, 0xc4226e44f8, 0x5619094b11fa, 0xc4226e44e0, 0x5619094cb5f6, 0xc4250b2b80)
	/build/go-ipfs/src/.gopath/src/gx/ipfs/QmdQFrFnPrKRQtpeHKjZ3cVNwxmGKKS2TvhJTuN9C9yduh/go-libp2p-swarm/swarm_addr.go:25 +0x31
gx/ipfs/QmdQFrFnPrKRQtpeHKjZ3cVNwxmGKKS2TvhJTuN9C9yduh/go-libp2p-swarm.(*Network).InterfaceListenAddresses(0xc420176700, 0x0, 0xc4226e4558, 0x0, 0xc425764fc0, 0xc420032a80)
	/build/go-ipfs/src/.gopath/src/gx/ipfs/QmdQFrFnPrKRQtpeHKjZ3cVNwxmGKKS2TvhJTuN9C9yduh/go-libp2p-swarm/swarm_net.go:126 +0x2d
gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/host/basic.(*BasicHost).AllAddrs(0xc420174580, 0x8, 0x8, 0x8)
	/build/go-ipfs/src/.gopath/src/gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/host/basic/basic_host.go:520 +0x4a
gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/host/basic.(*BasicHost).Addrs(0xc420174580, 0xc4248223b8, 0x8, 0x8)
	/build/go-ipfs/src/.gopath/src/gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/host/basic/basic_host.go:514 +0x2d
gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/protocol/identify.(*IDService).populateMessage(0xc420063620, 0xc4220c1dd0, 0x56190a97af00, 0xc427a8cd00)
	/build/go-ipfs/src/.gopath/src/gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/protocol/identify/id.go:169 +0x1c1
gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/protocol/identify.(*IDService).RequestHandler(0xc420063620, 0x56190a97b180, 0xc42175a2c0)
	/build/go-ipfs/src/.gopath/src/gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/protocol/identify/id.go:132 +0x23d
gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/protocol/identify.(*IDService).RequestHandler-fm(0x56190a97b180, 0xc42175a200)
	/build/go-ipfs/src/.gopath/src/gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/protocol/identify/id.go:65 +0x40
gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc4248223a0, 0xe, 0x7fe13f858280, 0xc42175a200, 0xa11d554, 0xc420491f50)
	/build/go-ipfs/src/.gopath/src/gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/host/basic/basic_host.go:320 +0x9f
created by gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
	/build/go-ipfs/src/.gopath/src/gx/ipfs/QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL/go-libp2p/p2p/host/basic/basic_host.go:284 +0x786
```

**Comment by Stebalien** [comment] 2017-12-16 01:11
Yeah... you have a *massive* memory corruption issue (probably). Are you noticing any other system instability (to rule out a hardware issue)?

Would you mind running a custom build (with the race detector enabled) until it crashes? I can compile it for you or you can built it yourself.

**Comment by myf** [comment] 2017-12-16 01:29
i have never seen memory issue from any other programs. I'd be happy to test it on a custom build with the race detector enabled. sorry for the delayed response btw.

**Comment by Stebalien** [comment] 2017-12-16 02:13
No problem at all.  Here's 0.4.13 with the race detector enabled: https://ipfs.io/ipfs/QmbsT1KsRCevBVwrhzrCZ6Q9dVg4Q9Zi1kc2iejB52jckn

Try running it on the command line redirecting any output to a log:

```sh
> ./ipfs daemon > 0.4.13-race.log 2>&1
```

**Comment by myf** [comment] 2017-12-20 20:59
i have yet to reproduce the error from your build, here's what a log ususally looks like
https://gist.github.com/myf/77d2e787b5bf9039de31b0a57192ee68

**Comment by Stebalien** [comment] 2017-12-22 02:20
@myf hm. Unfortunately, those are known issues (they could be causing this problem but it's really unlikely).

**Comment by kris113** [comment] 2018-03-22 13:54
http://localhost:8080/ipns/QmQP99yW82xNKPxXLroxj1rMYMGF6Grwjj2o4svsdmGh7S/wiki/Anasayfa.html
I get segmentation error (core dumped) error when trying to access above url. Im running ipfs deamon in Ubuntu subsytem on windows10.

**Comment by Kubuxu** [comment] 2018-03-23 08:50
@kris113 can you copy whole log? Also the Linux subsystem in past was problematic. Can you try native Windows build?

**Comment by Stebalien** [comment] 2019-05-01 00:07
(closing due to age; please file a new issue if you see this again)

**Closed by Stebalien** 2019-05-01 00:07 UTC
Labels: bug
