### ISSUE TITLE
Goroutine leak and wantlist build-up on master

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#4657] opened 2018-02-04 21:29 UTC
#### Description:

Right after applying 52301ce8 (latest master) to the ipfs.io gateways, there's a severe leak of `briantigerchow/pubsub.(*PubSub).start` goroutines, and wantlist entries start piling up. Within 18 minutes on scrappy, there were 78k goroutines and 1.9k wantlist entries. (It was still able to fetch a simple `date | ipfs add` from my own node, so it wasn't completely locked up.)

- Diff: https://github.com/ipfs/go-ipfs/compare/3f2c7746...52301ce8
- pprof: https://ipfs.io/ipfs/QmZkk8XwFJopBkK8AZxMVXbHk3MjxkxGBZPrUQmK6TdCKu
- Graphs: http://metrics.ipfs.team/dashboard/db/ipfs-v04x?refresh=30s&orgId=1&from=1517776089172&to=1517779689172

For now I've reverted back to 3f2c7746.

**Comment by Stebalien** [comment] 2018-02-05 16:32
Trivial reproduction: cat a file on the local gateway (sessions still aren't used for the `cat` command because that doesn't use the same cat function...).

**Comment by Stebalien** [comment] 2018-02-05 16:35
Ok. *Now* bitswap hangs trying to unsubscribe...

**Comment by Stebalien** [comment] 2018-02-21 00:57
Fixed in https://github.com/ipfs/go-ipfs/pull/4658.

Also, we've disabled bitswap sessions for the gateway (for other performance reasons, for now).

**Closed** 2018-02-21 00:57 UTC
Labels: bug
