### ISSUE TITLE
Error when trying to start the daemon on Windows 10 (Fixed! see bottom)

### ISSUE THREAD

**Issue by vegberg** [ipfs/go-ipfs#1681] opened 2015-09-10 18:03 UTC
When trying to run `ipfs daemon` through command prompt, this error appears.

    C:\Users\Vegard Berg>ipfs daemon
    Error: Post http://127.0.0.1:5001/api/v0/version?enc=json&stream-channels=true: dial tcp 127.0.0.1:5001: connectex: No connection could be made because the target machine actively refused it.

I'm running on Windows 10, which was upgraded from Windows 8.1

**EDIT**: Removing .ipfs and then doing `ipfs init` makes the daemon run again, but then I lose everything.

**Comment by jbenet** [comment] 2015-09-14 05:26
dupe of #1661? 

for the record, windows is not fully supported yet. if anyone here can help us more, that would be great.

i suspect it's some `filepath` lack of use

**Comment by interfect** [comment] 2015-09-16 03:09
I had the same problem on Windows 7, and deleting the .ipfs directory worked for me as well.

FWIW I shut down the daemon last time by just shutting down the computer. Maybe it corrupted something.

**Comment by DavidBurela** [comment] 2015-09-27 01:03
I am getting the same issue. After closing a daemon it will not run again unless you init

**Environment:**
Windows 10.
ipfs_master_windows-amd64 0.3.8-dev

**Repo steps:**
 - ipfs init
 - ipfs daemon
  - _Initializing daemon...  Daemon is ready_
 - ^c to kill the instance
  - Received interrupt signal, shutting down...
 - ipfs daemon
  - _Error: Post http://127.0.0.1:5001/api/v0/version?enc=json&stream-channels=true: dial tcp 127.0.0.1:5001: connectex: No connection could be made because the target machine actively refused it._
 - ipfs init -f
 - ipfs daemon
  - _Initializing daemon...  Daemon is ready_

**Comment by jbenet** [comment] 2015-09-27 01:16
Try downloading latest from:




https://gobuilder.me/github.com/ipfs/go-ipfs/cmd/ipfs




—

**Comment by DavidBurela** [comment] 2015-09-27 01:27
That fixed it. The new build from 2 hours ago no longer has this issue.

**Comment by jbenet** [comment] 2015-09-27 03:17
Great! I'll leave this open until we cut the `0.3.8` release for people who find this.

## This is fixed, download latest from https://gobuilder.me/github.com/ipfs/go-ipfs/cmd/ipfs

**Comment by rht** [comment] 2015-11-05 00:32
Can be closed.

**Closed** 2015-11-05 07:19 UTC

**Comment by vurumadla** [comment] 2017-10-16 05:03
hi i am facing the same issue while trying to run and access daemon through application in centos

request.js:143 POST http://localhost:5001/api/v0/add?stream-channels=true net::ERR_CONNECTION_REFUSED
