### ISSUE TITLE
ipfs ping should exit non-zero on fail

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1041] opened 2015-04-08 12:37 UTC
Today:

```
> ipfs ping QmaQgJV44WPhTwwPWFYsiuSNeW3o5mNVnYns7PdEpCjdyz
Looking up peer QmaQgJV44WPhTwwPWFYsiuSNeW3o5mNVnYns7PdEpCjdyz
Peer lookup error: routing: not found
> echo $?
0
```

https://github.com/ipfs/infrastructure/issues/11#issuecomment-90898787

**Comment by wking** [comment] 2015-06-24 09:03
On Wed, Apr 08, 2015 at 05:37:24AM -0700, Juan Batiz-Benet wrote:
> > ipfs ping QmaQgJV44WPhTwwPWFYsiuSNeW3o5mNVnYns7PdEpCjdyz
> Looking up peer QmaQgJV44WPhTwwPWFYsiuSNeW3o5mNVnYns7PdEpCjdyz
> Peer lookup error: routing: not found
> > echo $?
> 0

It's not the same command, but I expect the underlying issue here is
the same as #984.  I've got a fix for passing error statuses for
streaming commands between a client and daemon in #1413
(commands/http/handler: Write a trailer with any error messages), but
I haven't checked to see if ping or ‘dht get’ are streaming (I'd guess
not, but who knows :).

**Comment by whyrusleeping** [comment] 2016-01-02 02:20
duplicate of #984

**Closed by whyrusleeping** 2016-01-02 02:20 UTC
Labels: bug, commands
