### ISSUE TITLE
Bug: Full path in symlink on windows

### ISSUE THREAD

**Issue by ivan386** [ipfs/go-ipfs#5225] opened 2018-07-13 17:40 UTC
#### Version information:
go-ipfs version: 0.4.16-
Repo version: 7
System version: amd64/windows
Golang version: go1.10.2

#### Description:

```
>ipfs add -r "D:\symlink_test"
added QmbqVqMVvaDi96Wqv4uKWXhTnp6dVGrMFYXneCms5kwpQt symlink_test/symlink_to_test
 0 B / ? [-------------------------------------------------------------------------------------------
added QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn symlink_test/test
 0 B / ? [-------------------------------------------------------------------------------------------
added QmaVcUhni47SSnsVqMw53xW1Fkq5BrPQCVCHsc8Bdg2ZtJ symlink_test
 0 B / ? [-------------------------------------------------------------------------------------------
```

```
>ipfs block get QmbqVqMVvaDi96Wqv4uKWXhTnp6dVGrMFYXneCms5kwpQt

D:\symlink_test\test
```

**Comment by magik6k** [comment] 2018-07-14 08:51
cc @djdv

**Comment by ivan386** [comment] 2018-07-14 13:52
On drive d: create 2 directory. 
1. symlink_test
2. symlink_test/test

And make juction point to "test" as "symlink_to_test"

When add it to ipfs
```ipfs add -r "D:\symlink_test"```
It created 3 blocks.
1. `added QmbqVqMVvaDi96Wqv4uKWXhTnp6dVGrMFYXneCms5kwpQt symlink_test/symlink_to_test`
 Symlink block
2. `added QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn symlink_test/test`
 Empty directory
3. `added QmaVcUhni47SSnsVqMw53xW1Fkq5BrPQCVCHsc8Bdg2ZtJ symlink_test`
 Root directory

When i look in content of symlink block i see full path in it.

```
>ipfs block get QmbqVqMVvaDi96Wqv4uKWXhTnp6dVGrMFYXneCms5kwpQt

���D:\symlink_test\test
```
There must be relative path. And maybe in unix style.
```test```
or
```./test```

**Comment by djdv** [comment] 2018-07-20 17:41
@ivan386 
I believe this is the intended behaviour. Junctions can only be absolute paths, and you are adding the junction, as a link (who's target is absolute). For your case here, you would instead create a symbolic link, which can be relative.
```
md symlink_test
cd symlink_test
md test
mklink /D symlink_test test
ipfs add -r "D:\symlink_test"
```
For me, the result:
```
ipfs block get QmdaH1brf4LgVBVerDETfYu1Unsez9yeBxDvktnsBku5S7

test
```

**Comment by ivan386** [comment] 2018-07-20 18:45
On Windows XP available only junction points. In both cases ipfs make symlink block. Difference only in path.

Need to convert full path to relative when add junction point to ipfs.

Full path is useless on gateway and on other file system. If on target system need full path than it can be build from relative.

**Comment by djdv** [comment] 2018-10-30 13:48
Closing this as this is standard/intended behavior of NT "junctions", which are not semantically "symlinks".

**Closed by djdv** 2018-10-30 13:48 UTC
Labels: windows
