### ISSUE TITLE
Crash on shutdown - panic: Process cannot add children after being closed

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7989] opened 2021-03-18 09:12 UTC
#### Version information:
go-ipfs version: 0.9.0-dev-3393b4a39
Repo version: 11
System version: amd64/linux
Golang version: go1.16.2

#### Description:
I've stopped the IPFS daemon and the daemon crashed with a stack trace:

```
Mär 18 07:53:11 i3 ipfs[3089088]: Initializing daemon...
Mär 18 07:53:11 i3 ipfs[3089088]: go-ipfs version: 0.9.0-dev-3393b4a39
Mär 18 07:53:11 i3 ipfs[3089088]: Repo version: 11
Mär 18 07:53:11 i3 ipfs[3089088]: System version: amd64/linux
Mär 18 07:53:11 i3 ipfs[3089088]: Golang version: go1.16.2
Mär 18 07:55:35 i3 ipfs[3089088]: panic: Process cannot add children after being closed
Mär 18 07:55:35 i3 ipfs[3089088]: goroutine 1 [running]:
Mär 18 07:55:35 i3 ipfs[3089088]: github.com/jbenet/goprocess.(*process).AddChild(0xc002f89080, 0x55c0ad48cab0, 0xc003d289c0)
Mär 18 07:55:35 i3 ipfs[3089088]:         /home/ruben/.cache/yay/go-ipfs-git/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:99 +0x2a5
Mär 18 07:55:35 i3 ipfs[3089088]: main.daemonFunc(0xc000914000, 0x55c0ad4798c8, 0xc00089bda0, 0x55c0ad30ca60, 0xc00089bd40, 0x0, 0x0)
Mär 18 07:55:35 i3 ipfs[3089088]:         /home/ruben/.cache/yay/go-ipfs-git/src/go-ipfs/cmd/ipfs/daemon.go:396 +0x912
Mär 18 07:55:35 i3 ipfs[3089088]: github.com/ipfs/go-ipfs-cmds.(*executor).Execute(0xc0000105d0, 0xc000914000, 0x55c0ad4798c8, 0xc00089bda0, 0x55c0ad30ca60, 0xc00089bd40, 0xc00089bda0, 0x0)
Mär 18 07:55:35 i3 ipfs[3089088]:         /home/ruben/.cache/yay/go-ipfs-git/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.6.0/executor.go:77 +0x16b
Mär 18 07:55:35 i3 ipfs[3089088]: github.com/ipfs/go-ipfs-cmds/cli.Run(0x55c0ad4794d8, 0xc0006f2c80, 0x55c0ae03faa0, 0xc000180050, 0x5, 0x5, 0xc0001b6000, 0xc0001b6008, 0xc0001b6010, 0x55c0ad429528, ...)
Mär 18 07:55:35 i3 ipfs[3089088]:         /home/ruben/.cache/yay/go-ipfs-git/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.6.0/cli/run.go:137 +0xac5
Mär 18 07:55:35 i3 ipfs[3089088]: main.mainRet(0x0)
Mär 18 07:55:35 i3 ipfs[3089088]:         /home/ruben/.cache/yay/go-ipfs-git/src/go-ipfs/cmd/ipfs/main.go:168 +0x45e
Mär 18 07:55:35 i3 ipfs[3089088]: main.main()
Mär 18 07:55:35 i3 ipfs[3089088]:         /home/ruben/.cache/yay/go-ipfs-git/src/go-ipfs/cmd/ipfs/main.go:71 +0x25
Mär 18 07:55:35 i3 systemd[1]: ipfs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mär 18 07:55:35 i3 systemd[1]: ipfs.service: Failed with result 'exit-code'.
```

**Comment by Stebalien** [comment] 2021-03-23 16:02
This is a duplicate of https://github.com/ipfs/go-ipfs/issues/7027. I've added your stack trace there.

**Closed by Stebalien** 2021-03-23 16:02 UTC
Labels: kind/bug, need/triage
