### ISSUE TITLE
domain names in config for bootstrap nodes

### ISSUE THREAD

**Issue by cminnoy** [ipfs/go-ipfs#2921] opened 2016-06-29 20:25 UTC
Version 0.4.1

I have two nodes, both on a different ISP.
I would like to have both set in the configuration file as bootstrap nodes.
My ISP delivers only Dynamic IPs and I would like to use the dynamic DNS feature.
Up to version 0.4.1 it seems IPFS doesn't accept domain names in the config file so a dynamic IP setup doesn't work well. Any possibility to add this feature?

Cheers,

Chris

**Comment by Kubuxu** [comment] 2016-06-29 20:42
Duplicate of https://github.com/ipfs/go-ipfs/issues/1485

**Closed by Kubuxu** 2016-06-29 20:43 UTC
