### ISSUE TITLE
test failure in namesys/republisher

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3735] opened 2017-02-28 17:22 UTC
```
--- FAIL: TestRepublish (0.66s)

	repub_test.go:64: failed to find any peer in table

FAIL

FAIL	github.com/ipfs/go-ipfs/namesys/republisher	0.719s
```

**Comment by mateon1** [comment] 2017-02-28 23:51
Duplicate of #3197

**Closed** 2017-03-01 09:03 UTC
Labels: test failure
