### ISSUE TITLE
OOMKill under high CPU and memory usage 

### ISSUE THREAD

**Issue by tsoeiroecore** [ipfs/go-ipfs#8697] opened 2022-01-24 18:48 UTC
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.io

### Version

```Text
go-ipfs version: 0.11.0-67220ed
Repo version: 11
System version: amd64/linux
Golang version: go1.16.7
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/0.0.0.0/tcp/5001",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/0.0.0.0/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip6/::/udp/4001/quic"
    ]
  },
  "AutoNAT": {
    "ServiceMode": "disabled"
  },
  "Bootstrap": [
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"
  ],
  "DNS": {
    "Resolvers": {}
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "12D3KooWST54c2neCKi1derUamVdkZQ6d7Vg45jC6CikMJhBNy6u"
  },
  "Internal": {},
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "0",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "dhtclient"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "1m0s",
      "HighWater": 40,
      "LowWater": 20,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": true,
    "DisableNatPortMap": false,
    "RelayClient": {},
    "RelayService": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description

Under heavy load, my IPFS daemon gets OOMkilled
I have an AWS EC2 instance with 29GB and memory reaches the limit in less than a hour.

<img width="255" alt="Screen Shot 2022-01-24 at 15 35 20" src="https://user-images.githubusercontent.com/81694338/150843242-4e0380a8-5e03-4a7c-85f3-8094910952d1.png">

Exact same problem is reproducible in a IPFS daemon running locally via docker.
Profile archive: [ipfs-profile-192.168.68.107-2022-01-24T11:12:00-0300.tar.gz](https://github.com/ipfs/go-ipfs/files/7928020/ipfs-profile-192.168.68.107-2022-01-24T11.12.00-0300.tar.gz)

Hundreds of `ipfs get `requests running in parallel in a row, during some period of time will cause this issue

I've tried several different configurations with no success:
```
IPFS_PROFILE=lowpower
ipfs config Routing.Type "dhtclient"
ipfs config AutoNAT.ServiceMode "disabled"
ipfs config Reprovider.Interval "0"
ipfs config Swarm.ConnMgr.LowWater 20
ipfs config Swarm.ConnMgr.HighWater 40
ipfs config Swarm.ConnMgr.GracePeriod "60s"
ipfs config --bool Swarm.DisableBandwidthMetrics true
```

It's a similar issue to these:
- https://github.com/ipfs/go-ipfs/issues/7954
- https://github.com/ipfs/go-ipfs/issues/8314

**Comment by aschmahmann** [comment] 2022-01-28 16:27
@tsoeiroecore I'm closing this as a duplicate of the other issues you linked as being the same as this one (the GitHub links between the issues will persist).

The closer to reproducible you can make this for folks to debug the easier it will be, as of right now the only information is your config and the number of requests you've made but there's no information about the shape of the DAGs or a good way for someone to predictably reproduce your issue.

**Closed by aschmahmann** 2022-01-28 16:27 UTC
Labels: kind/bug, need/triage
