### ISSUE TITLE
`ipfs shutdown` test randomly fails

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4303] opened 2017-10-13 13:18 UTC
I'm getting this:

```
[36mexpecting success: 
	ipfs shutdown
(B[m
Error: Post http://127.0.0.1:37556/api/v0/shutdown?encoding=json&stream-channels=true: EOF
[1m[31mnot ok 8 - shutdown succeeds(B[m
#	
#		ipfs shutdown
#	
```

Which I thought we had resolved already...

**Comment by Stebalien** [comment] 2017-10-13 15:33
Nope. Duplicate of #4055.

**Closed by Stebalien** 2017-10-13 15:33 UTC
