### ISSUE TITLE
certificate is not valid for ipfs.io 

### ISSUE THREAD

**Issue by SeavantUUz** [ipfs/go-ipfs#4745] opened 2018-03-01 10:12 UTC
when I run `make install` for ipfs, error msgs occurred as below.

```
ERROR: [61 / 97 ] parallel fetch: failed to fetch package: QmY9JXR3FupnYAYJWK9aMr9bCpqWKcToQ1tz8DVGTrHpHw: Post https://ipfs.io/api/v0/get?arg=QmY9JXR3FupnYAYJWK9aMr9bCpqWKcToQ1tz8DVGTrHpHw&encoding=json&stream-channels=true: x509: certificate is valid for *.facebook.com, *.xx.fbcdn.net, *.fbsbx.com, *.xz.fbcdn.net, *.facebook.net, *.xy.fbcdn.net, *.messenger.com, fb.com, *.fbcdn.net, *.fb.com, *.m.facebook.com, messenger.com, facebook.com, not ipfs.io
```

As I noticed, each fetching actions to ipfs.io bumped the same msg and which looks obviously -- the certificate somehow went wrong .

How did it happen, or, how could I resolve these issues. 

Thx.

**Comment by Kubuxu** [comment] 2018-03-01 19:42
It seems like a problem on your side, looks like `ipfs.io` was redirected somehow to facebook IPs.

**Comment by SeavantUUz** [comment] 2018-03-02 07:08
Finally, I silenced these err msgs after I run an ipfs daemon on the machine. Just download the `dist` version and run it as a pre-condition. the reason is , the dependencies' path in the source marked by the way of ipfs itself. like `u "gx/ipfs/QmNiJuT8Ja3hMVpBHXv3Q6dwmperaQ6JjLtpMQgMCD7xvx/go-ipfs-util"`

is it interesting ? or have I made some mistakes? if not, shouldn't it be written in the readme file?

**Comment by djdv** [comment] 2018-03-02 14:27
@SeavantUUz 
Is it possible the national firewall is causing issues with the `ipfs.io` domain?
A friend of mine in Guangxi _sometimes_ has issues downloading from the public gateway but does not have issues getting content from me directly with `ipfs get` which is similar to how `gx` works if you have a local daemon running, you will fetch content from nodes directly over ipfs instead of over http.

**Comment by woodenfish** [comment] 2018-05-30 10:19
Seam problem, The reason is dns server return wrong ip, So just add a line "209.94.78.78 ipfs.io" to /etc/hosts, problem will be solved.

**Comment by Kubuxu** [comment] 2018-06-01 12:27
As others pointed out, the cause behind this issue is governments hijacking `ipfs.io` domain. I'm closing the issue as there is nothing we can do in go-ipfs to resolve this.

**Closed by Kubuxu** 2018-06-01 12:27 UTC
