### ISSUE TITLE
Cannot publish to IPNS

### ISSUE THREAD

**Issue by devanshusehgal** [ipfs/go-ipfs#7285] opened 2020-05-07 17:48 UTC
#### Version information:

go-ipfs version: 0.5.0
Repo version: 9
System version: amd64/linux
Golang version: go1.13.10

#### Description:

Whenever I try to execute `ipfs name publish website-hash`, the command runs for 1 minute and then I get the message **"Error: context deadline exceeded"**.

![ls](https://user-images.githubusercontent.com/38864946/81327418-d7600d80-90b8-11ea-8045-b195fee663c2.png)

![deadline](https://user-images.githubusercontent.com/38864946/81327435-dfb84880-90b8-11ea-93c1-bdd2eea08715.png)

IPFS Daemon is running and in the Peers page it says 500+ peers.

**Comment by RubenKelevra** [comment] 2020-05-07 23:35
Hey @devanshusehgal 

thanks for your report!

I think this bug has already be fixed in the `master`: https://github.com/ipfs/go-ipfs/commit/52344abd313d6715caf73c0045709f0d0a3f1e49

So the next point release will include this fix!

**Comment by aschmahmann** [comment] 2020-05-08 00:25
Thanks @devanshusehgal, this is a duplicate of #7244

**Closed by aschmahmann** 2020-05-08 00:25 UTC
Labels: kind/bug, need/triage
