### ISSUE TITLE
Illegal tag 0

### ISSUE THREAD

**Issue by ConsciousCode** [ipfs/go-ipfs#2211] opened 2016-01-17 02:53 UTC
Every few minutes my local daemon will emit an error, saying the following:

> 19:50:41.655 ERROR     swarm2: swarm listener accept error: proto: spipe_pb.Propose: illegal tag 0 (wire type 0) swarm_listen.go:129

I don't know what other information would help.

**Comment by whyrusleeping** [comment] 2016-01-17 04:51
@ConsciousCode this is caused by old nodes (0.3.*) trying to connect to newer nodes (on 0.4.0). It generally only happens when you have two different versioned nodes on the same LAN, so that they find eachother through mdns discovery. I don't know that I want to silence this error, because any other time we see an error from here, its going to be important (probably, I could be wrong).

**Comment by ConsciousCode** [comment] 2016-01-17 04:57
Another daemon I'm running on my VPS gave the same errors. I recently updated both instances using ipfs-update and fs-repo-migrations and both say their versions are 0.4.0-dev. So I guess the error is generated by interactions with other out-of-date peers?

This thread has use in that anyone who's even casually interested in the development will wonder where the errors are coming from - I couldn't find this in any of the open issues.

**Comment by whyrusleeping** [comment] 2016-01-17 06:42
@ConsciousCode indeed. I'll keep this one open until some time after the official 0.4.0 release so that anyone who sees this problem can see what causes it and that its nothing to worry about (unless they suspect its causing problems, at which point they should let us know)

**Comment by whyrusleeping** [comment] 2016-08-19 16:44
Its now 'some time' after the 0.4.0 release, closing now :)

**Closed by whyrusleeping** 2016-08-19 16:44 UTC
