### ISSUE TITLE
Ipfs Crashes with a stacktrace

### ISSUE THREAD

**Issue by YugankRastogi** [ipfs/go-ipfs#7853] opened 2021-01-08 14:06 UTC
#### Version information:
go-ipfs version: 0.8.0-dev-931ad5b00-dirty
Repo version: 10
System version: amd64/windows
Golang version: go1.15.6

#### Description:
IPFS node crashes on a private network occasionally

Stacktrace:
github.com/libp2p/go-libp2p-pnet.(*pskConn).Read(0xc0086ab5c0, 0xc0057c8a88, 0x2, 0x2, 0xc003095b30, 0xcbc08c, 0x1d8da80)
        pkg/mod/github.com/libp2p/go-libp2p-pnet@v0.2.0/psk_conn.go:43 +0x24c
io.ReadAtLeast(0x1d1fd51d710, 0xc0086ab5c0, 0xc0057c8a88, 0x2, 0x2, 0x2, 0x1000, 0x0, 0xc003095ba8)
        C:/Go/src/io/io.go:314 +0x8e
io.ReadFull(...)
        C:/Go/src/io/io.go:333
github.com/libp2p/go-libp2p-noise.(*secureSession).readNextInsecureMsgLen(0xc0057c8a00, 0x0, 0xc003095be8, 0xd19bfe)
        pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.1/rw.go:134 +0x93
github.com/libp2p/go-libp2p-noise.(*secureSession).Read(0xc0057c8a00, 0xc000a2e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.1/rw.go:53 +0x205
bufio.(*Reader).fill(0xc003df4120)
        C:/Go/src/bufio/bufio.go:101 +0x10a
bufio.(*Reader).ReadByte(0xc003df4120, 0xc0054ecdc8, 0xd09c1f0866910, 0x0)
        C:/Go/src/bufio/bufio.go:253 +0x45
encoding/binary.ReadUvarint(0x2340880, 0xc003df4120, 0xd1f332, 0xc0054ecdc8, 0x1)
        C:/Go/src/encoding/binary/varint.go:110 +0x8d
github.com/libp2p/go-mplex.(*Multiplex).readNextHeader(0xc008496d00, 0xc003095d01, 0x4, 0x0, 0x0)
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:548 +0x46
github.com/libp2p/go-mplex.(*Multiplex).handleIncoming(0xc008496d00)
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:367 +0xef
created by github.com/libp2p/go-mplex.NewMultiplex
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:105 +0x212

**Comment by jacobheun** [comment] 2021-01-08 18:45
How did you generate the private keys and can you provide any other dumps or stack traces with this? The line in error on the stack trace isn't sufficient for figuring out what's going on here.

**Comment by Stebalien** [comment] 2021-03-31 20:57
This is a duplicate of #6802

**Closed by Stebalien** 2021-03-31 20:57 UTC
Labels: kind/bug, need/triage
