### ISSUE TITLE
CID generated with `ipfs object put` crashes `ipfs files rm`

### ISSUE THREAD

**Issue by KB1RD** [ipfs/go-ipfs#8144] opened 2021-05-17 16:26 UTC
**Describe the bug**
Once adding said CID, the files page becomes blank each time you open it. You must hit the back button and refresh the page to make it go away. I tried removing all pins, garbage collecting the local repo, and destroying all local browser data. Only nuking the whole data directory for IPFS seems to make it go back to normal. 

**To Reproduce**
1. Run `echo '{ "Data": "abc" }' | ipfs object put`. This should output `QmXg9Pp2ytZ14xgmQjYEiHjVjMFXzCVVEcRTWJBmLgR39V`.
2. Click on the Files tab, click "Import", click "From IPFS", enter this CID.
3. The screen will now become blank and you will never be able to access the files tab. I recovered only by destroying my node (installed via snap): `rm -rf ~/snap/ipfs/common/*`

**Expected behavior**
This shouldn't happen.

**Screenshots**
It's just a white screen. There are some ambiguous errors in console.

**Desktop (please complete the following information):**
 - OS: Linux ubuntu-ryzen-desktop 5.4.0-42-generic ipfs/ipfs-webui#46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Browser Firefox 
 - Version 88.0.1 (installed via `apt`)

**Smartphone (please complete the following information):**
N/A

**Additional context**
IPFS at latest Snap version.

**Comment by lidel** [comment] 2021-05-18 01:11
@KB1RD  thank you for filling this, `ipfs object` API is being deprecated (https://github.com/ipfs/go-ipfs/issues/7936) in favor of `ipfs dag` and `dag-cbor`, consider moving away from using it. Still, this is a bug, and should be fixed.

----

_(moving to go-ipfs, as this is MFS/Object API bug)_

I can confirm this is a bug present in  go-ipfs 0.9.0-rc1.

Copying problematic DAG  to MFS works.
 `ipfs files ls` also works, but `ipfs ls` with direct CID of the parent dir with problematic DAG produces error:

```
$ echo '{ "Data": "abc" }' | ipfs object put
QmXg9Pp2ytZ14xgmQjYEiHjVjMFXzCVVEcRTWJBmLgR39V

$ ipfs files mkdir /my-dir
$ ipfs files cp /ipfs/QmXg9Pp2ytZ14xgmQjYEiHjVjMFXzCVVEcRTWJBmLgR39V /my-dir/foo

$ ipfs files ls /my-dir
foo

$ ipfs ls $(ipfs files stat --hash /my-dir)
Error: unexpected EOF
```

Then, it is impossible to remove the object, it seems:

```
$ ipfs files rm /my-dir/foo 
Error: unexpected EOF
```

**Comment by lidel** [comment] 2021-05-18 01:18
Ok, this seems to be a duplicate of https://github.com/ipfs/go-ipfs/issues/7999#issuecomment-804312497 so I'm closing this, as we no longer support `ipfs object` API.

@KB1RD  for now, you can fix this by removing problematic file with `--force`:

```
$ ipfs files rm --force /my-dir/foo 
```

**Closed by lidel** 2021-05-18 01:18 UTC
Labels: need/triage
