### ISSUE TITLE
adding no-announce filter to default profile

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#6926] opened 2020-02-24 22:21 UTC
Currently, the server profile got a no-announce filter for private subnetworks (IPv4/6).

I think this should be standard for the default profile as well. There's no need to announce the private IPs to the internet. Usual home users probably just want to use mDNS.

**Comment by Stebalien** [comment] 2020-02-25 23:41
Duplicate of https://github.com/libp2p/go-libp2p/issues/436 and https://github.com/libp2p/go-libp2p/issues/793.

I'm opening a single go-ipfs meta issue so we can close all the related issues: https://github.com/ipfs/go-ipfs/issues/6932

**Closed by Stebalien** 2020-02-25 23:41 UTC
Labels: enhancement
