### ISSUE TITLE
Direct pins

### ISSUE THREAD

**Issue by ambertch** [ipfs/go-ipfs#5169] opened 2018-06-29 06:36 UTC
I'm writing a utility to pin content as direct pins, so as to know that only that content is being pinned.

When I add pins, then view them via a `pin ls`, all pins are either recursive or indirect.

It seems like PinWithMode() is the only method through which direct pins can be made, and this is not exposed through any client APIs https://github.com/ipfs/go-ipfs/blob/master/pin/pin.go#L603

Is there a client accessible way to do direct pinning, or should I just validate that recursive pins are only made on files?

Thanks!

**Comment by Stebalien** [comment] 2018-06-30 00:19
You can use `ipfs pin add --recursive=false /ipfs/...` to pin a path directly (not recursive).

**Comment by Stebalien** [comment] 2018-06-30 19:15
Closing for tracking purposes.

**Closed by Stebalien** 2018-06-30 19:15 UTC
Labels: question

**Comment by EnchanterIO** [comment] 2023-02-15 11:09
If anyone else stumbles upon how to create a direct pin:
1. Add a tiny file with few chars to the IPFS node using `ipfs add` but without pinning: `ipfs add --pin=false /Users/lukas/Downloads/direct.txt`
2. Pin it but not recursively as Steven suggested `ipfs pin add --recursive=false QmY1kQFspUxDYQ5VkjPn9yJFjhQBSuoboreQo6PPdkN2hk`

Result:

```
ipfs pin ls
...
QmY1kQFspUxDYQ5VkjPn9yJFjhQBSuoboreQo6PPdkN2hk direct
...

```

**Comment by Jorropo** [comment] 2023-02-15 11:46
@EnchanterIO 
> QmY1kQFspUxDYQ5VkjPn9yJFjhQBSuoboreQo6PPdkN2hk **direct**

it works as intended.

**Comment by EnchanterIO** [comment] 2023-02-15 11:48
Yes indeed. I was just trying to create a direct pin so I can test what happens if one pins recursively a direct pin, spoiler: it converts to recursive.
