### ISSUE TITLE
v0.9.0 panics on OpenBSD

### ISSUE THREAD

**Issue by qbit** [ipfs/go-ipfs#8211] opened 2021-06-23 12:06 UTC
#### Version information:

go-ipfs version: 0.9.0
Repo version: 11
System version: amd64/openbsd
Golang version: go1.16.5

#### Description:

After running for a period of time, `ipfs daemon` panics with the following:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9f7872]

goroutine 270 [running]:
github.com/multiformats/go-multiaddr/net.(*maListener).Accept(0xc0006b49a0, 0xc00287de18, 0xb23a5d, 0xc000019980, 0xc008136a40)
        /build/pobj/go-ipfs-0.9.0/go/pkg/mod/github.com/multiformats/go-multiaddr@v0.3.2/net/net.go:259 +0x112
github.com/libp2p/go-tcp-transport.(*tcpListener).Accept(0xc0007af950, 0xc00287de70, 0xc00287de78, 0x20, 0xc0007d8a80)
        /build/pobj/go-ipfs-0.9.0/go/pkg/mod/github.com/libp2p/go-tcp-transport@v0.2.2/tcp.go:66 +0x37
github.com/libp2p/go-tcp-transport.(*tracingListener).Accept(0xc0001636f0, 0x0, 0x0, 0xc001438fc0, 0x1adbf60)
        /build/pobj/go-ipfs-0.9.0/go/pkg/mod/github.com/libp2p/go-tcp-transport@v0.2.2/metrics.go:226 +0x37
github.com/libp2p/go-libp2p-transport-upgrader.(*listener).handleIncoming(0xc001438fc0)
        /build/pobj/go-ipfs-0.9.0/go/pkg/mod/github.com/libp2p/go-libp2p-transport-upgrader@v0.4.2/listener.go:77 +0xf7
created by github.com/libp2p/go-libp2p-transport-upgrader.(*Upgrader).UpgradeListener
        /build/pobj/go-ipfs-0.9.0/go/pkg/mod/github.com/libp2p/go-libp2p-transport-upgrader@v0.4.2/upgrader.go:49 +0x18d
```

The daemon also produces a plethora of this error while running:
```
2021-06-23T06:01:16.574-0600    ERROR   tcp-tpt go-tcp-transport@v0.2.2/tcp.go:45       Failed set keepalive period: set tcp4 REDACTED:1777->REDACTED:30504: protocol not available
```

**Comment by qbit** [comment] 2021-06-23 12:22
The error from the keepalive bit seems to be from https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/net/tcpsockopt_openbsd.go#L13

So that might not be the issue.

**Comment by marten-seemann** [comment] 2021-06-23 17:46
Agreed, this is definitely not related to the socket option.

The problem is in https://github.com/multiformats/go-multiaddr/blob/2f4fae4104af2df7036afcdd93d2075845e68ed0/net/net.go#L234-L267. 
It looks like the `net.Listener` returns a `net.Conn` where the `LocalAddr()` is `nil`. It looks like the problem was introduced in https://github.com/multiformats/go-multiaddr/pull/135, which was merged after the v0.3.1 release, so it makes sense that this only occurs now.

Now I'm not sure why a `net.Conn` would return `nil` in `LocalAddr()`, I would have expected it to return a non-nil value in every case. The easy fix is to guard against unexpected `nil` values, if we can't come up with a reasonable explanation here.

**Comment by qbit** [comment] 2021-06-23 19:49
I figure this is more of a question for this thread:

Given https://github.com/libp2p/go-tcp-transport/pull/80#issuecomment-867109303 👍 👍 
> I guess OpenBSD users then have to live with a slightly suboptimal behavior then

It looks like go-tcp-transport just sets it to 30 seconds. I maintain the port of go-ipfs on OpenBSD and we have a doc that makes a number of [tuning recommendations](https://github.com/openbsd/ports/blob/master/net/go-ipfs/pkg/README) - Would recommending that users set their timout to 30 seconds be worth mentioning?

**Comment by marten-seemann** [comment] 2021-06-24 01:48
We probably should keep this open until the change is bubbled up here.

**Closed** 2021-06-24 03:17 UTC
Labels: kind/bug, need/triage

**Comment by marten-seemann** [comment] 2021-06-24 04:28
@qbit depending on the default value that OpenBSD used, it might or might not be worth it.
