### ISSUE TITLE
badgerds segfault

### ISSUE THREAD

**Issue by sneak** [ipfs/go-ipfs#5599] opened 2018-10-15 01:58 UTC
#### Version information:

go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/linux
Golang version: go1.10.3

#### Type:

Bug

#### Description:

Crash during `ipfs add`

```
 49.76 GiB / 207.24 GiB   24.01% 1h18m54s
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
 49.93 GiB / 207.24 GiB   24.09% 1h18m49spanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf768a2]

goroutine 22575756 [running]:
gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger/skl.(*Skiplist).IncrRef(...)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger/skl/skl.go:86
gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger.(*DB).getMemTables(0xc420593c00, 0x0, 0x0, 0x0, 0x0)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger/db.go:472 +0xd2
gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger.(*DB).get(0xc420593c00, 0xc42f0ea0a0, 0x4a, 0x4a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger/db.go:496 +0x66
gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger.(*Txn).Get(0xc445fc2240, 0xc42f0ea050, 0x42, 0x50, 0x42, 0x50, 0xc42a4643f0)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmb3GBFCHMuzmi9EpH3pxpYBiviyc3tEPyDQHxZJQJSxj9/badger/transaction.go:388 +0x109
gx/ipfs/QmQoiqmV9gAKEQAELqeGACQwXyDeijE6fq7ARhirPMX2T2/go-ds-badger.(*datastore).Has(0xc4202ea1c0, 0xc42f0ea000, 0x42, 0xc42057c900, 0x0, 0x0)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmQoiqmV9gAKEQAELqeGACQwXyDeijE6fq7ARhirPMX2T2/go-ds-badger/datastore.go:114 +0xbe
gx/ipfs/QmPMRquZA1WiRMQ5ZE2V1kHtnPaq2X5Qtz7Wgwwo2tjLyS/go-ds-measure.(*measure).Has(0xc4205e8000, 0xc42f0ea000, 0x42, 0xc42057dd00, 0x0, 0x0)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmPMRquZA1WiRMQ5ZE2V1kHtnPaq2X5Qtz7Wgwwo2tjLyS/go-ds-measure/measure.go:157 +0xd4
gx/ipfs/QmPMRquZA1WiRMQ5ZE2V1kHtnPaq2X5Qtz7Wgwwo2tjLyS/go-ds-measure.(*measure).Has(0xc4205e81e0, 0xc42f0ea000, 0x42, 0x8ce600, 0x0, 0x0)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmPMRquZA1WiRMQ5ZE2V1kHtnPaq2X5Qtz7Wgwwo2tjLyS/go-ds-measure/measure.go:157 +0xd4
gx/ipfs/QmeiCcJfDW1GJnWUArudsv5rQsihpi4oyddPhdqo3CfX6i/go-datastore/retrystore.(*Datastore).Has.func1(0x42, 0xc426627ae0)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmeiCcJfDW1GJnWUArudsv5rQsihpi4oyddPhdqo3CfX6i/go-datastore/retrystore/retrystore.go:81 +0x4e
gx/ipfs/QmeiCcJfDW1GJnWUArudsv5rQsihpi4oyddPhdqo3CfX6i/go-datastore/retrystore.(*Datastore).runOp(0xc4205fce40, 0xc426627b28, 0xc42f0ea000, 0x42)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmeiCcJfDW1GJnWUArudsv5rQsihpi4oyddPhdqo3CfX6i/go-datastore/retrystore/retrystore.go:29 +0x2b
gx/ipfs/QmeiCcJfDW1GJnWUArudsv5rQsihpi4oyddPhdqo3CfX6i/go-datastore/retrystore.(*Datastore).Has(0xc4205fce40, 0xc42f0ea000, 0x42, 0xc42f0ea000, 0x42, 0x3b)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmeiCcJfDW1GJnWUArudsv5rQsihpi4oyddPhdqo3CfX6i/go-datastore/retrystore/retrystore.go:79 +0x83
gx/ipfs/QmeiCcJfDW1GJnWUArudsv5rQsihpi4oyddPhdqo3CfX6i/go-datastore/keytransform.(*ktds).Has(0xc420185320, 0xc42ebb00c0, 0x3b, 0x36, 0xc42ebb00c0, 0x3b)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmeiCcJfDW1GJnWUArudsv5rQsihpi4oyddPhdqo3CfX6i/go-datastore/keytransform/keytransform.go:48 +0x76
gx/ipfs/QmadMhXJLHMFjpRmh85XjpmVDkEtQpNYEZNRpWRvYVLrvb/go-ipfs-blockstore.(*blockstore).Has(0xc420185340, 0xc44f6401e0, 0xc42058f900, 0xc4309020c0, 0x24)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmadMhXJLHMFjpRmh85XjpmVDkEtQpNYEZNRpWRvYVLrvb/go-ipfs-blockstore/blockstore.go:183 +0x41
gx/ipfs/QmadMhXJLHMFjpRmh85XjpmVDkEtQpNYEZNRpWRvYVLrvb/go-ipfs-blockstore.(*arccache).Has(0xc42027a2c0, 0xc44f6401e0, 0x0, 0x0, 0x0)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmadMhXJLHMFjpRmh85XjpmVDkEtQpNYEZNRpWRvYVLrvb/go-ipfs-blockstore/arc_cache.go:76
+0x6c
gx/ipfs/QmadMhXJLHMFjpRmh85XjpmVDkEtQpNYEZNRpWRvYVLrvb/go-ipfs-blockstore.(*idstore).Has(0xc4202ea740, 0xc44f6401e0, 0x210, 0xc4345ea240, 0x0)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmadMhXJLHMFjpRmh85XjpmVDkEtQpNYEZNRpWRvYVLrvb/go-ipfs-blockstore/idstore.go:41 +0x6f
github.com/ipfs/go-ipfs/filestore.(*Filestore).Has(0xc420185580, 0xc44f6401e0, 0xf1de6f0578764212, 0xc426627d78, 0xc7ecb4)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/filestore/filestore.go:160 +0x42
github.com/ipfs/go-ipfs/blockservice.(*blockService).AddBlocks(0xc43b05c540, 0xc4345ea000, 0x21, 0x21, 0xc438548260, 0x21)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/blockservice/blockservice.go:171 +0x3f5
github.com/ipfs/go-ipfs/merkledag.(*dagService).AddMany(0xc427c795f0, 0x1586500, 0xc428b2e140, 0xc428708900, 0x21, 0x21, 0xc42ba5df98, 0xdbe386)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/merkledag/merkledag.go:60 +0x134
gx/ipfs/QmZtNq8dArGfnpCZfx2pUNY7UcjGhVp5qqwQ4hH6mpTMRQ/go-ipld-format.(*Batch).asyncCommit.func1(0x1586500, 0xc428b2e140, 0xc428708900, 0x21, 0x21, 0xc42a33e540, 0x158a060, 0xc427c795f0)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZtNq8dArGfnpCZfx2pUNY7UcjGhVp5qqwQ4hH6mpTMRQ/go-ipld-format/batch.go:96 +0x8a
created by gx/ipfs/QmZtNq8dArGfnpCZfx2pUNY7UcjGhVp5qqwQ4hH6mpTMRQ/go-ipld-format.(*Batch).asyncCommit
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZtNq8dArGfnpCZfx2pUNY7UcjGhVp5qqwQ4hH6mpTMRQ/go-ipld-format/batch.go:94 +0xbc
```

**Comment by hdriqi** [comment] 2018-10-15 13:43
I also got similar error. This happen when I add multiple big folders (about 10k files) at the same time.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xff7a48]

goroutine 31 [running]:
os.(*File).Name(...)
        /usr/lib/go/src/os/file.go:49
gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs.(*Datastore).writeDiskUsageFile.func1(0xc42067de0f, 0x0)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs/flatfs.go:875 +0x38
gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs.(*Datastore).writeDiskUsageFile(0xc420589260, 0x16668e9, 0x0)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs/flatfs.go:880 +0x152
gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs.(*Datastore).checkpointLoop(0xc420589260)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs/flatfs.go:863 +0x2da
created by gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs.Open
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qmc1ExJkrEUesbvRNHq6g3bJ2km7K4XffcC2bvwdpfGYDx/go-ds-flatfs/flatfs.go:261 +0x245
```

**Comment by Kubuxu** [comment] 2018-10-15 13:56
@hdriqi can you open separate issue?

**Comment by schomatis** [comment] 2018-10-15 17:59
Duplicate of https://github.com/ipfs/go-ipfs/issues/4820. Closing this one (feel free to re-open if you think this is a different problem).

**Closed by schomatis** 2018-10-15 17:59 UTC
Labels: badger
