### ISSUE TITLE
SIGINT during startup causes a panic

### ISSUE THREAD

**Issue by ribasushi** [ipfs/go-ipfs#8241] opened 2021-07-04 15:09 UTC
#### Version information:

```
go-ipfs version: 0.9.0-179d1d150
Repo version: 11
System version: amd64/linux
Golang version: go1.16.3
```
( built with `make nofuse` )
#### Description:
Below is a full copy of my terminal after:
- A startup
- A single CTRL+C after realizing I forgot to add something to the config

It took about 5 secs before the `panic` occured
```
~$ go-ipfs/cmd/ipfs/ipfs daemon --enable-gc=false 
Initializing daemon...
go-ipfs version: 0.9.0-179d1d150
Repo version: 11
System version: amd64/linux
Golang version: go1.16.3
^C
Swarm announcing /ip4/139.178.69.51/tcp/4001
panic: Process cannot add children after being closed

goroutine 1 [running]:
github.com/jbenet/goprocess.(*process).AddChild(0xc007dfcde0, 0x223d0f0, 0xc00846a720)
        /srv/nft/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:99 +0x2a5
main.daemonFunc(0xc000231ce0, 0x2228f68, 0xc00089d920, 0x1ce22c0, 0xc00089d8c0, 0x0, 0x0)
        /srv/nft/go-ipfs/cmd/ipfs/daemon.go:432 +0x932
github.com/ipfs/go-ipfs-cmds.(*executor).Execute(0xc000116960, 0xc000231ce0, 0x2228f68, 0xc00089d920, 0x1ce22c0, 0xc00089d8c0, 0xc00089d920, 0x0)
        /srv/nft/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.6.0/executor.go:77 +0x16b
github.com/ipfs/go-ipfs-cmds/cli.Run(0x2228b78, 0xc00071cd40, 0x2e31f60, 0xc00003c180, 0x3, 0x3, 0xc000010010, 0xc000010018, 0xc000010020, 0x2092d78, ...)
        /srv/nft/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.6.0/cli/run.go:137 +0xab8
main.mainRet(0x0)
        /srv/nft/go-ipfs/cmd/ipfs/main.go:168 +0x45e
main.main()
        /srv/nft/go-ipfs/cmd/ipfs/main.go:71 +0x25
```

**Comment by aschmahmann** [comment] 2021-07-04 18:06
seems to be a duplicate of #7027

**Closed by aschmahmann** 2021-07-04 18:06 UTC
Labels: kind/bug, need/triage

**Comment by ribasushi** [comment] 2021-07-04 19:59
It is, should have looked first 🤦
