### ISSUE TITLE
IPNS and DNSLink (IPNS bind DNS) so slow issue?

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#5995] opened 2019-02-14 17:53 UTC
IPNS and DNSLink (IPNS bind DNS) so slow issue

For sample contect, same peer node, 

1).  This original hash is quickly loaded.
https://ipfs.io/ipfs/QmcXbRoSrnmqwVFms3t9iX6DZMtKfUB9PJj6j8HQp59Ubj

2). But when ipfs name publish original hash to IPNS, get peer ID,  it is much slower, 1+ minute wait
https://ipfs.io/ipns/QmbX1mn42J9Fh7ascyaX2txtqRxRNFg3NWMXFr8k6HqKBj 

3). Worse, when bind IPNS peer ID to domain DNS, with DNSlinks=/ipns/....
2+ minutes waiting to load
https://ipfs.io/ipns/pdfbay.org

Please try above link and advise why? How to improve the loading speed. 
Specially when it is too slow, bad user experience, make it un-usable.

**Comment by Stebalien** [comment] 2019-02-14 18:01
Duplicate of https://github.com/ipfs/go-ipfs/issues/3860. We're working on it but it's going to be a while.

**Closed by Stebalien** 2019-02-14 18:01 UTC
