### ISSUE TITLE
filestore - unable to add files on different HDD

### ISSUE THREAD

**Issue by FredericaBernkastel** [ipfs/go-ipfs#6092] opened 2019-03-17 15:44 UTC
```
go-ipfs version: 0.4.19-
Repo version: 7
System version: amd64/windows
Golang version: go1.11.5
```
**`ipfs add --nocopy "D:\file"`** 

will fail with message "**cannot add filestore references outside ipfs root**". 
ipfs_path is "**C:\Users\user\\.ipfs**"

ref: https://github.com/ipfs/go-ipfs/blob/221d1b13ab9ad982dedcc55f9f948d4e920c435d/filestore/fsrefstore.go#L284-L286

**Comment by Stebalien** [comment] 2019-03-18 16:14
Duplicate of https://github.com/ipfs/go-ipfs/issues/4224. We're considering lifting these constraints.

**Closed by Stebalien** 2019-03-18 16:15 UTC

**Comment by CsterKuroi** [comment] 2020-04-14 06:51
lifti these constraints~
