### ISSUE TITLE
"merkledag: not found" error could be more informative

### ISSUE THREAD

**Issue by Fil** [ipfs/go-ipfs#2009] opened 2015-11-26 22:57 UTC
I forgot to launch the daemon a machine B, and added a file on machine A.

On machine B when I tried to ipfs cat [dag] the error message I got was `merkledag: not found`; it could be more informative (at least: "check that your local daemon is running")

**Comment by rht** [comment] 2015-11-29 02:30
Running the daemon doesn't guarantee you will get the file from machine A. If daemon B is up but with 0 peers (as in not connected to the network), you'd still get the same err message.

**Comment by jbenet** [comment] 2015-12-01 16:03
yeah probably should make the errors more informative

**Comment by RichardLitt** [comment] 2016-02-26 20:08
They should also conform. For instance:

```
> ipfs bitswap wantlist
Error: api not running
```

This should have the same error message as `ipfs get` and `ipfs cat`, which both return `Error: merkledag: not found`.

**Comment by karlek** [comment] 2016-08-05 01:05
How about if the daemon isn't running locally the `ipfs cat` command could return a helpful reminder to start the daemon. 

> "[...] Please make sure that the daemon is running. The daemon can be started with `ipfs daemon`."

**Comment by whyrusleeping** [comment] 2016-08-05 10:00
These are different issues. Running ipfs commands without a daemon is a perfectly valid usecase. In those instances, trying to access an object you don't have in your local repo should correctly respond with "not found". 

@RichardLitt `ipfs bitswap wantlist` and `ipfs get/cat` are two very different types of commands. It doesnt make sense for them to have the same output.

@karlek imagine the scenario where you are working with ipfs offline on purpose, The error message you propose wouldn't really fit.

**Comment by hsanjuan** [comment] 2017-03-23 13:11
`merkledag: not found` message is very cryptic to everyone that encounters it the first time. I think the error should hint that the daemon is not running, or at the very least `cid not found locally`.

**Comment by lidel** [comment] 2018-10-31 15:21
cc https://github.com/ipfs/go-ipfs/issues/4416 &  PR  https://github.com/ipfs/go-ipfs/pull/4099

**Comment by robert-e-davidson3** [comment] 2020-06-15 23:45
Throwing in my voice: the only reason I found out what this error means is I googled it and got this ticket.

**Comment by lidel** [comment] 2021-01-07 15:02
Bumping this + cc @jessicaschilling for sanity check how to improve `merkledag: not found`

Some ideas:

- `requested CID/DAG was not found in the local repo (offline mode)`

**Comment by jessicaschilling** [comment] 2021-01-07 15:27
@lidel `requested CID/DAG not found locally (are you in offline mode?)`
?
Or just `(offline mode)` if that's confirmed to always be the case. Wasn't totally clear about this from the comment chain above.

**Comment by lidel** [comment] 2021-01-07 22:46
AFAIK there are at least two distinct "offline" states that produce `merkledag: not found`:

1. _intentional_: block not found in local repo, and won't look online because explicit `--offline` was passed to a command or `daemon --offline` is set globally.
2. **_accidental_**: block not found in local repo, and failed to ask the network because daemon is not running (or has no peers), AND  **user forgot or is not aware that the daemon needs to be running to resolve foreign CID**.

:point_right: To be specific, I want to **decrease the time wasted by our users on debugging scenario in bold**. I know it sounds like a small thing, but imagine learning about IPFS and then wasting hour(s) trying to debug `merkledag: not found` only to realize you forgot to start `ipfs daemon` or something equally trivial 🤬  

Paper cuts like this kill joy and initial enthusiasm for the project.
Even if we just change the error text, it will be a huge improvement.

Did some spelunking and:

- Found prior art by @ribasushi: [custom errors in `ipfs dag export`](https://github.com/ipfs/go-ipfs/blob/2ed9254426e900cf00a9b35304dc5b5de8173208/core/commands/dag/dag.go#L607-L616) that is addressing my concern and provides useful hint to the user.  At the very minimum we need something like that for at least `ipfs cat/get`
- @Stebalien @hsanjuan started related refactors in:
  - Better error messages tracked in https://github.com/ipfs/go-ipfs/issues/4416#issuecomment-592647097
  - Tracking: Improving ErrNotFound https://github.com/ipfs/go-ipfs/issues/7074#issuecomment-610654770
  - .. but it seems to be put on hold since ~0.5.0.  

@aschmahmann @hsanjuan will the refactor be picked up anytime soon? If not I'd like to PR a fix for `cat/get` commands similar to what @ribasushi  did in `ipfs dag export` + unify user-friendly errors across all commands.

**Comment by hsanjuan** [comment] 2021-01-12 12:55
> will the refactor be picked up anytime soon?

Not from my side. One thing block other thing and here we are (we never moved to raw-multihashes). :-( Per https://github.com/ipfs/go-ipfs/issues/7074#issuecomment-610654770 it may not be too difficult to move forward with the agreed solution though.

**Comment by Stebalien** [comment] 2021-03-31 21:02
Closing in favor of the tracking issue.

**Closed** 2021-03-31 21:02 UTC
Labels: topic/api, topic/commands, topic/docs-ipfs
