### ISSUE TITLE
"ERROR metrics-pr: Registering prometheus collector" when using --only-hash=true

### ISSUE THREAD

**Issue by haggins** [ipfs/go-ipfs#5413] opened 2018-08-31 13:50 UTC
#### Version information:
go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/linux
Golang version: go1.10.3

#### Type:
Bug

#### Description:
When you add a file with the `--only-hash=true` option, you get the following two errors at the IPFS daemon terminal (independent from your daemon being `--offline` or not):
```
~ $ ipfs add --only-hash=true test.txt 
added QmaQTyGfeKN5Hnp1mmRVTjHpxhvoWHoLQ4Nb1jNoEqFkQJ test.txt
```
```
~ $ ipfs daemon --offline
Initializing daemon...
Successfully raised file descriptor limit to 2048.
Swarm not listening, running in offline mode.
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8079
Daemon is ready
15:44:38.862 ERROR metrics-pr: Registering prometheus collector, name: ipfs_bs_cache_arc_hits_total, error: duplicate metrics collector registration attempted
 binding.go:74
15:44:38.862 ERROR metrics-pr: Registering prometheus collector, name: ipfs_bs_cache_arc_total, error: duplicate metrics collector registration attempted
 binding.go:74
```
**The error doesn't appear if you omit the `--only-hash=true` option or set it to false.**

**Comment by Stebalien** [comment] 2018-08-31 16:37
Thanks for reporting! This is a duplicate of https://github.com/ipfs/go-ipfs/issues/3913.

**Closed by Stebalien** 2018-08-31 16:37 UTC
