### ISSUE TITLE
Returning same hash for different file objects

### ISSUE THREAD

**Issue by svanschalkwyk** [ipfs/go-ipfs#5105] opened 2018-06-11 22:51 UTC
Same hash being returned for all folders (...3Nn) and all files (...wQH):

Event File/Folder Name: untitled folder 10
Directory QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn

Event File/Folder Name: untitled folder 11
Directory QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn

Using Docker (latest), code (latest), go 10.2.

**Comment by Stebalien** [comment] 2018-06-11 23:04
Are they empty? Those are the hashes of the empty folder and empty file.

**Comment by svanschalkwyk** [comment] 2018-06-11 23:40
Yes. Empty dirs.
I create the dirs and commit them to IPFS.
Then add files as they are required.

**Comment by ivan386** [comment] 2018-06-12 05:28
They hashed by content at the moment. Names can be saved only in underline dir. `Ipfs add -w` wrap added content in dir.

If you want share dir with files then add files as they are required and then commit dir to ipfs.

**Comment by svanschalkwyk** [comment] 2018-06-12 15:45
I misunderstood the innards of IPFS then. Will have to go to GCP and AWS if I want a unique hash (S3 for example)? 
I tried inserting a text file into the empty folders, but folders have to be updatable on the fly (i.e. while in IPFS). 
Alternatively, what can I add (in golang) that will allow the directory/filename to be added to the hash? In my case I use the path name as a somewhat unique identifier.

**Comment by Stebalien** [comment] 2018-06-12 19:40
IPFS is an immutable, content-addressable filesystem. There's really no point in assigning "unique" IDs. If two objects have the same hash, they *are* the same object.

If you're looking for mutable objects with unique IDs, you'll need to use something like IPNS for that. IPNS will allow you to create unique and updatable files/directories. However, IPNS has some performance issues at the moment.

---

As we've determined that this is not a bug, I'm going to close it in favor of continuing the discussion on https://discuss.ipfs.io.

**Closed by Stebalien** 2018-06-12 19:40 UTC
Labels: question

**Comment by svanschalkwyk** [comment] 2018-06-12 21:01
Thank you.
Seen from that perspective, it makes sense.
I'll change the order in which my code runs to fit that. The
misunderstansing resulted from my thinking in terms of a mutable FS.
