### ISSUE TITLE
ipfs add got stuck after running garbage collector

### ISSUE THREAD

**Issue by girish979** [ipfs/go-ipfs#5973] opened 2019-02-06 21:30 UTC
#### Version information:
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1

#### Severity: Medium (?)

##Repo stats
**NumObjects: 190350
RepoSize:   27361171018
StorageMax: 3000000000000
RepoPath:   /home/Storage/ipfs
Version:    fs-repo@7
**

#### Pin count
ipfs pin ls |  wc -l
108206

#### Description:

I did `ipfs --debug=true pin add QmV3YAoK8KbemebgoszHqKSsfYPxy5KK23VJF4XNrRyivx --progress`
and this got stuck forever.

info as per https://github.com/ipfs/go-ipfs/blob/master/docs/debug-guide.md#beginning
[info.gz](https://github.com/ipfs/go-ipfs/files/2838384/info.gz)

**Comment by Stebalien** [comment] 2019-02-06 23:29
What's the output of `ipfs bitswap wantlist`?

**Comment by leerspace** [comment] 2019-02-08 00:56
What is QmV3YAoK8KbemebgoszHqKSsfYPxy5KK23VJF4XNrRyivx supposed to be a hash for? I can't find any providers for it, so that might be one reason it never completes.

What happens if you use a more widely available hash? For example, QmSSqP1MCyRcxR2Xf5bcTEGnhpTzy9j9MgurgyZHbr5XPN.

**Comment by girish979** [comment] 2019-02-08 16:26
> ipfs bitswap wantlist

I restarted the IPFS to fix issue, will post the output when the issue is observed again.




> What is QmV3YAoK8KbemebgoszHqKSsfYPxy5KK23VJF4XNrRyivx supposed to be a hash for? I can't find any providers for it, so that might be one reason it never completes.
> 
> What happens if you use a more widely available hash? For example, QmSSqP1MCyRcxR2Xf5bcTEGnhpTzy9j9MgurgyZHbr5XPN.

It is just a hash for some small content. I am running IPFS locally and it is not connected to other nodes.

Is the pin count related to the garbage collector performance / run time, each time the garbage collector is run?

**Comment by Stebalien** [comment] 2019-02-13 01:01
@girish979 I asked about the wantlist because your IPFS node probably couldn't find the content. That's usually why pinning/fetching gets stuck.

**Comment by michaelavila** [comment] 2019-06-05 20:29
Tagging with `icebox` until we are able to reproduce or start to see other instances

**Comment by Stebalien** [comment] 2019-06-05 22:55
(I'm actually just going to close this per https://github.com/ipfs/go-ipfs/issues/5973#issuecomment-463009954)

**Closed by Stebalien** 2019-06-05 22:55 UTC
Labels: bug, icebox
