### ISSUE TITLE
What is the reason for very slow

### ISSUE THREAD

**Issue by voxsoftware** [ipfs/go-ipfs#6382] opened 2019-05-28 02:01 UTC
#### Version information:
go-ipfs 0.4.20

 * I go to a machine with go-ipfs 0.4.20 and execute ``` ipfs add xxxxx``` (a file with 20MB), i got the *hash*
 * I go to another machine, use the HTTP gateway with the hash, the request hangs, more than 36 minutes without still can access to uploaded file

What is the reason for this?

**Comment by voxsoftware** [comment] 2019-05-28 02:53
I tested the same happens with orbit-db if I try initiate database on nodejs app (using http client) hangs, but in browser not. What is the reason of this really really slow ?

**Comment by jasonzhouu** [comment] 2019-05-28 06:55
https://github.com/ipfs/go-ipfs/issues/5226#issuecomment-408614576

**Comment by voxsoftware** [comment] 2019-05-28 07:05
Just now 5 hours later, still cannot access to hash from other machine

**Comment by Stebalien** [comment] 2019-05-28 07:08
@jasonzhouu that's a different issue. The issue _here_ is about finding content. The issue _there_ is about receiving the same block multiple times. While that's _still_ an issue, it no longer scales linearly with the number of peers that _have_ the block.

---

@voxsoftware 

The gateway may not be able to reach your node. However, the issue is likely content routing (i.e., using the DHT to find who has the content). Unfortunately, this is currently _really_ slow as the DHT is full of unreachable peers behind NATs.

See: https://github.com/libp2p/go-libp2p-kad-dht/issues/216

**Comment by Stebalien** [comment] 2019-05-28 07:10
Closing as this isn't directly actionable. Feel free to continue asking followup questions.

**Closed by Stebalien** 2019-05-28 07:10 UTC
Labels: bug, duplicate, perf

**Comment by jasonzhouu** [comment] 2019-05-28 07:17
There are 2 kinds of test in https://github.com/ipfs/go-ipfs/issues/5226#issuecomment-408614576 :
- latency test
- duplicate blocks test

**Comment by voxsoftware** [comment] 2019-05-28 07:30
@Stebalien my node is online. I tested with other files, on node and works some times. But other times like this, hangs for many many time. Really the problem is not related to node because is my own node, in a machine with 0 latency from the other machine where I am testing get the hash. 

So, if you close the node, you only are ignoring a big issue

**Comment by voxsoftware** [comment] 2019-05-28 07:33
@jasonzhouu latency more than one hour?

**Comment by voxsoftware** [comment] 2019-05-28 07:34
I consider acceptable 5 minutes, but more than 20 minutes, is unusable. If I need have some requirenments on nodes where I uploaded please say me, because I cannot believe that this happens

**Comment by voxsoftware** [comment] 2019-05-28 07:37
Another aclaration, for this tests, I am using *vps*  on dedicated servers, with 100% internet all time and without firewalls, and really I don't understand, what is happening

**Comment by jasonzhouu** [comment] 2019-05-28 07:38
> @jasonzhouu latency more than one hour?

yes

**Comment by Stebalien** [comment] 2019-05-28 08:03
@jasonzhouu IIRC, those tests are all about duplicate blocks in a closed test network. I can't find anything on that thread about finding content, latency, etc.

> So, if you close this issue, you are ignoring a big issue

I'm sorry, I realize I wasn't clear on this. This issue is very much valid and we're working on it as fast as we can.

I closed this report simply for tracking purposes. This isn't something that can simply be fixed or implemented and leaving a bunch of vague "ipfs is slow" issues open just clutters the issue tracker. Worse, these issues tend to turn into a mess of multiple issues as other users jump in and start reporting unrelated performance issues.

However, looking through the issue tracker, I can't find a decent meta-issue for this. I'm going to create one now.

**Comment by jasonzhouu** [comment] 2019-05-28 08:17
@Stebalien 
![](https://user-images.githubusercontent.com/32749078/43357895-d91e0074-9280-11e8-89ae-3381a7472176.png)

**Comment by Stebalien** [comment] 2019-05-28 08:36
@jasonzhouu The comment associated with that graph is:

> IPFS performance deteriorates as the number of nodes increases. This is due to the increasing number of duplicate blocks. This is happenning due to the current Bitswap implementation.

_That_ issue has been (mostly) fixed. At the time, go-ipfs was asking every connected peer for every block of data instead of asking different peers for different blocks. If 10 peers had a single block, go-ipfs would fetch the block from all 10 peers and take 10x longer to do so as it was downloading 10x the amount of data.

The _delay_ there is the delay in fetching the entire file.

---

@voxsoftware I've filed a meta issue (https://github.com/ipfs/go-ipfs/issues/6383) to try to explain what's going on here and why.

**Comment by voxsoftware** [comment] 2019-05-28 21:49
If this is relevant, i want say that just now I tested, and I can access to file, almost one day later.

**Comment by Stebalien** [comment] 2019-05-28 23:23
> If this is relevant, i want say that just now I tested, and I can access to file from my other node, almost one day later.

I've heard this before and that is kind of odd. I wonder if the initial attempt to tell the network you have the content failed but a subsequent request succeeded.

**Comment by bronger** [comment] 2022-07-11 18:33
I’m currently observing a similar effect. I add a large directory (2.5 GB) with `ipfs add --nocopy -r -w …`, and an `ipfs get` on my other machine hangs.  Hours later, it still does, even after restarts. The funny thing is that I then added a 20-character test file on the first side, and _this_ is directly accessible from the second. And then – magic – also the big directory is accessible. I am currently trying to reproduce, but is it realistic to assume a coincidence here?

The test file was added without `--nocopy` FWIW.
