### ISSUE TITLE
 go-ipfs should be able to mount `/ipfs` separately from `/ipns`.

### ISSUE THREAD

**Issue by vi** [ipfs/go-ipfs#3563] opened 2017-01-05 02:09 UTC
#### Version information:

go-ipfs version: 0.4.4-
Repo version: 4
System version: amd64/linux
Golang version: go1.7

#### Priority:

P2 or P3

#### Description:

IPNS seems to be [more][1] [problematic][2] compared to basic IPFS layer. It requires connection to internet, it expires. IPFS may be used without IPNS.

Yet there is no option to mount only `/ipfs`, without `/ipns`.

First attempt:

```
  "Mounts": {
    "IPFS": "/home/vi/home/ipfs/ipfs",
    "IPNS__commented_out": "/home/vi/home/ipfs/ipns",
    "FuseAllowOther": true
  },
```

Result:

`Error: Could not resolve name.` despite of I assumed that moving away "IPNS" mount parameter should disable that mout.

Second attempt: `ipfs mount`

`~/ipfs` becomes available for a moment (while it is trying to resolve node's name). Then it quits with `Error: Could not resolve name.` and `~/ipfs` becomes unmounted again.

Expected something like `ipfs mount --disable-ipns` or `"Mounts": { "DisableIPNS": true }`.

Ideally I should also be option to do further independent `ipfs mount --only-ipns` to deliver optional `/ipns` part later.

`/ipfs`, unlike `/ipns` may be used by something serious, be available at boot time (before network configured).

[1]:https://github.com/ipfs/go-ipfs/issues/2383
[2]:https://github.com/ipfs/go-ipfs/issues/2178

**Comment by eminence** [comment] 2017-01-05 02:11
CC #2167

**Comment by whyrusleeping** [comment] 2017-01-05 12:04
Definitely agreed, lets do this. It should be configurable through the CLI and we should be able to have a config setting for it.

**Comment by Mikaela** [comment] 2019-03-26 15:19
Is this a duplicate of https://github.com/ipfs/go-ipfs/issues/2187?

**Comment by Stebalien** [comment] 2019-03-26 17:45
Yes. Thanks!

**Closed by Stebalien** 2019-03-26 17:45 UTC
Labels: commands, enhancement, fuse, help wanted
