### ISSUE TITLE
Error: unable to open leveldb datastore

### ISSUE THREAD

**Issue by Mithgol** [ipfs/go-ipfs#1974] opened 2015-11-17 17:06 UTC
In the morning my computer “froze” (became unresponsive) and I had to reset it; the reason behind it was, I suppose, not related to go-ipfs.

After the reboot I tried to run IPFS and got the following message:

`Error: failed to create lock file` _(lock path here)_ `open` _(lock path here)_ `: The file exists.`

This is natural after an unexpected reboot.

I have deleted the lock file using the given path and then attempted to restart IPFS. I've got the following message:

**`Error: unable to open leveldb datastore`**

There's literally nothing I could do about it, and thus I eventually resorted to `ipfs init -f` and lost my pinned media, an associated IPNS name, etc.

Consider choosing some other key+value storage that survives an unexpected reboot better than LevelDB.

For example, SQLite implements serializable transactions that are atomic, consistent, isolated, and durable, [even if the transaction is interrupted by a program crash, an operating system crash, or a power failure to the computer.](http://sqlite.org/transactional.html) SQLite also has [an extension](https://www.sqlite.org/json1.html) useful for managing JSON content stored in an SQLite database.

**Comment by whyrusleeping** [comment] 2015-11-17 17:39
so you deleted `$IPFS_PATH/datastore/LOCK` ? or which lock file did you delete?

**Comment by Mithgol** [comment] 2015-11-17 19:27
`$IPFS_PATH/repo.lock`

**Comment by jbenet** [comment] 2015-11-17 19:37
I'm surprised that leveldb _isn't_ durable. yeah leveldb likely has a lock too.

@Mithgol in the future ask before deleting-- you can recover all (or most) of the data from the repo. It's a pretty basic format. even the leveldb stuff can be recovered with a bit of work. Also, once 0.4.0 lands, pinsets will just be ipfs objects, and out of leveldb.

**Comment by whyrusleeping** [comment] 2015-11-17 19:41
@Mithgol yeah, the file you needed to delete was `$IPFS_PATH/datastore/LOCK` leveldb is fairly durable, and as you mention, issues like this are expected for hard reset.

**Comment by jbenet** [comment] 2015-11-17 19:44
@whyrusleeping maybe worth making `ipfs repo recover` or something that checks it for integrity and removes lock files.

**Comment by jbenet** [comment] 2015-11-17 19:44
and the errors could advise users to try this. the UX otherwise is horrible.

**Comment by whyrusleeping** [comment] 2015-11-17 19:50
thats a good idea.

**Comment by rht** [comment] 2015-11-17 23:08
git has https://git-scm.com/docs/git-fsck to complement for its occasional lack of fsync.

**Comment by Mithgol** [comment] 2015-11-18 10:31
Actually I remember that I also deleted `$IPFS_PATH/datastore/LOCK` later, and thus my actions were like the following:

* reboot (reset)

* `ipfs daemon`

* `Error: failed to create lock file` *($IPFS_PATH/repo.lock)* `open` *($IPFS_PATH/repo.lock)* `: The file exists.`

* deleted `$IPFS_PATH/repo.lock`

* `ipfs daemon`

* `Error: unable to open leveldb datastore`

* deleted `$IPFS_PATH/datastore/LOCK`

* `ipfs daemon`

* still `Error: unable to open leveldb datastore`

Though I might have misremembered (or mistyped) and deleted `$IPFS_PATH/datastore/LOG` instead of `$IPFS_PATH/datastore/LOCK` because they're somewhat similar. But I don't really think so.

**Comment by iav** [comment] 2016-04-03 14:46
So, now I have the same as topicstarter.
ipfs version 0.3.11
Running  on Raspberry Pi 1GB ram, raspbian.
Funny:
```
 $ ipfs diag sys
Error: api not running
```
How can I recover without lost of my pins?

**Comment by lgierth** [comment] 2016-04-03 21:46
@lav this happens if you double-ctrl-c or kill the daemon -- it'll leave behind the `~/.ipfs/api` file, you can simply delete that one and it'll continue to work.

**Comment by iav** [comment] 2016-04-03 23:35
ok, now I delete  `~/.ipfs/api` and run
```
 $ ipfs daemon
Initializing daemon...
Error: unable to open leveldb datastore
```
Then I remove `LOCK` file in `~/.ipfs/datastore`. Nothing changed.
What's next?

**Comment by whyrusleeping** [comment] 2016-08-23 21:02
I believe that this is fixed with `ipfs repo fsck`. If someone can verify thats the case that would be very helpful

**Comment by antilibrary** [comment] 2017-08-06 12:24
I'm getting this same error when I try to run the ipfs docker container on a windows 10 machine (docker Version 17.06.0-ce-win19 (12801)):

```
docker run --name ipfs -v "C:/Users/user/Documents/ipfs":/data/ipfs -d ipfs/go-ipfs daemon --enable-pubsub-experiment
```

This will result in:

```
ipfs version 0.4.10
initializing IPFS node at /data/ipfs
generating 2048-bit RSA keypair...done
peer identity: Qmbfue3xrG8JUF7yUaCAX5cS8tbuFnGQggYbhJJDWS45uK
Error: unable to open leveldb datastore: sync /data/ipfs/datastore: invalid argument
```

**Comment by Mithgol** [comment] 2017-08-06 22:55
@antilibrary Can you try the aforementioned `ipfs repo fsck`?

**Comment by magik6k** [comment] 2017-08-06 23:30
@antilibrary It doesn't look related and it's most likely caused by how docker handles volume mounting on windows.

**Closed** 2021-03-22 16:04 UTC
Labels: need/verification
