### ISSUE TITLE
Store keys outside of config

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#783] opened 2015-02-15 01:13 UTC

**Comment by diasdavid** [comment] 2016-01-02 01:50
IPFS Repo Spec was updated to include a 'Keys' repo

https://github.com/ipfs/specs/pull/43

**Comment by eingenito** [comment] 2019-05-16 20:23
Closing as duplicate of #6262 which has more context.

**Closed by eingenito** 2019-05-16 20:23 UTC
Labels: difficulty:easy, help wanted, repo
