### ISSUE TITLE
ipfs get - The system cannot find the path specified

### ISSUE THREAD

**Issue by leerspace** [ipfs/go-ipfs#3660] opened 2017-02-07 03:19 UTC
#### Version information:
```
go-ipfs version: 0.4.5-rc1-
Repo version: 5
System version: amd64/windows
Golang version: go1.7.4
```

#### Description:

On both 0.4.4 and 0.4.5 rc2 (not sure if rc1 or 2 since `version` shows 1 but I downloaded the rc2 binary) I get an error when trying to do `ipfs get /ipfs/QmPVP4sDre9rtYahGvcjv3Fqet3oQyqrH5xS33d4YBVFme`. This is the XKCD archive from archives.ipfs.io.

For what it's worth I also have issues with doing an IPFS get on this hash on linux, but rather than an error it just hangs so once I can get more information on that one I'll create a separate issue.

Command output:
```
D:\Downloads\go-ipfs_v0.4.5-rc2_windows-amd64\go-ipfs>ipfs.exe get /ipfs/QmPVP4sDre9rtYahGvcjv3Fqet3oQyqrH5xS33d4YBVFme
Saving file(s) to QmPVP4sDre9rtYahGvcjv3Fqet3oQyqrH5xS33d4YBVFme
 2.34 MB / 92.69 MB [==>-----------------------------------------------------------------------------------]   2.53% 0s
Error: open QmPVP4sDre9rtYahGvcjv3Fqet3oQyqrH5xS33d4YBVFme\1031 - s keyboard leopard \1031 - s keyboard leopard  - alt.txt: The system cannot find the path specified.
```

IPFS daemon output (from multiple attempts):
```
Daemon is ready
[0;37m21:07:47.751 [31mERROR [0;34mcommands/h: [0merr: context canceled [0;37mhandler.go:288[0m
[0;37m21:08:56.855 [31mERROR [0;34mcommands/h: [0merr: context canceled [0;37mhandler.go:288[0m
[0;37m21:09:06.703 [31mERROR [0;34mcommands/h: [0merr: context canceled [0;37mhandler.go:288[0m
[0;37m21:10:22.216 [31mERROR [0;34mcommands/h: [0merr: context canceled [0;37mhandler.go:288[0m
```

**Comment by Kubuxu** [comment] 2017-02-07 09:56
My two guesses: On Windows the path is too long or contains illegal characters. On Linux, everything works fine, but people that were hosting the archive are not longer hosting it in full and there are just fragments scattered around.

**Comment by leerspace** [comment] 2017-02-07 13:56
I think I see the invalid character on windows: a trailing space in the directory name. Whether ipfs on Windows should do anything to handle that, I'm not sure. If this is desired and expected behavior for go-ipfs on Windows, then this issue is probably good to close.

On the side note of linux, given that the gateway seems to load the hash (https://ipfs.io/ipfs/QmPVP4sDre9rtYahGvcjv3Fqet3oQyqrH5xS33d4YBVFme) just fine, I would assume (maybe wrongly) that I should also be able to access it doing an `ipfs get`. Doing a `wget -r https://ipfs.io/ipfs/QmPVP4sDre9rtYahGvcjv3Fqet3oQyqrH5xS33d4YBVFme` on linux does give me a couple of 302, 400, and 500 errors, so it looks like there is at least one inaccessible file with the about file being one of them. I had been working on the assumption that the hashes on archives.ipfs.io would be some of the best "seeded" hashes to test with, but this seems to be yet another bad assumption on my part.

**Comment by whyrusleeping** [comment] 2017-02-10 19:56
> I had been working on the assumption that the hashes on archives.ipfs.io would be some of the best "seeded" hashes to test with

This should be an absolutely correct assumption to make, If its not the case then we really need to figure out what the issue is. @lgierth Can you investigate?

**Comment by Kubuxu** [comment] 2017-02-13 01:30
The hash  was updated in archives repo to be one that is seeded by among others, us. I am closing this, we can open a separate issue for what to do when Windows refuses to cooperate, probably we should investigate what Git does in this case.

**Closed by Kubuxu** 2017-02-13 01:30 UTC

**Comment by djdv** [comment] 2017-02-13 04:51
These might be relevant
https://github.com/ipfs/go-ipfs/issues/1710
https://github.com/ipfs/go-ipfs/issues/2013
