### ISSUE TITLE
Node stuck on 200% CPU

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2730] opened 2016-05-18 10:22 UTC
Version: 0.4.2
Node didin't respond to debug API endpoints so I don't have any debugging information.

Happened when I tried to download go-ipfs-0.4.2 from /ipns/dist.ipfs.io

**Comment by pfraze** [comment] 2016-06-27 14:11
I experience this when IPFS has been running, and I sleep my machine. When I turn the laptop back on, the IPFS node is pegged at over 200%, and stays that way.

![screen shot 2016-06-25 at 9 18 30 am](https://cloud.githubusercontent.com/assets/1270099/16382556/e3b6ce72-3c46-11e6-83b7-ccc7b6c0dd35.png)

MacOS 10.11.4

**Comment by therealplato** [comment] 2016-06-27 15:55
any chance this is related to [similar docker issues](https://forums.docker.com/search?q=200%25)

**Comment by pfraze** [comment] 2016-06-27 16:00
The description is similar, but there's nothing in there that explains it,
and I'm not using docker

**Comment by whyrusleeping** [comment] 2016-08-19 16:17
I believe this has been resolved in 0.4.3, i'm pretty sure it was the utp issue

**Comment by pfrazee** [comment] 2016-08-21 01:37
@whyrusleeping what's the release timeline for 0.4.3?

**Comment by whyrusleeping** [comment] 2016-08-21 02:22
@pfraze quite soon. We're investigating one final potential issue and
@jbenet is going to review a few things. Hopefully by the end of the week.

**Comment by whyrusleeping** [comment] 2016-08-23 20:33
going to close this now, we have release candidate builds up and we're unable to reproduce the problem using them

**Closed by whyrusleeping** 2016-08-23 20:33 UTC
Labels: bug
