### ISSUE TITLE
Unable to write /ipns mount on a peer

### ISSUE THREAD

**Issue by kvm2116** [ipfs/go-ipfs#5259] opened 2018-07-18 17:03 UTC
#### Version information:

go-ipfs version: 0.4.16-rc2-8a9aa41
Repo version: 7
System version: amd64/linux
Golang version: go1.10.3

#### Description:

IPFS node seems to be unable to edit a peer's /ipns mount. Example given below:

There are 2 machines, A and B. Both have /ipns mounted. Machine A has a directory in the /ipns mount (/ipns/local/sample_A) with a file A1.txt (/ipns/local/sample_A/A1.txt).
 Machine B needs the file A1.txt (to be edited) as well as add another file A2.txt. When I try to add A2.txt on Machine B as /ipns/peer_id/sample_A/A2.txt, it gives an error "Permission denied".

**Comment by Stebalien** [comment] 2018-07-18 21:20
Basically, you can't do that. Every node "owns" its own IPNS key/directory. However, peer B can copy the files out of `/ipns/peer_a/` into `/ipns/local` and edit them there. Note: "copying" won't actually duplicate the data because it's all content addressed.

**Comment by Stebalien** [comment] 2018-07-18 21:20
Closing as it works as intended. Feel free to ask for clarification.

**Closed by Stebalien** 2018-07-18 21:20 UTC

**Comment by Stebalien** [comment] 2018-07-18 22:42
>  What do you mean by "copying"? Does it mean that /ipns/local on peer B will show that the file exists, but the file is really just a pointer to the file blocks in the blockstore?

Effectively, yes. Although, if you use the standard posix utilities, it'll still copy (and then likely dedup) unfortunately. Ideally, we'd "mount" `/ipns/local` inside of MFS (see `ipfs files`) so one could use IPFS commands to mess with the files but we don't do that yet and probably won't get around to implementing it for a while.

>  To create the copy in peer B /ipns/local, I assume the code will need to be changed? Specifically, the Lookup function?

A the moment, a simple `cp /ipns/peer_a/* /ipns/local` will copy everything from peer A. In most cases, the resulting files/directories will be identical so when we re-import the data to IPFS, it should dedup everything.

>  Is it possible to edit the file before the entire file is copied over to peer B?

Not that I know of. However, you can always copy and then edit (or copy to your local machine, edit, and then copy into `/ipfs/local`).

---

Note: A shared filesystem is a project we want to do eventually but doing it correctly requires ACLs, at the very minimum.

**Comment by kvm2116** [comment] 2018-07-21 15:35
Instead of copying the entire file to peer B, is it possible to create a dummy file on peer B (/ipns/peer_b/dummy) and assign it the hash value of the original file on peer A?

**Comment by Stebalien** [comment] 2018-07-21 15:43
Yes but it's a bit messy. You can:

1. Get the current hash of `/ipns/local`.
2. Add that to MFS (`ipfs files cp /ipfs/HASH /ipns_local`).
3. "Copy" the file to `/ipns_local` (`ipfs files cp "$(ipfs /ipns/peer_b/file_name)" /ipns_local/file_name`).
3. Update your local IPNS pointer to point to the new directory (`ipfs name publish "/ipfs/$(ipfs files stat --hash /ipns_local/file_name)"`).

In this case, the "copy" commands actually just link, they don't copy.

**Comment by kvm2116** [comment] 2018-07-21 16:29
Thanks!
 I am a bit confused on which steps to perform on which peer.
Let's assume the file is on peer A (/ipns/peer_a/fileA), which needs to be accessed from B. And the dummy file on B (/ipns/peer_b/fileB) points to the fileA.

Step 1. Current hash of /ipns/local of peer A, right?
Is step 2 and 3 expected to be run on peer A. And the final step on peer B? Or all final 3 steps on peer B?

**Comment by Stebalien** [comment] 2018-07-21 17:00
In my instructions, the file is on peer B and all of the steps should be run on peer A.

**Comment by kvm2116** [comment] 2018-07-21 18:53
Ah I see. Thank you.

First 3 steps worked perfectly. Last step gave an Error: cannot manually publish while IPNS is mounted.

**Comment by Stebalien** [comment] 2018-07-23 05:55
Damn. It doesn't look like that's possible at the moment. For now, the only solution is to unmount, update, and remount. That kind of sucks...

**Comment by pyhedgehog** [comment] 2024-08-13 18:09
> 4\. Update your local IPNS pointer to point to the new directory (`ipfs name publish "/ipfs/$(ipfs files stat --hash /ipns_local/file_name)"`).

Here we returning to initial question:
```
# ipfs name publish "/ipfs/$(ipfs files stat --hash /ipns_local)"
Error: cannot manually publish while IPNS is mounted
# ln -s -f "/ipfs/$(ipfs files stat --hash /ipns_local)" "$(readlink -f /ipns/local)"
ln: failed to create symbolic link '/ipns/<my-device-id>/<directory-cid>': Input/output error
# cp -f "/ipfs/$(ipfs files stat --hash /ipns_local)" "$(readlink -f /ipns/local)"
cp: -r not specified; omitting directory '/ipfs/<cid>'
# cp -r "/ipfs/$(ipfs files stat --hash /ipns_local)" "$(readlink -f /ipns/local)"
```
Latest command is most disappointing. It succeeds, creates hash inside /ipns/local (instead of linking) and doesn't publishes anything. In addition this is not working for other keys.

PS: Checked on kudo 0.29.0
