### ISSUE TITLE
object get hash returns different object

### ISSUE THREAD

**Issue by nycoliver** [ipfs/go-ipfs#3306] opened 2016-10-15 19:36 UTC
#### Version information:

```
go-ipfs version: 0.4.5-dev-d5c716a
Repo version: 4
System version: amd64/darwin
Golang version: go1.7.1
```

#### Type:

```
Bug
```

#### Priority:

```
Blocking me, seems fairly important, I'll give it a P2
```
#### Description:

```
$ ipfs add test.jpg
added QmYwTwYjhDzebM9E6rucYHdXUhKYEa7LHq5Sfkd9dfS3or
$ ipfs object get QmYwTwYjhDzebM9E6rucYHdXUhKYEa7LHq5Sfkd9dfS3or | ipfs object put
added QmZp9hVnPHHY7Jd6whXrvrDzHk9n9wtiTwdPCxtSHwWzNm
```

The object returned from object get is different than the object from files add. Should be the same.

See https://github.com/ipfs/js-ipfs-api/issues/368

**Comment by whyrusleeping** [comment] 2016-12-01 00:14
duplicate of #1724

**Closed** 2017-09-02 23:30 UTC
