### ISSUE TITLE
IPFS UI + HTTPs API are always pointing to port 80

### ISSUE THREAD

**Issue by koalalorenzo** [ipfs/go-ipfs#4488] opened 2017-12-14 07:17 UTC
#### Description:
When I am exposing the API behind a reverse proxy via HTTPS (nginx), the API call coming from the `/webui` interface are all failing as they are trying to get to port `:80`. In the logs of the browser it looks like this:

```
GET https://ipfs-api.myawesomewebsite:80/api...
```

What should I do to allow the UI to talk to the HTTPS correctly?
If I am disabling HTTPS it works perfectly.

To reproduce you can spin up a container, set up nginx to point `:443` to `:5001`. Even with a fake certificate you will see the problem by browsing to `https://localhost/webui`.

**Comment by Stebalien** [comment] 2017-12-19 18:20
This has been fixed and will be released in 0.4.14.

**Closed by Stebalien** 2017-12-19 18:20 UTC

**Comment by lukecyca** [comment] 2018-02-28 19:23
It's been over two months since this bug was fixed, and the 0.4.14 milestone is still only 28% complete. Would it be possible to divide the milestone so we can make this fix (and other fixes) available in a release?

**Comment by Stebalien** [comment] 2018-02-28 22:56
So... ignore the milestone, they don't often give any clear indication of blockers. At the moment, we have a few regressions with regards to the recently updated commands library that we'd like to fix before releasing.

However, I agree, we need to get a release out the door ASAP.

**Comment by Stebalien** [comment] 2018-03-06 21:20
We should have an RC out in days. A release in a week, maybe. https://github.com/ipfs/go-ipfs/pull/4759

**Comment by lukecyca** [comment] 2018-03-13 03:39
I've tested this issue on `0.4.14-rc1` and it doesn't appear to be fully fixed. I'm possibly doing something wrong.

My webui is at https://ipfs.example.com/webui which redirects to https://ipfs.example.com/ipfs/Qm...

However it is attempting to hit the API at http://ipfs.example.com:443/api/v0/...

So the port is correct in a way, but it appears to have "http" hardcoded as the URI scheme, so it doesn't work. Afterall an https server is more than just an http server running on port 443.
