### ISSUE TITLE
multiple node, some faster, some slower, choose which one?

### ISSUE THREAD

**Issue by hoogw** [ipfs/go-ipfs#6047] opened 2019-03-04 21:44 UTC
I have multiple computer running ipfs add same content. 
Home computer have ISP upload speed 10Mbps limit.
Workplace computer have upload speed 800Mbps limit, is hundred times faster than home internet. 

When I request a file, ipfs always try to get it from slow home computer. 
If I shut down home computer, it will get it from work place computer. 

My question is if I have both home / work computer running. 
The file loading speed is slow becasue it always try to get file from home slow computer. 
If I shut down home computer, it faster, because it get file from work computer. 

2 same content node, does not help with speed. 

I have try ipfs dht provide <key>, does not help. 
please advise, how to make sure it load file from faster node, instead of slow node?

**Comment by Stebalien** [comment] 2019-03-04 22:17
Unfortunately, the issue is: https://github.com/ipfs/go-bitswap/issues/95

Basically, once we've found some nodes willing to serve content, we don't bother searching further (unless those nodes stop giving us the requested content). We do this because searching for nodes willing to provide content is pretty expensive.

Closing so we can track this in that go-bitswap issue.

**Closed by Stebalien** 2019-03-04 22:17 UTC
Labels: bug
