### ISSUE TITLE
Low performance over QUIC

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#8647] opened 2022-01-09 15:30 UTC
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

built from source

### Version

```Text
Sending side:

go-ipfs version: 0.12.0-dev-deb79a258
Repo version: 11
System version: amd64/linux
Golang version: go1.17.5

Receiving side:

go-ipfs version: 0.11.0-dev-5a61bedef
Repo version: 11
System version: amd64/linux
Golang version: go1.17.3
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Announce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/80",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/443",
      "/ip6/::/tcp/443",
      "/ip4/0.0.0.0/udp/443/quic",
      "/ip6/::/udp/443/quic"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
  ],
  "DNS": {
    "Resolvers": null
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": true,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": false,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "1GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 60
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": false,
    "FilestoreEnabled": true,
    "GraphsyncEnabled": true,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "ShardingEnabled": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": true
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "12D3KooWAtWXFYuNE2biceY5irfsnhA9Cvekbmx1tiKntLbkqvn1"
  },
  "Internal": {},
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 2048
  },
  "Migration": {
    "DownloadSources": null,
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": "gossipsub"
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "dhtclient"
  },
  "Swarm": {
    "AddrFilters": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.0.0/ipcidr/29",
      "/ip4/192.0.0.8/ipcidr/32",
      "/ip4/192.0.0.170/ipcidr/32",
      "/ip4/192.0.0.171/ipcidr/32",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/24",
      "/ip4/192.168.1.0/ipcidr/24",
      "/ip4/192.168.2.0/ipcidr/24",
      "/ip4/192.168.3.0/ipcidr/24",
      "/ip4/192.168.4.0/ipcidr/24",
      "/ip4/192.168.5.0/ipcidr/24",
      "/ip4/192.168.6.0/ipcidr/24",
      "/ip4/192.168.7.0/ipcidr/24",
      "/ip4/192.168.9.0/ipcidr/24",
      "/ip4/192.168.10.0/ipcidr/24",
      "/ip4/192.168.11.0/ipcidr/24",
      "/ip4/192.168.12.0/ipcidr/22",
      "/ip4/192.168.16.0/ipcidr/20",
      "/ip4/192.168.32.0/ipcidr/19",
      "/ip4/192.168.64.0/ipcidr/18",
      "/ip4/192.168.128.0/ipcidr/17",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "ConnMgr": {
      "GracePeriod": "3m",
      "HighWater": 50,
      "LowWater": 30,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "EnableAutoRelay": false,
    "EnableRelayHop": false,
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description

I'm downloading my system updates via the ipfs. Pacman is using the curl-library and only do HTTP calls to the local IPFS gateway.

I noticed that the performance is pretty bad:
- There are many timeouts within a download, so say it gets a megabyte and then stalls.
- If I deactivate the download timeout I sometimes receive a 408 from the ipfs gateway.
- Overall the download feels "chunky" from time to time. So I get a block, long time nothing, then I get a block, long time nothing. Then it returns to normal download speeds.

I deactivated QUIC on the receiving side and all the issues listed above are gone.

Internet provider: O2 via LTE with 50-75% signal strength on a stationary location.
Connection to the router: Wifi which shows signal strength: Good

**Comment by aschmahmann** [comment] 2022-02-25 16:31
If you can give more debug information (e.g. pprof) or a more stable reproduction that would be helpful. @marten-seemann are there any particular debugging tips you'd give here?

**Comment by marten-seemann** [comment] 2022-02-25 16:46
Recording a qlog would be a good idea. Set the QLOGDIR env variable to a directory. Every QUIC connection will then log a qlog. qlogs can best be visualized using https://qvis.quictools.info/.

**Comment by BigLep** [comment] 2022-03-25 15:20
Closing because additional requested info wasn't provided.  Feel free to reopen with the additional info.

**Closed by BigLep** 2022-03-25 15:20 UTC
Labels: kind/bug, need/author-input
