### ISSUE TITLE
Option --timeout does not seem to have the expected effect

### ISSUE THREAD

**Issue by tdiesler** [ipfs/go-ipfs#5228] opened 2018-07-13 19:22 UTC
#### Version information:

go-ipfs version: 0.4.15-
Repo version: 6
System version: 386/linux
Golang version: go1.10.2

#### Type:

Bug, Documentation

#### Description:

When I had `ipfs get <some hash>` hanging forever, I tried the `--timeout` option like this

```
ipfs --timeout=10000 get <some hash>
```

Instead of returning after 10sec, the cmd returned immediately. Same effect with `--timeout=10`.
The documentation does not say what unit the timeout is and how this can be used.

**Comment by skliarie** [comment] 2018-07-16 05:31
Don't want to hijack the ticket, it looks like we are talking about the same thing: is there a way to make all requests on port :8080 to timeout after several seconds?
The problem kills performance of the http://d.tube videos start - the site logic requests high resolution image and if it is not found, then it falls back to low resolution image. The huge (infinite?) timeout causes video opening screen to become grey, thus killing whatever user experience there remains.

**Comment by tdiesler** [comment] 2018-07-16 10:15
Yes, `--timeout=10s` works as expected. 

This however does not work `--timeout=10000000`. The call returns immediately without error message.

**Comment by RaffaGonzo** [comment] 2018-07-17 22:21
Mind if I look at the code and add in an error feature? (if no one is already doing it)

**Comment by Stebalien** [comment] 2018-07-18 17:08
@skliarie that's the gateway, not the API, so it doesn't take a timeout param. I assume dtube makes it's requests from JS so you'll probably want to just set a request timeout.

@tdiesler that's expected. A nanosecond is 10^-9 seconds. That timeout is 0.01 seconds (10ms).

Closing as not a bug (feel free to continue discussing if you disagree).

**Closed by Stebalien** 2018-07-18 17:08 UTC
