### ISSUE TITLE
Too high CPU use

### ISSUE THREAD

**Issue by poly000** [ipfs/go-ipfs#6930] opened 2020-02-25 15:56 UTC
Computer runs slowly, The CPU usage is high. :(
https://github.com/poly000/Documents/raw/master/ipfs-profile.tar.gz

**Comment by Stebalien** [comment] 2020-02-26 03:56
OS: Windows
Version: 0.4.23

**Comment by Stebalien** [comment] 2020-02-26 04:04
* Were you doing something when this happened?
* How long did the CPU spike last?
* What experimental features do you have enabled?
* Are you using a private network? Relays? etc.

It looks like your node is trying to create a bunch of outbound connections _very_ rapidly, and failing _very rapidly_.

From what I can tell, you have a _single_ provider query running. There's no way that should trash your CPU like that. That is, unless there's something on your network _very_ rapidly resetting any outbound IPFS connections (e.g., the GFW?).

**Comment by poly000** [comment] 2020-02-26 13:20
I tried to upload something.
On and off in hours.
idk but might be none. because I just changed "10GB" to "20GB" in my config
i am using wifi
yes, i am living in china
bug i dont know how to config a proxy

**Comment by poly000** [comment] 2020-02-26 13:37
> 
> 
>     * Were you doing something when this happened?
> 
>     * How long did the CPU spike last?
> 
>     * What experimental features do you have enabled?
> 
>     * Are you using a private network? Relays? etc.
> 
> 
> It looks like your node is trying to create a bunch of outbound connections _very_ rapidly, and failing _very rapidly_.
> 
> From what I can tell, you have a _single_ provider query running. There's no way that should trash your CPU like that. That is, unless there's something on your network _very_ rapidly resetting any outbound IPFS connections (e.g., the GFW?).

I tried to upload something.
Off and on in hours.
idk but might be none. because I only changed "10GB" into "20GB" in my config
i am using wifi
yes, i am living in china
i dont know how to config a proxy

now i changed "set http_proxy=http://127.0.0.1:1080" into "set http_proxy=127.0.0.1:1080"
it looks like the problem is solved...
thank you for your help :)

**Comment by Stebalien** [comment] 2020-02-26 16:25
Odd, the websocket transport will use your proxy but the main TCP transport (the one causing the issues) shouldn't.

**Comment by poly000** [comment] 2020-02-26 18:33
> 
> 
> Odd, the websocket transport will use your proxy but the main TCP transport (the one causing the issues) shouldn't.

hmmm
what will happen if the http_proxy

**Comment by Stebalien** [comment] 2020-02-26 19:35
And setting `http_proxy` fixes it?

**Comment by poly000** [comment] 2020-02-27 03:25
> 
> 
> And setting `http_proxy` fixes it?

yes

**Comment by Stebalien** [comment] 2020-02-27 03:40
Strange...

**Comment by poly000** [comment] 2020-02-27 06:58
when I upload something, my conputer ru slowly again...
im taking a ipfs-profile

**Comment by poly000** [comment] 2020-02-27 07:04
> 
> 
> Strange...

when I upload something, my computer run slowly again...
https://github.com/poly000/Documents/raw/master/ipfs-profile.tar.gz
`ipfs.exe` is the same as last upload

**Comment by poly000** [comment] 2020-02-28 18:16
> 
> 
> > Strange...
> 
> when I upload something, my computer run slowly again...
> with Intermittent white noise in my headphones
> https://github.com/poly000/Documents/raw/master/ipfs-profile.tar.gz
> `ipfs.exe` is the same as last upload

idk why,
i added "set https_proxy=127.0.0.1:1080" and start ipfs dameon
after i uploaded a file, my pc do not runs slowly

**Comment by Stebalien** [comment] 2020-03-17 21:59
Sorry for letting this sit. Unfortunately, we can't reproduce this issue so debugging it is pretty much impossible. If we get additional reports of this behavior, we can look for common themes/conditions and try to make progress.

**Comment by poly000** [comment] 2020-03-29 08:37
> 
> 
> Sorry for letting this sit. Unfortunately, we can't reproduce this issue so debugging it is pretty much impossible. If we get additional reports of this behavior, we can look for common themes/conditions and try to make progress.

thx for your help, i will try to find logs

**Comment by hsanjuan** [comment] 2020-03-29 15:29
Hi, please attach logs here, but only if they are relevant. I am going to close this for the moment for the reasons above (can't reproduce, can't debug). We can always re-open if there is new, relevant information later. Thanks!

**Closed by hsanjuan** 2020-03-29 15:29 UTC
Labels: bug
