### ISSUE TITLE
Removing block does not clear the DHT table

### ISSUE THREAD

**Issue by redmouth** [ipfs/go-ipfs#4249] opened 2017-09-19 09:10 UTC
After a block is unpinned and removed, local DHT still keep the block's key.  As designed?

**Comment by Stebalien** [comment] 2017-09-20 19:57
I assume you mean that we don't cancel provider records (i.e., "I provide block X")? Yes, this is by design. Publishing provider records already creates a lot of spam (we're working on reducing this) so we just let them expire (at least for the moment).

**Comment by michaelavila** [comment] 2019-06-05 18:41
Closing as question was adequately answered with nothing to fix or follow up on.

**Closed by michaelavila** 2019-06-05 18:41 UTC
