### ISSUE TITLE
Path Resolve error: no link named "fontawesome-webfont.woff2"

### ISSUE THREAD

**Issue by d6e** [ipfs/go-ipfs#1458] opened 2015-07-09 05:36 UTC
## Repro steps:
- `ipfs daemon`
- `open http://localhost:5001/webui`

## Environment:
- Chromium 45.0.2430.0 (64-bit)
- ipfs 0.3.5

```
> $ ipfs daemon
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/162.244.136.153/tcp/4001
Swarm listening on /ip4/192.168.1.148/tcp/4001
Swarm listening on /ip4/192.168.99.1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
ERRO[22:24:43:000] Path Resolve error: multihash length inconsistent: &{36  220 [115 225]}  module=core/server
ERRO[22:29:16:000] Path Resolve error: no link named "fontawesome-webfont.woff2" under QmWjympWW8hpP5Jgfu66ZrqTMykUBjGbFQF2XgfChau5NZ  module=core/server
ERRO[22:29:17:000] Path Resolve error: no link named "fontawesome-webfont.woff2" under QmWjympWW8hpP5Jgfu66ZrqTMykUBjGbFQF2XgfChau5NZ  module=core/server
ERRO[22:29:21:000] Path Resolve error: no link named "fontawesome-webfont.woff2" under QmWjympWW8hpP5Jgfu66ZrqTMykUBjGbFQF2XgfChau5NZ  module=core/server
ERRO[22:29:42:000] Path Resolve error: no link named "fontawesome-webfont.woff2" under QmWjympWW8hpP5Jgfu66ZrqTMykUBjGbFQF2XgfChau5NZ  module=core/server
ERRO[22:29:45:000] Path Resolve error: no link named "fontawesome-webfont.woff2" under QmWjympWW8hpP5Jgfu66ZrqTMykUBjGbFQF2XgfChau5NZ  module=core/server
ERRO[22:29:49:000] Path Resolve error: no link named "fontawesome-webfont.woff2" under QmWjympWW8hpP5Jgfu66ZrqTMykUBjGbFQF2XgfChau5NZ  module=core/server
```

**Comment by jbenet** [comment] 2015-07-09 05:51
@d6e interesting -- thanks! looks like an asset is not on https://github.com/ipfs/webui/

**Comment by jbenet** [comment] 2015-07-09 05:51
duplicate of https://github.com/ipfs/webui/issues/60 -- sorry we should fix this soon.

**Closed by jbenet** 2015-07-09 05:52 UTC

**Comment by kingflurkel** [comment] 2015-10-26 12:51
Still get this error, should I do something?

**Comment by whyrusleeping** [comment] 2015-10-26 16:54
@kingflurkel it still hasnt actually been fixed yet.

@jbenet @diasdavid when can we ship a new version of the webui?

**Comment by jbenet** [comment] 2015-10-28 01:11
not sure. something to bring up in the webui repo
