### ISSUE TITLE
pin_add hangs indefinitely

### ISSUE THREAD

**Issue by Netherdrake** [ipfs/go-ipfs#3905] opened 2017-05-06 03:31 UTC
### Version:
```
~ % ipfs version --all
go-ipfs version: 0.4.8-
Repo version: 5
System version: amd64/linux
Golang version: go1.8
```
*I also have the same issue on OSX, 0.4.8.*

#### Severity:
**Medium/Low**

#### Description:

When I try pinning content that has no nodes that have that content, ipfs will just hang forever.
```
% ipfs --debug=true pin add QmPVGeoYekRKyb2iZ3gLa6h6ekEivBVeJZpayQfQrB1wL3
15:54:25.881  INFO   cmd/ipfs: IPFS_PATH /Users/user/.ipfs main.go:304
15:54:25.881 DEBUG   cmd/ipfs: calling pre-command hooks... main.go:298
15:54:25.881 DEBUG   cmd/ipfs: executing command via API main.go:335
```

```
% ipfs diag cmds
Command    Active  StartTime        RunTime
pin/add    true    May  5 15:44:24  32m17.870082689s
```

**Comment by Kubuxu** [comment] 2017-05-06 07:06
That is because before we pin we execute fetch on the graph so it is local. Only fully local content can currently be pinned. You can add timeout to ipfs command so it times out.

`ipfs --timeout=25m pin add QmPVGeoYekRKyb2iZ3gLa6h6ekEivBVeJZpayQfQrB1wL3`

**Comment by Netherdrake** [comment] 2017-05-06 09:32
What I'd really like ideally is an async flag, so I can just do:
```
ipfs --background=true pin add QmPVGeoYekRKyb2iZ3gLa6h6ekEivBVeJZpayQfQrB1wL3
```

And then the API returns instantly, and ipfs daemon figures it out at its own pace. This would be very useful if a resource is temporarily unavailable, and ipfs can keep trying to fetch it over time.

@Kubuxu Do you happen to know if its possible to pass custom flags with Python `ipfsapi` wrapper?
Perhaps something like:
```
ipfs.pin_add(multihash, recursive=True, opts={'background':True})
``

**Comment by whyrusleeping** [comment] 2017-05-10 05:50
Also try adding the `--progress` option to the pin add.

**Comment by Katamori** [comment] 2017-05-15 00:15
The issue occured here, as well. 0.4.8 as well as 0.4.9, Arch Linux distro.

Though apparently the reason is found, I just wanted to highlight that it's definitely a reproduced and reproducable issue, and that I also would like to see it change, and/or listening to the possible solutions.

**Comment by whyrusleeping** [comment] 2017-09-02 01:08
@Katamori you can use the progress flag mentioned above to watch the pin commands progress.

I'm going to close this for now, pinning large graphs is expected to take some time.

As for 'running a command async', please see this issue (and other related issues linked): https://github.com/ipfs/go-ipfs/issues/3114

**Closed by whyrusleeping** 2017-09-02 01:08 UTC
