### ISSUE TITLE
Better Constructor Errors

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6394] opened 2019-06-02 00:04 UTC
> Error: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".IpnsRepublisher.func1 (/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/node/ipns.go:38): failed to build namesys.NameSystem: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".Namesys.func1 (/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/node/ipns.go:31): failed to build routing.Routing: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".Routing (/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/node/libp2p/routing.go:60): could not build value group libp2p.Router[group="routers"]: could not build arguments for function "github.com/ipfs/go-ipfs/core/node/libp2p".BaseRouting (/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/node/libp2p/routing.go:34): failed to build libp2p.BaseIpfsRouting: function "github.com/ipfs/go-ipfs/core/node/libp2p".Host (/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/node/libp2p/host.go:39) returned a non-nil error: privnet: private network was not configured but is enforced by the environment

**Comment by schomatis** [comment] 2021-12-23 16:32
Closing as I think this is a duplicate of https://github.com/ipfs/go-ipfs/issues/6394.

**Closed by schomatis** 2021-12-23 16:32 UTC
Labels: kind/enhancement
