### ISSUE TITLE
./ipfs pubsub peers [<topic>] does not return self as a peer iff self is subscribed to a topic.

### ISSUE THREAD

**Issue by zutils** [ipfs/go-ipfs#5808] opened 2018-11-29 15:49 UTC
#### Version information:
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1

#### Type:
Bug

#### Description:
  ./ipfs pubsub peers [topic] does not return self as a peer iff self is subscribed to a topic.  If I am NOT subscribed to the topic, I would expect that my peerid would not be in this list. If I am, I would suspect my peerid to be in the list.

  I have 3 terminal windows open.  The first starts the ipfs daemon. The second subscribes to an ipfs topic, and the third lists the peers that are connected.  My own hash does not show up in the list. Only those connecting from the outside (sometimes/rarely) show up. Occasionally, I will get a "Error: api not running" when using the cli to publish random data to a topic.

**Comment by eingenito** [comment] 2018-12-05 21:34
Hey @zutils this is expected behavior. `ipfs pubsub peers <topic>` is intended to return a list of peers you are connected to and pubsub'ing on a given topic. In this way it is consistent with `ifps swarm peers`. If you want to find out what topics your node is currently subscribed to you can use `ipfs pubsub ls`. Hope that helps.

**Comment by eingenito** [comment] 2018-12-05 21:36
I'm going to close this issue for now. If you have further questions about ipfs behavior please consider posting them on https://discuss.ipfs.io/ first. More people can help there and it lets others learn from the discussion. Thanks.

**Closed by eingenito** 2018-12-05 21:36 UTC
