### ISSUE TITLE
No cache-control on Host: based requests

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#5968] opened 2019-02-04 15:21 UTC
On domain based requests we should use ETag base cache. We are currently not doing this.
The solution is to send `Cache-control: public` as the ETag is already sent.

**Comment by magik6k** [comment] 2019-02-04 15:38
cc @lidel

**Comment by lidel** [comment] 2019-02-16 09:41
I believe this is a duplicate of https://github.com/ipfs/go-ipfs/issues/1818#issuecomment-450866591

**Closed** 2022-01-18 20:36 UTC
Labels: kind/enhancement, help wanted
