### ISSUE TITLE
Amount of RAM used by IPFS burst to 500 MB and more

### ISSUE THREAD

**Issue by gdeverlant** [ipfs/go-ipfs#4531] opened 2017-12-29 08:36 UTC
#### Description:

Is it normal that the amount of RAM used by IPFS is so extreme?

![image](https://user-images.githubusercontent.com/26530975/34432864-81cf3b04-ec7b-11e7-8362-6946bcc6a9e2.png)

**Comment by Stebalien** [comment] 2017-12-29 16:54
Memory usage generally depends on how many peers you have. We've been working on reducing it but yes, 500MiB isn't that surprising at the moment.

If you want to reduce it further, try setting a lower connection closing limit: https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#connmgr

**Comment by leerspace** [comment] 2017-12-30 14:53
I think this might be related to (if not a duplicate of) #3318

**Comment by Stebalien** [comment] 2018-01-28 07:43
@leerspace good point.

**Closed by Stebalien** 2018-01-28 07:43 UTC
