### ISSUE TITLE
IPFS should stop accepting pin requests/new files after hitting the StorageMax limit

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7875] opened 2021-01-21 16:12 UTC
IPFS will currently accept pins and new files for the MFS when way beyond StorageMax. This is an issue since there's no other measure in place to stop writing more data to the disk than that.

When the GC is on it cannot clean up when we just continue pinning stuff, since it's not allowed to clean pins up.

While changing StorageMax to a hard limit for pinning/mfs operation, it should affect any other operations like getting data from the network or DHT operations, so the node continues to be operational - it just cannot mark more data for storing it permanently.

An example:

```
$ ipfs repo stat
NumObjects: 404282
RepoSize:   88709351300
StorageMax: 60000000000
RepoPath:   /home/ipfs/.ipfs
Version:    fs-repo@11
```

```
$ du -hc .ipfs/blocks/ | grep total
83G     total
```

IPFS is started on this machine with ` --enable-gc` on.

_This is somewhat related to this: https://github.com/ipfs/go-ipfs/issues/3066_

**Comment by RubenKelevra** [comment] 2021-01-21 16:54
This is basically how StorageMax was originally intended to work (I guess):

https://github.com/ipfs/go-ipfs/blob/master/test/sharness/t0082-repo-gc-auto.sh#L57

**Comment by Stebalien** [comment] 2021-02-12 18:28
Duplicate of https://github.com/ipfs/go-ipfs/issues/5140.

**Closed by Stebalien** 2021-02-12 18:28 UTC
Labels: kind/enhancement, need/triage
