### ISSUE TITLE
IPFS gateway can't be accessed from China

### ISSUE THREAD

**Issue by gogolxdong** [ipfs/go-ipfs#4765] opened 2018-03-05 02:28 UTC
IPFS gateway can't be accessed from China unless using vpn, how to solve this problem?

**Comment by Stebalien** [comment] 2018-03-05 05:33
Duplicate of https://github.com/ipfs/community/issues/290.

The best way is to install go-ipfs locally and use your *local* gateway. However, there's also a list of alternative public gateways here: https://ipfs.github.io/public-gateway-checker/.

Note: this is *not* an endorsement of any of these alternative public gateways. I have absolutely no idea if they're trustworthy.

I'm going to close this as it isn't really a bug in go-ipfs. However, I understand our support forum (discuss.ipfs.io) is currently inaccessible in China. If you have any more questions, please ask on https://github.com/ipfs/community/issues for now (unless you can find some way to access discuss.ipfs.io).

**Closed by Stebalien** 2018-03-05 05:33 UTC

**Comment by dongtianyi** [comment] 2018-03-05 06:41
Yes, we use https://ipfs.github.io/public-gateway-checker  to check available gateway.

**Comment by Kubuxu** [comment] 2018-03-05 12:37
@Stebalien I think we should improve flow of installing go-ipfs straight from sources by building source distribution package of `gx`, `gx-go` and `go-ipfs` sources bundled and possibly signed so they can be transported by thirdparties with trust. What do you think?

**Comment by Stebalien** [comment] 2018-03-06 18:44
Yeah, that sounds like a good idea. Also, publishing an IPNS record for dists.ipfs.io would help (https://github.com/ipfs/ipfs-update/issues/80)

**Comment by Sunnykaby** [comment] 2018-03-22 02:20
Hello, I just download the ipfs-go src from github. and I want to build the ipfs from the go src, but I found the error:
I can't get anything form the "/ipfs/QmT3CLJKJzWPuN4NAN4LLy69UpKskMF3AuYhXstKdn8V43".
