### ISSUE TITLE
`ipfs dag put` does not serialize IPLD CIDv0 consistent with spec

### ISSUE THREAD

**Issue by iostat** [ipfs/go-ipfs#4227] opened 2017-09-13 21:18 UTC
#### Version information:
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8.3

#### Type:
Potential bug?

#### Severity:
Medium

#### Description:
Hi all,

I've recently been playing with the `ipfs dag` feature, and observed that the CBOR it generates and stores doesn't quite conform (ostensibly) to the IPLD CIDv0 spec when referencing CIDv0 objects:

As an example (`rq` is  [dflemstr's rq](https://github.com/dflemstr/rq) tool used to read the CBOR):

1. Let's create a simple case with a CIDv0 link: 
```
$ echo '{"hello": "world", "link": {"/": "QmR7GSQM93Cx5eAg6a6yRzNde1FQv7uL6X1o4k7zrJa3LX" } }' | ipfs dag put -
zdpuAp8w8FUere3r7XbN1kjdDhkqT9UqjMUmjkhJm7dHiHUwr
```
2. Read back the raw CBOR with `ipfs block get`, and pipe it to `rq -c` for readability
```
$ ipfs block get zdpuAp8w8FUere3r7XbN1kjdDhkqT9UqjMUmjkhJm7dHiHUwr | rq -c
{
  "hello": "world",
  "link": [
    0,
    18,
    32,
    41,
    37,
    84,
    34,
    69,
    184,
    73,
    16,
    103,
    152,
    219,
    68,
    116,
    252,
    207,
    1,
    179,
    102,
    128,
    236,
    136,
    195,
    83,
    153,
    146,
    143,
    200,
    161,
    189,
    112,
    83,
    204
  ]
}
```

We expect the CIDv0 multihash to be 46 bytes, as a base58 encoded string of 34 actual bytes (1 byte to signifying SHA2-256, another for the length (32), and 32 more for the hash itself).

The [CIDv0](https://github.com/ipld/cid#cidv0) spec specifies:
* the multibase is always base58btc and implicit (not written)
* the multihash is written as is

My understanding of the spec is that the link should be stored as either a text/byte string containing the base58 encoded multihash (i.e., as `Qm...`), or just a raw 34 byte non-base58 multihash. However, as we can see, our link is stored instead as a 35-byte bytestring, with a `0x00` "binary" multibase prefix (written!) and the 34 non-base58-bytes.

Not sure if this is actually expected behavior and a misunderstanding of the spec on my end, a misimplementation of the proposed spec, or perhaps an inconsistency in the CIDv0 spec itself.

Thanks!

**Comment by whyrusleeping** [comment] 2017-09-13 23:48
I believe this is as intended. Cids are stored as binary data (not base58 encoded) and the '0' byte prefix is the multibase, signifying that there is no encoding. That said, I would expect to see a tag in the cbor output.

**Comment by iostat** [comment] 2017-09-13 23:58
Thanks for the response!

That makes perfect sense. I've believe I've seen some of the go-ipld libraries check for cidv0 by checking whether input[:2] == "Qm", but that may have been for JSON decoding only. Perhaps this is a point worth clarifying in ipld/spec? If this 0-multibase practice for binary storage is consistent I'd be happy to submit a PR for that. 

With regards to the tag, I believe that rq omits it unless you specify some flag, but it's definitely there in the actual CBOR binary.

**Comment by whyrusleeping** [comment] 2017-09-16 21:08
Yeah, please do submit a PR for that to the spec, keeping things consistent is important.

I'm gonna go ahead and close this issue as resolved, feel free to reopen if you think its not.

**Closed by whyrusleeping** 2017-09-16 21:08 UTC
