### ISSUE TITLE
ipfs update not working

### ISSUE THREAD

**Issue by sexybiggetje** [ipfs/go-ipfs#2460] opened 2016-03-12 15:24 UTC
I used the installer as linked on the ipfs.io install page. This is the OS X v0.3.11 package (http://dist.ipfs.io/go-ipfs/v0.3.11/go-ipfs_v0.3.11_darwin-amd64.tar.gz).

After install I like to check if I'm up to date, so we issue ipfs update:
```sh
martijn@kenpachi ~/go-ipfs> ipfs update
Error: %!s(MISSING) not installed.
```

I'm now left curious as to what wasn't installed, and how to properly fix this. I do have go 1.6 installed and not 1.5, but that shouldn't be too much of a difference for this operation.

**Comment by tomgg** [comment] 2016-03-13 01:27
That error message is fixed in an updated version of go-ipfs; it directs the user to [ipfs-update](https://github.com/ipfs/ipfs-update).

(Is this a catch 22?---unable to update because an update is required to know how to update.)

**Comment by sexybiggetje** [comment] 2016-03-13 09:44
Sadly that requires me to manually install ipfs-update, but no problem. However, I tried to install v0.4.0-dev, which yails then with the following mesage:

```martijn@kenpachi ~/g/bin> ./ipfs-update install v0.4.0-dev
fetching ipfs version v0.4.0-dev
binary downloaded, verifying...
success!
stashing old binary
installing new binary to /usr/local/bin/ipfs
checking if repo migration is needed...
  - Migration required
ERROR: Migration Failed:  # cd /Users/martijn/go/src/github.com/ipfs/fs-repo-migrations; git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'ipfs-1-to-2/golang-lru'
package github.com/ipfs/fs-repo-migrations: exit status 1
 exit status 1
install failed, reverting changes...
ERROR: # cd /Users/martijn/go/src/github.com/ipfs/fs-repo-migrations; git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'ipfs-1-to-2/golang-lru'
package github.com/ipfs/fs-repo-migrations: exit status 1
 exit status 1
```

**Comment by whyrusleeping** [comment] 2016-03-15 00:20
@sexybiggetje I couldnt reproduce the issue youre having. It appears from the log output that your source tree for fs-repo-migrations might be dirty. Could you try removing `$GOPATH/src/github.com/ipfs/fs-repo-migrations`  and rerunning `ipfs-update` command?

**Comment by sexybiggetje** [comment] 2016-03-15 05:19
Well that got me a step further, but I now get the strangest error :).

```
martijn@kenpachi ~/g/bin> ./ipfs-update install v0.4.0-dev
fetching ipfs version v0.4.0-dev
binary downloaded, verifying...
success!
stashing old binary
installing new binary to /usr/local/bin/ipfs
checking if repo migration is needed...
  - Migration required
ERROR: Migration Failed:  package github.com/ipfs/fs-repo-migrations: cannot download, $GOPATH not set. For more details see: go help gopath
 exit status 1
install failed, reverting changes...
ERROR: package github.com/ipfs/fs-repo-migrations: cannot download, $GOPATH not set. For more details see: go help gopath
 exit status 1 
martijn@kenpachi ~/g/bin> echo $GOPATH
/Users/martijn/go
martijn@kenpachi ~/g/bin> 
```
But I think that's a message from go itself?

**Comment by whyrusleeping** [comment] 2016-03-15 17:39
Yeah, thats kinda really weird. I'll look into that...

**Comment by whyrusleeping** [comment] 2016-03-15 17:42
what happens if you run `go get -u github.com/ipfs/fs-repo-migrations` on your command line?

**Comment by sexybiggetje** [comment] 2016-03-15 18:21
It gives a similar result. 
```
martijn@kenpachi ~/g/bin> go get -u github.com/ipfs/fs-repo-migrations
package github.com/ipfs/fs-repo-migrations: cannot download, $GOPATH not set. For more details see: go help gopath
```

I think I should figure this one out seperately from this issue, it should be go related. I'm able to do a simple hello world with go, but somehow the paths are not playing nice. I'll completely remove go and try again on a fresh installation.

**Comment by whyrusleeping** [comment] 2016-03-15 20:29
@sexybiggetje cool, let me know how it goes.

**Comment by whyrusleeping** [comment] 2016-05-09 17:26
@sexybiggetje can this be closed?

**Closed** 2016-05-09 20:29 UTC
