### ISSUE TITLE
more insight into t0130 random sharness failures

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4038] opened 2017-07-05 15:49 UTC
https://ipfs.io/ipfs/QmSibg7w86aN7eW7HiLGfGzzc4kEdAsnWSfyFjHQyih9pm

in particular:
```
==> .iptb/2/daemon.stderr <==
Error: ipfs daemon is running. please stop it to run this command
Use 'ipfs daemon --help' for information about this command
```

Daemons from a previous run are still alive. We kinda suspected this was the case.

**Comment by Stebalien** [comment] 2017-07-28 05:15
I've finally reproduced this locally and, while I *do* have other daemons running, I don't see any connections between the two test daemons and these other daemons (checked with netstat).

At this point, it looks like peer A gets stuck dialing peer B. Peer B lists peer A in `ipfs swarm peers` but peer A doesn't list peer B.

Peer A goroutine dump: https://gist.github.com/05382bfd13c0944251d6357821f51560
Peer B goroutine dump: https://gist.github.com/8be42f0f6b576f89f76f4747de698ac1

I'll continue to look into this but figured I'd post this here in case my computer dies or something...

**Comment by Stebalien** [comment] 2017-07-28 05:33
Turns out we're closing a closed channel, panicking, and then deadlocking when we try to re-take the lock in a deferred statement:

/ipfs/QmRWT7HgGeMovh1MUiidWFj9i96DjH5KXPmQWkPQDefxHG/go-multiplex/multiplex.go:242

**Comment by Stebalien** [comment] 2017-07-28 08:31
(likely) fix: https://github.com/whyrusleeping/go-multiplex/issues/5

**Closed** 2017-07-30 03:53 UTC
Labels: test failure
