### ISSUE TITLE
`ipfs add --encoding=json ...` doesn't give json

### ISSUE THREAD

**Issue by matthewbauer** [ipfs/go-ipfs#7492] opened 2020-06-18 19:20 UTC
#### Description:

Running this command, gives me text, not json:

```
$ mkdir -p a
$ ipfs --encoding=json add -r a
added QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn a
 0 B / ? [--------------------------------------------------------------------=]
```

The encoding doc suggests it should just give json:

```
  --enc, --encoding          string - The encoding type the output should be
                                      encoded with (json, xml, or text).
                                      Default: text.
```

**Comment by Stebalien** [comment] 2020-06-18 20:13
Unfortunately, this is a duplicate of https://github.com/ipfs/go-ipfs/issues/1121. It's fixable but fixing it hasn't been a high priority.

**Closed by Stebalien** 2020-06-18 20:13 UTC
Labels: kind/bug, need/triage
