### ISSUE TITLE
iptb tests fail often

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1162] opened 2015-04-29 00:04 UTC
iptb tests fail often. we think it's the port reuse. randomizing ports should fix this.

**Comment by jbenet** [comment] 2015-04-29 00:04
cc @whyrusleeping

**Comment by whyrusleeping** [comment] 2015-04-30 07:45
```
todo.append("make iptb tests not fail as often")
```

**Comment by whyrusleeping** [comment] 2015-04-30 17:05
I've updated iptb to take a port option on init to specify the port range. I think we can have each iptb test use a port range outside the normal ports we use (i.e. 10000, 11000, etc). If it continues to fail after that, then that signals to me that things are not shutting down properly and i'll need to look into that more. But for now, i'm fairly confident in the processes being closed correctly.

**Comment by jbenet** [comment] 2015-05-01 11:43
kk

**Comment by whyrusleeping** [comment] 2015-05-02 09:38
@jbenet I'm researching how travis is running our tests. I suspect that its running both our go1.3 and go1.4 tests in parallel on the same VM, but I dont have any proof to back up that statement.

**Comment by whyrusleeping** [comment] 2015-05-10 23:25
closing this for now, havent seen many failures caused by iptb recently

**Comment by jbenet** [comment] 2015-05-11 13:18
Yeah I think you fixed them with port chosing



—

**Comment by whyrusleeping** [comment] 2016-01-02 02:32
this has been fixed

**Closed by whyrusleeping** 2016-01-02 02:32 UTC
Labels: bug, cleanup, testing
