### ISSUE TITLE
p2p-circuit addresses are still printed with /ipfs/QmRelay/p2p-circuit/p2p/QmTarget

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6868] opened 2020-02-04 17:18 UTC
#### Version information:

master

#### Description:

`ipfs swarm peers` is listing addresses of the form /**ipfs**/QmRelay/p2p-circuit/**p2p**/QmTarget. This should _never_ happen.

**Comment by vipulnayyar** [comment] 2020-03-02 22:57
Hi @Stebalien, although this issue has already been assigned, I decided to look more into this as it seemed interesting. How do I reproduce this issue on the master branch?

I have only encountered addresses in the incorrect format of '/**ipfs**/QmRelay/p2p-circuit/**p2p**/QmTarget', when I was mistakenly running ipfs daemon v0.4.23 with ipfs swarm cmd client built from master.

However, when I correctly ran the ipfs daemon and the ipfs swarm client, both built from the latest master, I could see the p2p-circuit addresses listed in the form '/ip4/206.116.153.42/tcp/4003/**p2p**/QmXow5.../p2p-circuit/**p2p**/QmUHmrr...'

How can I reliably recreate this issue on master? Right now, I am just starting the daemon and waiting for peers to increase to over 170, after which p2p-circuit addresses start appearing in the list. I am unable to see any peer addresses in the list with the keyword '**ipfs**' in it.

**Comment by Stebalien** [comment] 2020-03-02 23:23
Thanks!

>  when I was mistakenly running ipfs daemon v0.4.23 with ipfs swarm cmd client built from master.

Yeah, that's a different issue.

> How can I reliably recreate this issue on master?

I'm not able to reliably reproduce it either. However, I haven't _fixed_ it so I assume it's still an issue. On the other hand, I'm no longer seeing this in the wild.

**Comment by hsanjuan** [comment] 2020-03-05 09:39
Then I guess let's close it and re-open if things change?

**Comment by vipulnayyar** [comment] 2020-03-06 13:55
@hsanjuan, I picked this issue to work on because it was listed as one of the TODOs in #6776 for 0.5 release. Maybe it can also be removed from that list.

**Closed** 2020-03-07 02:25 UTC
Labels: bug
