### ISSUE TITLE
[Question/Feature] Can "ipfs pin" also give a name to the pin?

### ISSUE THREAD

**Issue by DaniellMesquita** [ipfs/go-ipfs#7891] opened 2021-01-31 06:58 UTC
IPFS UI have an option to list pins and rename them.

Can the "ipfs pin" command also name/rename a pin?
If not, please implement it.

**Comment by aschmahmann** [comment] 2021-01-31 07:15
go-ipfs side of this is a duplicate of https://github.com/ipfs/go-ipfs/issues/4586 (some updates in https://github.com/ipfs/go-ipfs/pull/4757#issuecomment-728198661).

**Closed by aschmahmann** 2021-01-31 07:15 UTC
Labels: kind/enhancement
