### ISSUE TITLE
Too many open files.

### ISSUE THREAD

**Issue by VA3FXP** [ipfs/go-ipfs#4096] opened 2017-07-27 14:39 UTC
#### Version information:
% ipfs version --all
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/linux
Golang version: go1.8.3

#### Description:
While trying to upload files I get an error message:   "Too many open files"
If I re-run the command, the file-upload progresses further, and then crashes. (each time with a different client.go:NUMBER)
For the below example, it took four attempts to upload the entire file.

% ipfs add Debian/debian-9.1.0-amd64-netinst.iso -w
 32.00 MB / 290.00 MB [======>-----------------------------------------------------]  11.03% 2s10:06:34.852 ERROR commands/h: open /home/matt/.ipfs/blocks/ZI/put-667476165: too many open files client.go:247

% uname -a
Linux ipfs 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux

**Comment by Kubuxu** [comment] 2017-07-27 15:18
Duplicate of: https://github.com/ipfs/go-ipfs/issues/3792

**Closed** 2017-07-27 19:58 UTC
