### ISSUE TITLE
Extra newline at end of "dag get" result

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ipfs#3503] opened 2016-12-13 23:24 UTC
#### Version information:
go-ipfs version: 0.4.5-dev-4cb236c
Repo version: 4
System version: amd64/linux
Golang version: go1.7.1

#### Type:
Bug

#### Priority:
P1 (for me)
#### Description:
Using either the cli or http api the dag get command seems to add an extra newline 0x0A on the end of the raw data.

To reproduce using cli:
```bash
echo '{"data":1234}' | ipfs dag put -f cbor
```
then 
```bash
ipfs dag get zdpuAs3whHmb9T1NkHSLGF45ykcKrEBxSLiEx6YpLzmKbQLEB | wc -c
```
should give 13, but gives 14, and the extra byte on the end is a newline

The same JSON through the http api results in the same extra byte. The JSON is not special, similar JSON with more/different elements does the same.

**Comment by Kubuxu** [comment] 2016-12-14 00:14
JSON isn't a stable format, we have no way of knowing was was the initial format of the json you have passed in.

Also you are passing it in with a new line, but doing `printf "%s" '{"data":1234}'` won't change anything.
The formatting of the output JSON format is arbitrary if you store it as pure data.

**Comment by ianopolous** [comment] 2016-12-14 00:22
_ipfs dag put --help_ says that the default input format is JSON.

**Comment by djdv** [comment] 2016-12-14 02:49
I think Kubuxu is saying that `echo` is outputting your string but also a newline, so what you meant to pass in and what is actually being passing in are different. `printf` will print the string and not add a newline. 
![untitled](https://cloud.githubusercontent.com/assets/13862850/21167895/d3f7ca56-c17d-11e6-8513-b74e123c1a66.png)

**Comment by Kubuxu** [comment] 2016-12-14 07:04
> JSON isn't a stable format, we have no way of knowing was was the initial format of the json you have passed in.

Yes, input format is JSON but storage format is CBOR, which is stable format.
There are infinitely many ways you can store same data in JSON (`{"data":1234}`, `{"data":1234 }`, `{"data": 1234}`, and so on) but from the usability standpoint it is more important that the same information has the same address.

If you want to store the white-space information, use plain `ipfs add` which doesn't interpret data your are passing it.

**Comment by ianopolous** [comment] 2016-12-14 08:38
@djdv I tried the printf suggestion, but, as Jakub predicted, it gives the same result. 

@kubuxu I get that JSON -> CBOR is many to one, and you need some canonical format. What I don't get is why that canonical format has a newline outside a minimal form of the json. As a consumer of the api, even one who is well versed in other aspects of IPFS this is surprising to me. (Also, I originally submitted this after discussing it with @whyrusleeping)

**Comment by whyrusleeping** [comment] 2016-12-15 19:44
Yeah, the primary issue here isnt that the input object differs from the output object, the problem is that theres a newline after the json blob for some reason.

**Comment by jacobheun** [comment] 2020-05-29 17:11
Verified this is still an issue in 0.5

**Comment by lidel** [comment] 2021-07-02 20:31
For the record, this is still an issue in 0.9.0.
Adding to maintenance board.

**Comment by aschmahmann** [comment] 2021-07-09 16:09
This may get resolved in the refactoring of `dag get` to support go-ipld-prime (e.g. https://github.com/ipfs/go-ipfs/pull/8171). For now let's just add a sharness test that expects to fail and we can flip the switch to expecting success in the rewriting PR to see if the issue persists.

**Comment by masih** [comment] 2021-07-20 11:18
> This may get resolved in the refactoring of `dag get` to support go-ipld-prime (e.g. #8171). For now let's just add a sharness test that expects to fail and we can flip the switch to expecting success in the rewriting PR to see if the issue persists.

Implemented here: https://github.com/ipfs/go-ipfs/pull/8280

**Comment by masih** [comment] 2021-07-22 13:32
@aschmahmann I can confirm #7995 fixes this issue.

**Comment by aschmahmann** [comment] 2021-07-22 14:29
Great, we'll close this issue out once it's been incorporated into master.

**Comment by BigLep** [comment] 2021-08-20 15:26
Closing since it's in RC

**Closed by BigLep** 2021-08-20 15:26 UTC
Labels: kind/bug, status/ready, P1
