### ISSUE TITLE
Issue with `block get` and keccak256 - illegal base32 data at input byte X

### ISSUE THREAD

**Issue by XertroV** [ipfs/go-ipfs#4741] opened 2018-02-27 21:12 UTC
#### Version information:
0.4.13

#### Type:
Bug

#### Description:
Using `ipfs block put` and then `ipfs block get` can result in an exception being thrown.

Easy to demo:

```
╰─➤  echo '{"hi": "there"}' | ipfs block put --mhtype keccak-256
cZsyN1Re3C3wayTpNMMAHS8NYLbU7CJABUv63cF4V4yT3b

╰─➤  ipfs block get cZsyN1Re3C3wayTpNMMAHS8NYLbU7CJABUv63cF4V4yT3b
Error: illegal base32 data at input byte 4
```

This doesn't happen with other hashing algs (though sha3-256 doesn't work for a different reason):

```
╰─➤  echo '{"hi": "there"}' | ipfs block put
QmctZwqj5wpathnW2vW1dujTGAEWap4kbuGV9uhWGDTqw3

╰─➤  ipfs block get QmctZwqj5wpathnW2vW1dujTGAEWap4kbuGV9uhWGDTqw3
{"hi": "there"}

╰─➤  echo '{"hi": "there"}' | ipfs block put --mhtype sha3-256
W1ke9EmidoZq1gzEffrPJsCC55iuWijqoXfgaejB1KRv1K

╰─➤  ipfs block get W1ke9EmidoZq1gzEffrPJsCC55iuWijqoXfgaejB1KRv1K
Error: selected encoding not supported
```

It'd be really nice to use `keccak-256` because it's the cheapest on Ethereum.

**Comment by magik6k** [comment] 2018-03-02 11:46
This is caused by `block put` not switching to cidv1 when a custom multihash settings are provided. This is already fixed in https://github.com/ipfs/go-ipfs/pull/4563

**Closed** 2018-03-23 06:03 UTC
