### ISSUE TITLE
BUG: empty responce

### ISSUE THREAD

**Issue by ivan386** [ipfs/go-ipfs#6008] opened 2019-02-20 19:15 UTC
#### Version information:
Version | "0.4.18"
-- | --
Commit | "aefc746f3"
Repo | "7"
System | "amd64/linux"
Golang | "go1.11.5"

#### Description:

This [link](https://ipfs.io/ipfs/uAXAASxJFCjoBcAA2EjAKIhIg-BnibCPDDbicOSNiGB_lIYDbHBAGRwaLnjjbSOE-1ssSCjIwMTkuMDIuMjAKAggBEgdpcGZzLmlvCgIIAQ/ipfs.io) return empty responce
```
https://ipfs.io/ipfs/uAXAASxJFCjoBcAA2EjAKIhIg-BnibCPDDbicOSNiGB_lIYDbHBAGRwaLnjjbSOE-1ssSCjIwMTkuMDIuMjAKAggBEgdpcGZzLmlvCgIIAQ/ipfs.io
```
On other gateway [it works](https://cloudflare-ipfs.com/ipfs/uAXAASxJFCjoBcAA2EjAKIhIg-BnibCPDDbicOSNiGB_lIYDbHBAGRwaLnjjbSOE-1ssSCjIwMTkuMDIuMjAKAggBEgdpcGZzLmlvCgIIAQ/ipfs.io) right

**Comment by Stebalien** [comment] 2019-02-21 04:34
Duplicate of #6007.

**Closed by Stebalien** 2019-02-21 04:34 UTC
