### ISSUE TITLE
infrequent crashes in daemon mode on armv7

### ISSUE THREAD

**Issue by optimusbrine** [ipfs/go-ipfs#1425] opened 2015-06-25 20:29 UTC
I am running ipfs on a raspberry pi 2 and the daemon seems to crash somewhere between 5 mins and 1hour after i start it with `ipfs daemon`.

the kernel version and architecture uname reports is `Linux 3.18.11-v7+ armv7l`

the head of the stack trace is as follow
```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x76dc18dc
...
```
I do not know what of the rest of this is relevant, but here it is https://gist.github.com/optimusbrine/e29ed9360d2eaa81a390

**Comment by chriscool** [comment] 2015-06-26 03:47
The following links look relevant:

https://groups.google.com/forum/#!topic/golang-nuts/8gszDBRZh_4
https://github.com/gocql/gocql/issues/330

It looks like the daemon might be creating too many threads or using too much memory.
`ulimit -u` could help increase the thread limit but it's not really a fix.

**Comment by optimusbrine** [comment] 2015-06-26 13:11
I was able to curtail it to some degree by lowering the default stack size with `ulimit -s` (i think anyhow, the default was 8mb, but 500kb was sufficient).

What structure in the program do all of these threads relate to? I was thinking it might be swarm peers, but on two seperate runs where the peer count plateued around 40, the thread count maxed at 115 and 272 respectively.

It might be more reasonable to be able to limit the amount of these thread related structures instead.

**Comment by jbenet** [comment] 2015-06-26 20:12
> It might be more reasonable to be able to limit the amount of these thread related structures instead.

how do we do this in Go? I think go governs this with its own internal scheduler, but we may be able to tune it.

 cc @whyrusleeping

**Comment by whyrusleeping** [comment] 2015-06-26 20:16
@optimusbrine could you try running the daemon with `IPFS_REUSEPORT=false` ?

**Comment by optimusbrine** [comment] 2015-06-26 20:26
@jbenet I just meant that if the usage of native threads is somehow semantically tied to some data structure, that there be an option provided to limit the usage of that structure. Like if it was tied to peers, an option to let you specify that you only want to connect to N peers at max. It shouldn't need to be go specific unless that relationship cannot be determined.

@whyrusleeping Yes that seems to be keeping the thread count at exactly 10.

**Comment by whyrusleeping** [comment] 2015-06-26 20:36
@optimusbrine okay, so the extra threads are being caused by our poor use of epoll in our reuseport implementation. let me know how things go running it with that env var set like that.

**Comment by jbenet** [comment] 2015-06-26 20:42
@whyrusleeping that reuseport crap keeps on giving! if only we could use the internal runtime scheduler... https://github.com/golang/go/issues/9661 is so annoying.  have better ides on using epoll?

**Comment by whyrusleeping** [comment] 2015-06-26 20:46
kqueue > epoll. all my kernel experience is on freeBSD so i'm not actually that familiar with epoll.

**Comment by optimusbrine** [comment] 2015-06-27 12:45
@whyrusleeping 18 threads at 15 hours up. I think it was at around 16 3 hours in, so it seems pretty stable. Thanks for the help guys.

**Comment by whyrusleeping** [comment] 2015-06-28 22:38
@optimusbrine thanks for the feedback, do let us know if you experience any connectivity issues.

**Comment by bcomnes** [comment] 2015-07-19 21:31
@optimusbrine I'm running into the exact same thing.  Can you clarify what you did to help improve the situation?

**Comment by optimusbrine** [comment] 2015-07-21 06:31
@bcomnes that should be all you need. Running `top`, then showing threads with `Shift+h` should not show any more than about 20 threads being spawned by the ipfs daemon. Before setting the IPFS_REUSEPORT=false it was spawning hundreds.

**Comment by bcomnes** [comment] 2015-07-21 15:24
Worked great!  Thanks for the info.

**Comment by leni536** [comment] 2015-08-10 19:36
I had the same problem on the following system:
```
$ uname -a
Linux debian-eee 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt9-2 (2015-04-13) i686 GNU/Linux
```

Using IPFS_REUSEPORT=false worked fine for me too.

**Comment by whyrusleeping** [comment] 2015-08-10 19:39
@leni536 thanks for the info. what kind of machine was that? and what is your normal file descriptor limit?

I'm glad disabling reuseport allows you to use ipfs, but it also limits the effectiveness of NAT traversal. We should look at fixing our implementation (if anyone knows about epoll stuff, we want your help!)

**Comment by leni536** [comment] 2015-08-10 19:53
Asus Eee PC 2G Surf, I don't know what exact spec you are interested about. It didn't run low on RAM or HDD space.

As for the fd limit:
```
$ ulimit -n
65536
```

Could the full stack trace be useful? It's kind of large.

**Comment by whyrusleeping** [comment] 2015-08-10 19:55
@leni536 if you dont mind putting it in a gist for me, that would be useful. Its strange that you would run into those issues on something with moderately decent specs. perhaps it has to do with the fact that its 32 bit? (the common denominator between the pi and your machine)

**Comment by leni536** [comment] 2015-08-10 20:06
https://leni536.github.com/ipfs.log

**Comment by jbenet** [comment] 2015-08-11 01:31
For reuseport, I wonder if:
- we should fix it in Go
- contribute a patch and try to land it for 1.5/1.6
- build go-ipfs with a patched golang for now until it gets merged.

@Luzifer would you be willing to build in gobuilder with a golang dist of our choosing? we would keep it in a git repo.

**Comment by whyrusleeping** [comment] 2015-08-11 14:12
> build go-ipfs with a patched golang for now until it gets merged

gonna have to say no to this part. We can patch it, but i dont think we should depend on it until it merges. Users already have issues getting the right version of go (package managers shipping old or damaged versions IM LOOKING AT YOU REDHAT. YOU SHOULD FEEL BAD). Adding to that will hurt us I feel.

**Comment by jbenet** [comment] 2015-08-11 16:07
I think it's possible to do it with not too much trouble with a build tag. would drop fd usage lots :smile:

**Closed** 2016-08-26 00:06 UTC
Labels: bug
