### ISSUE TITLE
Strange error trying to run the daemon through supervisord

### ISSUE THREAD

**Issue by darkstar** [ipfs/go-ipfs#861] opened 2015-03-05 23:27 UTC
When I try to run the daemon through supervisord, I keep getting the following error in the log file (stdout/stderr):
```
Use 'ipfs daemon --help' for information about this command
Error: Expected 0 arguments, got 1
```
which is strange as the config file I'm using to launch the daemon contains just the word "daemon" as argument:
```
[program:ipfs]
command=/var/lib/go/bin/ipfs daemon
user=darkstar
redirect_stderr=true
stdout_logfile=/var/log/ipfs-daemon.log
```

I tried tracing the launch with strace and it also shows that only 1 argument is given:
```
darkstar@flonne:/etc/supervisor$ cat /tmp/strace.log |grep daemon
open("/var/log/ipfs-daemon.log", O_WRONLY|O_CREAT|O_APPEND|O_LARGEFILE, 0666) = 9
[pid  9015] execve("/var/lib/go/bin/ipfs", ["/var/lib/go/bin/ipfs", "daemon"], [/* 28 vars */]) = 0
[pid  9015] write(2, "Use 'ipfs daemon --help' for inf"..., 60 <unfinished ...>
[pid  9012] read(7, "Use 'ipfs daemon --help' for inf"..., 131072) = 60
[pid  9012] write(9, "Use 'ipfs daemon --help' for inf"..., 60) = 60
```

Then I modified the file ```github.com/jbenet/go-ipfs/commands/cli/parse.go``` to print the arguments:
```
darkstar@flonne:/var/lib/go/src/github.com/jbenet/go-ipfs$ git diff commands/cli/parse.go
diff --git a/commands/cli/parse.go b/commands/cli/parse.go
index 4981747..7590174 100644
--- a/commands/cli/parse.go
+++ b/commands/cli/parse.go
@@ -171,7 +171,7 @@ func parseArgs(inputs []string, stdin *os.File, argDefs []cmds.Argument, recursi
        // and the last arg definition is not variadic (or there are no definitions), return an error
        notVariadic := len(argDefs) == 0 || !argDefs[len(argDefs)-1].Variadic
        if notVariadic && numInputs > len(argDefs) {
-               return nil, nil, fmt.Errorf("Expected %v arguments, got %v", len(argDefs), numInputs)
+               return nil, nil, fmt.Errorf("Expected %v arguments, got %v: %v", len(argDefs), numInputs, inputs)
        }

        stringArgs := make([]string, 0, numInputs)
```
and recompiled via ```go get github.com/jbenet/go-ipfs/cmd/ipfs``` (note that I don't know any go language, so I don't know if there's a different/better way to just recompile that binary, but this seemed to work) and I got the following in the log file:
```
Use 'ipfs daemon --help' for information about this command
Error: Expected 0 arguments, got 1: []
```

At this point I'm out of ideas what goes wrong where. I know that supervisord launches the binary correctly (as shown by the strace output), however, ipfs seems to insist that there's an extra argument being given.

Any ideas?

**Comment by darkstar** [comment] 2015-03-05 23:28
Oh by the way this is on kubuntu 14.10 with go 1.4.1 from ```ppa:evarlast/golang1.4```

**Comment by whyrusleeping** [comment] 2015-03-06 00:48
@darkstar thanks for reporting this! It looks like an empty string is somehow being passed in as an argument to the command... weird

**Comment by jbenet** [comment] 2015-03-06 00:49
Might be stdin-- our commands lib is overly aggressive on that, and I think treats it as an arg. I'll look at it closer when I'm back to comp.



—

**Comment by whyrusleeping** [comment] 2015-03-06 00:57
@darkstar could you try changing the command to `/var/lib/go/bin/ipfs daemon < /dev/null` ?

**Comment by kkoroviev** [comment] 2015-03-06 01:29
@whyrusleeping

Now it is:

```
Error: Expected 0 arguments, got 3

Use 'ipfs daemon --help' for information about this command
```

Could reproduce it too.

**Comment by kkoroviev** [comment] 2015-03-06 01:52
If I delete [this chunk](https://github.com/jbenet/go-ipfs/blob/master/commands/cli/parse.go#L148), the problem becomes reproducible on terminal as well.

**Comment by whyrusleeping** [comment] 2015-03-06 03:49
very interesting... @mappum I'll buy you coffee if you know whats going on here!

**Comment by kkoroviev** [comment] 2015-03-06 05:04
By the way, this ugly hack:

```
[program:ipfs]
command=/bin/bash -c "/var/lib/go/bin/ipfs daemon < /dev/null"
```

gives you:

```
Initializing daemon...
Error: ipfs not initialized, please run 'ipfs init'
```

That's because we use @mitchellh's `go-homedir` to resolve `~/.go-ipfs/` to an absolute path.

[Here](https://github.com/jbenet/go-ipfs/blob/master/Godeps/_workspace/src/github.com/mitchellh/go-homedir/homedir.go#L57) it assumes that `sh -c 'eval echo ~$USER'` returns the home directory. But if `HOME` and `USER` are unset (our case), `bash` will return an empty string and `dash` gives you a `~`. In Ubuntu `sh` is symlinked to `dash` by default.

So we get `~/.go-ipfs/` when we try to resolve `~/.go-ipfs/`.

**Comment by whyrusleeping** [comment] 2015-03-06 05:23
@kkoroviev Wow! Good analysis. Thanks for the info

**Comment by mitchellh** [comment] 2015-03-06 06:43
@kkoroviev I'm happy to augment the library to return more accurate results! Please let me know a more resilient test.

**Comment by kkoroviev** [comment] 2015-03-07 06:26
@mitchellh

A better way is to parse `/etc/passwd` directly. Not sure about Mac, but on Linux it will definitely work.

Does Go have a function to find out the UID of the current user?

**Comment by darkstar** [comment] 2015-03-07 10:00
Okay, so this here is now a combined workaround which actually works:
```
[program:ipfs]
command=/bin/bash -c "/var/lib/go/bin/ipfs daemon < /dev/null"
environment=HOME="/home/darkstar",USER="darkstar"
user=darkstar
redirect_stderr=true
stdout_logfile=/var/log/ipfs-daemon.log
```

**Comment by chriscool** [comment] 2015-05-22 03:26
I think this issue might have been fixed by merging PR #1263 or PR #1238.
At least on my Linux machine @kkoroviev 's test now passes.
We might want to monitor if it is passing on CI machines too and then turn the `test_expect_failure` into `test_expect_success`.

**Comment by cryptix** [comment] 2015-05-29 12:30
@chriscool: The stdin test now passes on my box too.

I pushed a PR that switches them back to success and also improves error detection in t0060. ( #1297 )

**Comment by chriscool** [comment] 2015-05-29 20:41
Ok, great! I am closing this issue then.

**Closed by chriscool** 2015-05-29 20:41 UTC
Labels: bug, commands
