### ISSUE TITLE
"ipfs dag get" does not have CBOR output; hence data roundtrip is not guaranteed as JSON mangles data stored by application

### ISSUE THREAD

**Issue by AndreaCensi** [ipfs/go-ipfs#6239] opened 2019-04-20 16:23 UTC
#### Version information:

```
go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/darwin
Golang version: go1.10.3
```

#### Type:

enhancement / bug

#### Description:

It seems that at this time there is no way to retrieve a dag in CBOR format.

Source: https://gowalker.org/github.com/ipfs/go-ipfs/core/commands/dag

`dag put` allows the input to be CBOR

`dag get` does not have the option to have the output in CBOR.

This feature is important because, as previously concluded elsewhere (https://github.com/ipld/ipld/issues/65), JSON is not a robust format for data transfer, so applications that want to preserve data integrity should use CBOR. 

This counts as a bug if we want it to be true that "an application can put a CBOR file, get a hash, and retrieve exactly the same file with that hash".

**Comment by Stebalien** [comment] 2019-04-22 22:14
Unfortunately, this is an annoying limitation of the dag API because it tries to convert formats. Personally, I recommend using the `ipfs block` API for this reason.

**Comment by Stebalien** [comment] 2019-04-23 02:12
(closing as a duplicate of https://github.com/ipfs/go-ipfs/issues/4313)

**Closed by Stebalien** 2019-04-23 02:12 UTC
Labels: bug
