### ISSUE TITLE
Many are not loading for me

### ISSUE THREAD

**Issue by tiotrom** [ipfs/go-ipfs#6055] opened 2019-03-05 23:17 UTC
I am getting "504 Gateway Time-out" for many links. Say this one, created by me https://ipfs.io/ipfs/QmcaDe1RhyZtEAy8Z7ee8vN5AnQXB6mdpnvmDVCRqJT76q does not load for me.  But this one created by a friend loads https://ipfs.io/ipfs/QmRthwbSiaecPnZunAQNZr5wzuHogmfGraVEbeqimTeQaW - I am wondering why. I am trying this for the past 2 days. He can load far more links than me, and I cna definitely load his...

I am in Europe he is in Canada. Any advice? Anything I can send you guys to try and figure this out? I did not do any custom config to it.

**Comment by Stebalien** [comment] 2019-03-06 00:37
By "created" I assume you mean that you added the file to a local IPFS node on _your_ computer and then tried to access it via the gateway?

This is likely because the gateway can't connect to your computer. We're working on improving NAT traversal but it will take some time. Your friend is probably behind a NAT that's easier to traverse. For now, your best bet is to try to manually configure your router to port-forward port 4001.

Alternatively, you can also try the _highly experimental_ AutoRelay feature by running `ipfs config --json Swarm.EnableAutoRelay` and restarting your node (it may take you a few minutes for this feature to start working.

Note: We also had some trouble with our gateways over the weekend. However, we believe those issues have been fixed.

**Comment by tiotrom** [comment] 2019-03-06 01:40
> By "created" I assume you mean that you added the file to a local IPFS node on your computer and then tried to access it via the gateway?
Yes indeed.

OK I will try to forward the router port thank you. Until I can do that I tried `ipfs config --json Swarm.EnableAutoRelay`  and I get ```
[tio@tio-pc ~]$ ipfs config --json Swarm.EnableAutoRelay
Error: failed to get config value: "Swarm key has no attributes"

```

**Comment by Stebalien** [comment] 2019-03-06 04:04
Sorry, `ipfs config --json Swarm.EnableAutoRelay true`.

**Comment by tiotrom** [comment] 2019-03-06 12:18
I get the same exact error

```
[tio@tio-pc ~]$ ipfs config --json Swarm.EnableAutoRelay true
Error: failed to get config value: "Swarm key has no attributes"
```

**Comment by lordcirth** [comment] 2019-03-08 00:22
What go-ipfs version? You need 4.19 to use AutoRelay.

**Comment by Stebalien** [comment] 2019-03-08 05:15
@tiotrom that looks like a bug in the config command.

**Comment by tiotrom** [comment] 2019-03-09 18:00
I am using 0.4.18-2 - will test the latest version when Manjaro updates their repositories. I'll try to get back to this. Thank you!

**Comment by dkasak** [comment] 2019-03-31 21:25
I've recently tried using IPFS again after a hiatus and I'm encountering a similar problem. Port 4001 is forwarded on my router (I confirmed this with a scan from the outside), but the ipfs.io gateway still sometimes times out with 504 after 5 or more minutes of not being able to connect.

This happens only sporadically. When it's working, I can have it resolve many files in succession, but when it stops working it can take half an hour or more for it to start working again.

I haven't been able to figure out what the cause might be. Is there a document somewhere that describes how to debug this kind of issues?

**Comment by Stebalien** [comment] 2019-04-25 23:25
This is probably an issue with:

1. The gateway being overloaded making it time out before it even gets to your request.
2. The DHT being slow making it hard to find providers for content. We're working on this but progress has been very slow.

I'm going to close this issue as there isn't really anything actionable here.

**Closed by Stebalien** 2019-04-25 23:25 UTC
Labels: question
