### ISSUE TITLE
http api/v0/dns says "not a valid domain name", anything else works fine

### ISSUE THREAD

**Issue by etam** [ipfs/go-ipfs#5585] opened 2018-10-11 08:26 UTC
#### Version information:
go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/linux
Golang version: go1.10.3

#### Type:
Bug

#### Description:
I set up my website, registered domain `etam-software.eu` and published dnslink TXT record. Accessing through http://127.0.0.1:8080/ipns/etam-software.eu/ works fine, but ipfs-companion firefox addon is not redirecting to my gateway. I found that http api/v0/dns, which is used by addon, returns error, even though everything else works fine:

```
$ dig +noall +answer TXT etam-software.eu
etam-software.eu.       221     IN      TXT     "dnslink=/ipns/QmanzJhzCXAgry6rT7uyhwdwk9HTDSzVZ4R4mgcBy1nd1j"
$ ipfs name resolve -r etam-software.eu
/ipfs/QmZY4bqaNB8yQUFeVS87QEuNKyTLkfT5eZ1QWwoeozu8xG
$ curl http://127.0.0.1:5001/api/v0/dns/etam-software.eu?r=true
{"Message":"not a valid domain name","Code":0,"Type":"error"}
```

**Comment by lidel** [comment] 2018-10-11 08:36
Looks like a bug in `dns` command:

```console
$ ipfs dns -r etam-software.eu
Error: not a valid domain name

$ dig +short TXT etam-software.eu
"keybase-site-verification=cyjmMyLHiHvrzT2UvcaUmMcF5FhS7Qk47QbTuhHbfMo"
"dnslink=/ipns/QmanzJhzCXAgry6rT7uyhwdwk9HTDSzVZ4R4mgcBy1nd1j"
```

**Comment by overbool** [comment] 2018-10-11 11:30
@etam As the documentation and code explains: `ipfs dns` can't resolve `ipns/Qm....`.

`ipfs dns` can resolve `ipns/ipfs.io`

**Comment by Stebalien** [comment] 2018-10-23 03:11
Yes. Basically, the `ipfs dns` command can resolve dnslink names *only*. If you want general-purpose name resolution, use the `ipfs name resolve -r` command.

However, this *should* be documented. Would someone like to add a note to the help text along the lines of:

> Note: This command can only recursively resolve *DNS* links, it will fail to recursively resolve through IPNS keys etc. For general-purpose recursive resolution, use `ipfs name resolve -r`.

**Comment by etam** [comment] 2018-10-23 06:55
@overbool 

My main issue is that IPFS Companion is not redirecting from my website to IPFS gateway.

Now, the questions are:
- Is my setup wrong? (I think it's not, but maybe I'm wrong)
- Is there a bug in IPFS? (I thought it is, and @lidel agreed)
- Or, if I correctly understand what you're saying, IPFS Companion is using wrong RPC method?

**Comment by Stebalien** [comment] 2018-10-23 13:29
@lidel I believe this is a bug in companion. We *could* fix it here by making `ipfs dns -r` recurse through IPNS keys but that may have performance implications for some applications.

On the other hand, we *may* want to just stop at the first non-IPNS key.

---

I've merged the doc fix for now as that's strictly better than simply not working but we may want a better fix.

**Comment by lidel** [comment] 2018-10-23 15:49
@Stebalien  I agree, we can switch Companion to use `ipfs name resolve -r` to traverse IPNS, however we still need to fix basic `ipfs dns` (without `-r`) to work and tell us if DNSLink exists or not.

And from what I see it does not  work for `etam-software.eu` right now:

```console
$ ipfs dns -r etam-software.eu
Error: not a valid domain name

$ ipfs dns etam-software.eu
Error: could not resolve name (recursion limit exceeded)

$ dig +short TXT etam-software.eu
"keybase-site-verification=cyjmMyLHiHvrzT2UvcaUmMcF5FhS7Qk47QbTuhHbfMo"
"dnslink=/ipns/QmanzJhzCXAgry6rT7uyhwdwk9HTDSzVZ4R4mgcBy1nd1j"
```

What is worse, lookup for `ipfs.io` works only WITH `-r` and fails without it:

```console
$ ipfs dns ipfs.io
Error: could not resolve name (recursion limit exceeded)

$ ipfs dns -r ipfs.io                                                                                                                                                                                                   /ipfs/QmS4fTD7Rh8NouNhp9uZbawUdBpgHaUTeL3EnxX8Tiiu7H

$ dig +short TXT ipfs.io
"dnslink=/ipns/website.ipfs.io"
"v=spf1 a include:_spf.google.com ~all"
```

Just to be sure its not me, are you able to reproduce above errors?

Would it be possible to fix `ipfs dns` (without `-r`) to return dnslink as-is?

I think this would be the expected behavior:
```console
$ ipfs dns ipfs.io
/ipns/website.ipfs.io

$ ipfs dns etam-software.eu
/ipns/QmanzJhzCXAgry6rT7uyhwdwk9HTDSzVZ4R4mgcBy1nd1j
```

**Comment by Stebalien** [comment] 2018-10-23 18:13
How about: https://github.com/ipfs/go-ipfs/issues/5635

**Closed** 2019-03-19 16:14 UTC
Labels: difficulty:easy, documentation, help wanted, in progress

**Comment by lidel** [comment] 2020-12-04 22:31
https://github.com/ipfs/go-ipfs/issues/5585#issuecomment-432304451 continued in https://github.com/ipfs/go-ipfs/issues/6454
