### ISSUE TITLE
Can't pin but I can see object

### ISSUE THREAD

**Issue by yangwao** [ipfs/go-ipfs#2388] opened 2016-02-22 12:35 UTC
Idk if it's 0.4.0 upcoming release related, but here is pastebin 
https://ipfs.io/ipfs/QmREhQoprhJwSM2gtgMMbDDn1k5yq1a3oYCfqWeBqzJH1k/paste

I can do 

root@markone:~# ipfs object stat Qme1cJCtfWN2m4ZRvRqe6bnD7unrjFznpVYbYvLwTDoXUF
NumLinks: 6
BlockSize: 322
LinksSize: 320
DataSize: 2
CumulativeSize: 16603890

but I could not 
root@markone:~# ipfs pin add Qme1cJCtfWN2m4ZRvRqe6bnD7unrjFznpVYbYvLwTDoXUF

both host are online, but previously been in one network. But later been also restarted. Any idea?

**Comment by jbenet** [comment] 2016-02-22 12:36
@yangwao if you can repro a test with sharness, that's even better.

**Comment by yangwao** [comment] 2016-02-28 08:05
@jbenet what is sharness?

**Comment by dignifiedquire** [comment] 2016-02-28 11:23
@yangwao he means a test that can be added to the repo reproducing this issue

**Comment by yangwao** [comment] 2016-02-28 11:27
No idea how to do it, where I can see some manual? 
I think I found some network glitch, can't reproduce now. And very likely can be related to #2413 :)

**Comment by RichardLitt** [comment] 2016-02-29 14:05
Subscribing. I also would like to know more about sharness testing.

**Comment by yangwao** [comment] 2016-02-29 16:01
Another case. Same scenario. I've canceled pinning after half-hour.
```
root@markone:~# ipfs pin add QmQ9UzmQGZVL9JzbUoNYp7hVVQcruuwSgH4Amok2yYLXoY
^C
Error: request canceled
root@markone:~# ipfs object stat QmQ9UzmQGZVL9JzbUoNYp7hVVQcruuwSgH4Amok2yYLXoY
NumLinks: 12
BlockSize: 599
LinksSize: 597
DataSize: 2
CumulativeSize: 18402013
root@markone:~# ipfs object links QmQ9UzmQGZVL9JzbUoNYp7hVVQcruuwSgH4Amok2yYLXoY
QmRwaLviHANz1fAjPsKwfjPgTodFmd4kgHr7fDDAyvb14K 3267     404.html
Qmbah8citaTkhkDx4w9SM13HFJiCF4uEj3hiqRqoKo6qKc 41590    css
QmS4prQ7xh3wZwcrdV8WxzeXEoqaCitkW1CAyzF5J49aTk 192430   fonts
QmZ6igQDpcqMSgLoERyDnLRms7TF2gzexzfJ3fhFLJLLcq 886791   images
QmShxggBkRR8BkPqH7sZQ9Z2ddWpbKiXPb2N9nwQHsubuZ 16983445 img
QmeCo2HBAY4jHfrGN8xoiuFdaUxmVrptyU52uSVQPLhqoR 20205    index.html
QmTE5t7VAzYNKKaJns39ak7XzqYMVMxR9cKBKdbmHxDLcj 24107    index.xml
QmTX8TehtAZfMkNZdjSagYtssnms58xCqsuvurnWkyCnh6 91622    js
QmVc2zUcSULdhEAJ2iKQ7ZDtw6svPpMJt4Vt3siELpiyV7 305      page
QmQphFtvz4izn6avH3Gzy3H4BTZEyHL3JKf8DbivUraTMr 66874    post
Qmau2Uf7xtFuTwv9SbZSokuv4Y6HvTyGH5T195W2Bk3xPa 362      sitemap.xml
QmP72jKYVns9SCFoYhm4Ls7aAKtr4r8fAgp7i5byoA4DEL 90416    tags
root@markone:~# ipfs get QmeCo2HBAY4jHfrGN8xoiuFdaUxmVrptyU52uSVQPLhqoR
Saving file(s) to QmeCo2HBAY4jHfrGN8xoiuFdaUxmVrptyU52uSVQPLhqoR
21.50 KB 0
root@markone:~# ipfs id
{
	"ID": "QmbM5BFMH1X1DLN7anKQHE3p7hWC56e5S1dx96kXfLCpaw",
	"PublicKey": "CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCWcdLGUPIuA1gajxFnv62gH53Y9nwCzYm8TO/f4awNi9c9A6Oxh60o9nyxdRizHZOgr2qMnN5sWy49kbAI4A49XIjhjNgVhonLW+JeDLSFn8NOINYgZyTbEcMa8sEcsDrtRKR2N7IFfyhi8dPsGzz+EyPFAwBDfSHEyzTqC92uev8lXDpxtowImFU2KIN1WpGV//us46Udnj7a4ng1pi2ihenchCthUaMLF15BnaKRza4apowQfw1KIKDhaeBhqJ9Mh54iVezBfEEwsBwglVjd+lgfJ/Wbo2PQStet2n0PE6it8gfzsJ72KpOE2eqSawal9WfNsvKmYoVOFKAq0HgbAgMBAAE=",
	"Addresses": [
		"/ip4/127.0.0.1/tcp/4001/ipfs/QmbM5BFMH1X1DLN7anKQHE3p7hWC56e5S1dx96kXfLCpaw",
		"/ip4/192.168.13.215/tcp/4001/ipfs/QmbM5BFMH1X1DLN7anKQHE3p7hWC56e5S1dx96kXfLCpaw",
		"/ip6/::1/tcp/4001/ipfs/QmbM5BFMH1X1DLN7anKQHE3p7hWC56e5S1dx96kXfLCpaw"
	],
	"AgentVersion": "go-libp2p/0.1.0",
	"ProtocolVersion": "ipfs/0.1.0"
}
```

**Comment by whyrusleeping** [comment] 2016-08-23 20:46
@yangwao is this still an issue? A lot has been improved since this was reported

**Comment by Stebalien** [comment] 2017-12-05 04:58
In an effort to clean up the issue tracker a bit, I'm going to assume this has been fixed and close it (we've fixed a lot of bugs that could have caused this). If not, please reopen.

**Closed by Stebalien** 2017-12-05 04:58 UTC
Labels: verify
