### ISSUE TITLE
ipfs get --nocopy

### ISSUE THREAD

**Issue by ivan386** [ipfs/go-ipfs#6687] opened 2019-09-29 11:50 UTC
```ipfs get --nocopy```

This will replace:
```
ipfs get -o=file_name cid
ipfs repo gc
ipfs add --nocopy file_name
```

With that option file will be fetched and it raw leaves will be sored in filestore as links to parts of file that will be writen by get.

This commad must use split by block sizes to produce same CID as in original link.

**Comment by foxcpp** [comment] 2020-06-22 16:59
Wouldn't `ipfs pin add -r` basically do it? Getting file DAG into local filestore as is without writing out a copy into file system?

**Comment by jl452** [comment] 2020-06-22 18:03
@foxcpp how i can use this file?

> ipfs pin add <ipfs-path>... - Pin objects to local storage.
> Stores an IPFS object(s) from a given path locally to disk.

where is file name for use it not in ipfs?

and second: "ipfs add" can use --chunker and hash will be not same, when i download this file!

**Comment by ivan386** [comment] 2020-06-22 20:26
@foxcpp  ```ipfs get --nocopy``` must write file in to file system without copy in blockstore and add link to it in filestore.

**Comment by Artoria2e5** [comment] 2020-07-22 07:41
For a get from filestore in the case of files sharing identical blocks, FICLONERANGE (Linux) or FSCTL_DUPLICATE_EXTENTS_TO_FILE (Windows) should be used to reduce the amount of disk traffic.

**Comment by aschmahmann** [comment] 2020-07-23 15:12
This looks like a duplicate of #3981, if it's not feel free to reopen.

**Closed by aschmahmann** 2020-07-23 15:12 UTC
Labels: kind/feature
