### ISSUE TITLE
applying 9-to-10 repo migration failed in ipfs

### ISSUE THREAD

**Issue by pontiyaraja** [ipfs/go-ipfs#7676] opened 2020-09-16 09:50 UTC
#### Description:

Initializing daemon...
go-ipfs version: 0.6.0-53971d664
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.4
Found outdated fs-repo, migrations need to be run.
Run migrations now? [y/N] y
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
  => Running: /var/folders/yl/5sr1t26d27ddbrx5mcfqr48r0000gn/T/go-ipfs-migrate437691780/fs-repo-migrations -to 10 -y
Found fs-repo version 7 at /Users/pandiyarajaramamoorthy/.ipfs
===> Running migration 7 to 8...
applying 7-to-8 repo migration
locking repo at "/Users/pandiyarajaramamoorthy/.ipfs"
  - verifying version is '7'
> Upgrading config to new format
Bootstrap field missing or of the wrong type
Nothing to migrate
updated version file
===> Migration 7 to 8 succeeded!
===> Running migration 8 to 9...
applying 8-to-9 repo migration
updated version file
===> Migration 8 to 9 succeeded!
===> Running migration 9 to 10...
applying 9-to-10 repo migration
locking repo at "/Users/pandiyarajaramamoorthy/.ipfs"
  - verifying version is '9'
> Upgrading config to new format
ipfs migration:  migration 9 to 10 failed: unexpected end of JSON input
  => Failed: /var/folders/yl/5sr1t26d27ddbrx5mcfqr48r0000gn/T/go-ipfs-migrate437691780/fs-repo-migrations -to 10 -y
The migrations of fs-repo failed:
  migration failed: exit status 1
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations

Error: migration failed: exit status 1

@aschmahmann

**Comment by aschmahmann** [comment] 2020-09-16 10:40
@pontiyaraja a few questions:

1) where did you get your version of go-ipfs v0.6.0? That version number/commit hash isn't showing up in my git history.
2) do you get the same error if you rerun the daemon?
3) what version of go-ipfs were you running before running the migration?

**Comment by pontiyaraja** [comment] 2020-09-16 15:17
Initializing daemon...
go-ipfs version: 0.8.0-dev-48b2f1273
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4
Found outdated fs-repo, migrations need to be run.
Run migrations now? [y/N] y
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
  => Running: /tmp/go-ipfs-migrate059296063/fs-repo-migrations -to 10 -y
Found fs-repo version 7 at /home/moibit/.ipfs
===> Running migration 7 to 8...
applying 7-to-8 repo migration
locking repo at "/home/moibit/.ipfs"
  - verifying version is '7'
> Upgrading config to new format
Bootstrap field missing or of the wrong type
Nothing to migrate
updated version file
===> Migration 7 to 8 succeeded!
===> Running migration 8 to 9...
applying 8-to-9 repo migration
updated version file
===> Migration 8 to 9 succeeded!
===> Running migration 9 to 10...
applying 9-to-10 repo migration
locking repo at "/home/moibit/.ipfs"
  - verifying version is '9'
> Upgrading config to new format
ipfs migration:  migration 9 to 10 failed: unexpected end of JSON input
  => Failed: /tmp/go-ipfs-migrate059296063/fs-repo-migrations -to 10 -y
The migrations of fs-repo failed:
  migration failed: exit status 1
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations

Error: migration failed: exit status 1

**Comment by pontiyaraja** [comment] 2020-09-16 15:22
@aschmahmann 

where did you get your version of go-ipfs v0.6.0? That version number/commit hash isn't showing up in my git history. - **master branch**
do you get the same error if you rerun the daemon?  -- **yes**
what version of go-ipfs were you running before running the migration? - 0.4.0
what does your config file currently look like? (remember to not include your private key when posting) 

```
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Announce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ]
  },
  "Bootstrap": null,
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Experimental": {
    "FilestoreEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "PreferTLS": false,
    "QUIC": false,
    "ShardingEnabled": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoFetch": false,
    "PathPrefixes": [],
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "my peer id",
    "PrivKey": "my key"
  },
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": "",
    "StrictSignatureVerification": false
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "dht"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "DisableRelay": false,
    "EnableAutoNATService": false,
    "EnableAutoRelay": false,
    "EnableRelayHop": false
  }
}
```

**Comment by pontiyaraja** [comment] 2020-09-16 15:27
@aschmahmann 

its returning error if I try to run any ipfs common after that

**`Error: error loading plugins: failure to decode config: EOF`**

**Comment by aschmahmann** [comment] 2020-09-17 06:37
@pontiyaraja it looks like the cause of the issue is that you have `null` instead of `[]` for Bootstrap. I did an upgrade from v0.4.0 to v0.6.0 using your config and it failed, but making Bootstrap `[]` made it succeed.

-------

### What went wrong:

I'm not sure whether `null` used to be valid in go-ipfs v0.4.0, if so it probably means there's just a corner case missing in one of the migrations between versions 3 and 8.

> its returning error if I try to run any ipfs common after that
>
> Error: error loading plugins: failure to decode config: EOF

For some reason the 7 to 8 migration will just overwrite your config file with an empty file if the config is invalid and it'll say that the conversion was successful instead of failing. Since the 9 to 10 conversion modifies the config file it's the one throwing errors, but that's just a symptom not the problem.

i.e. the below sequence of events you reported is problematic since apparently "Bootstrap field missing or of the wrong type" is enough to corrupt the config file and yet we succeed instead of failing.

```
Upgrading config to new format
Bootstrap field missing or of the wrong type
Nothing to migrate
updated version file
===> Migration 7 to 8 succeeded!
```

@hsanjuan it looks like when we allowed this behavior in https://github.com/ipfs/fs-repo-migrations/pull/97 things broke by returning `nil` because then we don't write anything to the output file. Any problem with just doing `out.Write(data); return nil` instead?

**Comment by hsanjuan** [comment] 2020-09-17 16:53
> @hsanjuan it looks like when we allowed this behavior in ipfs/fs-repo-migrations#97 things broke by returning nil because then we don't write anything to the output file. Any problem with just doing out.Write(data); return nil instead?

Hmm, I guess that works. Sorry!

**Comment by aschmahmann** [comment] 2020-09-17 17:27
> Hmm, I guess that works. Sorry!

Lol, no worries. Just wanted to check before I went around changing things

**Comment by pontiyaraja** [comment] 2020-09-18 02:56
> @pontiyaraja it looks like the cause of the issue is that you have `null` instead of `[]` for Bootstrap. I did an upgrade from v0.4.0 to v0.6.0 using your config and it failed, but making Bootstrap `[]` made it succeed.
> 
> ### What went wrong:
> I'm not sure whether `null` used to be valid in go-ipfs v0.4.0, if so it probably means there's just a corner case missing in one of the migrations between versions 3 and 8.
> 
> > its returning error if I try to run any ipfs common after that
> > Error: error loading plugins: failure to decode config: EOF
> 
> For some reason the 7 to 8 migration will just overwrite your config file with an empty file if the config is invalid and it'll say that the conversion was successful instead of failing. Since the 9 to 10 conversion modifies the config file it's the one throwing errors, but that's just a symptom not the problem.
> 
> i.e. the below sequence of events you reported is problematic since apparently "Bootstrap field missing or of the wrong type" is enough to corrupt the config file and yet we succeed instead of failing.
> 
> ```
> Upgrading config to new format
> Bootstrap field missing or of the wrong type
> Nothing to migrate
> updated version file
> ===> Migration 7 to 8 succeeded!
> ```
> 
> ### Preventing this for other users:
> @hsanjuan it looks like when we allowed this behavior in [ipfs/fs-repo-migrations#97](https://github.com/ipfs/fs-repo-migrations/pull/97) things broke by returning `nil` because then we don't write anything to the output file. Any problem with just doing `out.Write(data); return nil` instead?

@aschmahmann @hsanjuan  we are running a private Ipfs storage platform https://www.moibit.io, we don't share blocks to public nodes. We need migration without bootstrap nodes.

**Comment by aschmahmann** [comment] 2020-09-18 05:46
@pontiyaraja 

> you have null instead of [] for Bootstrap

Just use an empty list

**Comment by pontiyaraja** [comment] 2020-09-20 12:31
> @pontiyaraja
> 
> > you have null instead of [] for Bootstrap
> 
> Just use an empty list instead of null and you'll be fine

@aschmahmann 
I don't think its a valid response. I will be updating 40 Kubernetes Pod's images, by rolling update. I don't want to do it manually.  I think it should be fixed from IPFS-migration side.

**Comment by aschmahmann** [comment] 2020-10-16 17:28
Closed by https://github.com/ipfs/fs-repo-migrations/pull/108

**Closed by aschmahmann** 2020-10-16 17:28 UTC
Labels: kind/bug, need/triage
