### ISSUE TITLE
pinning stalls

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/go-ipfs#7442] opened 2020-06-08 15:15 UTC
#### Version information:
go-ipfs version: 0.6.0-dev
Repo version: 9
System version: amd64/linux
Golang version: go1.14.3

Commit 44df41cb08bd2d1cbce72584010926d68d6864a9

#### Description:
I tried to pin `/ipfs/QmXQ9wz4VYCRpdXMiHQA6smzBJtoQAPwDe8bt9AeKLXeQc` which is the folder with the binaries for go-ipfs 0.5.1.

It stalled twice on the same machine.

The "OverrideSecurityTransports" is on with "noise", "tls", "secio" priority. All other experimental options are deactivated. Routing type is dhtclient to conserve some memory on the 2GB machine.

I killed the IPFS daemon with sigabrt, here's the stack trace:

[kill_ipfs_daemon_on_pin_stall.txt](https://github.com/ipfs/go-ipfs/files/4746834/kill_ipfs_daemon_on_pin_stall.txt)

@Stebalien we discussed this shorty on the chat.

**Comment by Stebalien** [comment] 2020-06-08 16:01
Unfortunately, stalled isn't enough information to diagnose this. I'm not even sure if this is a regression or an older bug.

I've recently fixed https://github.com/libp2p/go-libp2p-peerstore/pull/155 (regression since 0.5.0) which may have caused this by preventing reconnects from working properly in some cases. 

We've also fixed https://github.com/ipfs/go-bitswap/pull/405 which could have maybe triggered this? But we haven't dug into that enough.

**Comment by Stebalien** [comment] 2020-06-08 19:57
Ok, we've reproduced it.

**Comment by Stebalien** [comment] 2020-06-09 01:45
The problem appeared to go away when using the latest bitswap release (only present in the release-v0.6.0 branch, not on master). That included https://github.com/ipfs/go-bitswap/pull/405. Any chance you could try to confirm?

**Comment by RubenKelevra** [comment] 2020-06-09 21:17
I can confirm that 9467986a1d50f1387d64a3f95c2af1712dd47e88 is not affected. :)

**Comment by RubenKelevra** [comment] 2020-06-10 10:53
@Stebalien I did a git bisect, to make find the exact commit which fixed this issue. It appears to be a2cd58edf19f04c9554c271124462db701035a3a. The log is attached. :)

[go-ipfs_issues_7442_bisect_log.txt](https://github.com/ipfs/go-ipfs/files/4757969/go-ipfs_issues_7442_bisect_log.txt)

**Comment by Stebalien** [comment] 2020-06-12 02:40
We'll merge the release branch back into master when we cut the final release. That will include the fix.

**Comment by jacobheun** [comment] 2020-07-09 09:52
@RubenKelevra can you verify this is fixed in master? The release branch was merged into master so this should no longer be an issue.

**Comment by RubenKelevra** [comment] 2020-07-09 12:30
Yes, that's fixed since the 0.6 release.

I thought the ticket would autoclose on release :)

**Closed** 2020-07-09 12:30 UTC
Labels: P0, kind/bug
