### ISSUE TITLE
Create Brew Formula and tap

### ISSUE THREAD

**Issue by ChristopherA** [ipfs/go-ipfs#1144] opened 2015-04-27 20:04 UTC
The most popular package system for OS X is [Homebrew](http://brew.sh).

I highly recommend that you create a `brew` formula/recipe for IPFS as per https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md and register it with brew or one of the [taps](https://github.com/Homebrew?query=). Then you can install a binary file and have `go` and `git` as dependencies, and if someone is using a non-supported Mac OS version or GO version it will compile them instead.

With this formula everything can be installed by:

* `brew tap ipfs/ipfs` (required until you are approved to be in the master index)
* `brew install ipfs`

-- Christopher Allen

**Comment by Luzifer** [comment] 2015-04-27 21:25
All following points are regarding the official Homebrew repo:

- Binary distribution is unwanted
- Only stable software is accepted

(Refs: [Acceptable Formulae](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md))

As long as we [set up an own tap](http://formalfriday.club/2015/01/05/creating-your-own-homebrew-tap-and-formula.html) this should be okay and for the users there is only one additional command to add a tap…

**Comment by jbenet** [comment] 2015-04-27 21:33
:+1:  thanks @ChristopherA and @Luzifer 

I had stayed away because i read they did not want alpha things. But if setting up our own tap is fine, let's do that. for repo name in the org, i think `ipfs/brew-tap`. 

we can also have all the other little tools (`multihash`, `multiaddr`, `iptb`, `graphmd`, ...) published on there.

> - Binary distribution is unwanted

hmm it's annoying to force users to compile things... particularly if the deps are non trivial. any idea why this is? is this purely a security concern? or is there something else?

**Comment by cryptix** [comment] 2015-04-27 21:37
> hmm it's annoying to force users to compile things... particularly if the deps are non trivial. any idea why this is? is this purely a security concern? or is there something else?

Never found the official reason - they pre build (I think, their term is bottling) popular packages though. Maybe it's a complication/security/reproducibility thing?

**Comment by Luzifer** [comment] 2015-04-27 21:47
> for repo name in the org, i think ipfs/brew-tap.

After reading the docs I think `ipfs/homebrew-ipfs` or `ipfs/homebrew-tap` would be better. As far as I understood it has to begin with `homebrew-`…

**Comment by ChristopherA** [comment] 2015-04-27 22:03
As I understand it if you do your own tap, you can do binary, and you can set some dependencies so if there is a new version of OSX released it will compile instead of using binary.

**Comment by jbenet** [comment] 2015-04-27 22:46
> I think `ipfs/homebrew-ipfs` or `ipfs/homebrew-tap` would be better.

:+1: is `ipfs/homebrew-ipfs-tap` overkill? whatever is most clear to users who ever see the repo name only. `ipfs/homebrew-ipfs` may be enough.

---

Okay, let's try their way (compile) for now until we run into issues. once we have our own signed binaries we can revisit the question if relevant. (maybe even provide checksums of binaries to check, if the builds are reproducible, etc).

**Comment by Luzifer** [comment] 2015-07-06 11:58
Someone created a formula and submitted it but:

```
[13:57] luzifer ~> which ipfs
/usr/local/bin/ipfs
[13:57] luzifer ~> ls -lh /usr/local/bin/ipfs
lrwxr-xr-x  1 luzifer  admin    29B  6 Jul 13:56 /usr/local/bin/ipfs -> ../Cellar/ipfs/0.3.5/bin/ipfs
[13:57] luzifer ~> ipfs version
ipfs version 0.3.4
[13:57] luzifer ~>
```

Version 0.3.5 should identify as 0.3.5, not as 0.3.4

**Comment by whyrusleeping** [comment] 2015-07-06 15:10
I think thats our bad, we forgot to change the in code version before bumping the tag number. so it may be building *at* tag 0.3.5

**Comment by jbenet** [comment] 2015-07-07 03:15
@whyrusleeping we should update the tag then? do we know if this is kosher with `brew`?

**Comment by cryptix** [comment] 2015-07-07 13:06
> I think thats our bad, we forgot to change the in code version before bumping the tag number. so it may be building at tag 0.3.5

Yup. that's the case. The version bump in code came some commits after the tag.


@jbenet it [looks like](
https://github.com/Homebrew/homebrew/blob/b5c86745831bfff92fc717446ceddbf13915c442/Library/Formula/ipfs.rb#L8) they track both the revision hash and the tag name. I'm not sure what happens when you reassign the tag but I'd expect an error when they don't match.


Personally, I'd wait for 0.4 before we bump brew again.

**Comment by whyrusleeping** [comment] 2015-07-07 15:39
0.4 is gonna be great.

**Comment by diasdavid** [comment] 2016-01-02 02:36
Let's keep track of this on the distributions repo https://github.com/ipfs/distributions/issues/22

**Closed by diasdavid** 2016-01-02 02:36 UTC
