### ISSUE TITLE
Panic in IpfsDHT

### ISSUE THREAD

**Issue by sidenaio** [ipfs/go-ipfs#7312] opened 2020-05-14 06:18 UTC
#### Version information:
github.com/ipfs/go-ipfs v0.5.1-0.20200506014919-3339ce3b0e95

#### Description:

```
panic: send on closed channel

goroutine 2038717 [running]:
github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).findProvidersAsyncRoutine.func1(0x21ed620, 0xc00b821000, 0xc0002a96e0, 0x22, 0xc00b2507b0, 0xb765d6, 0x1fd1540, 0xc000b141d8, 0x0)
        /home/mikhail/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.7.11/routing.go:582 +0x6d1
github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).runLookupWithFollow
```

**Comment by aschmahmann** [comment] 2020-05-14 09:29
@sidenaio thanks for the bug report. It looks like there's a cleanup issue when the FindProviders lookup is aborted early. Can you give any other context on what you were doing when you encountered the error?

**Comment by sidenaio** [comment] 2020-05-14 09:55
We are using ipfs as a library in [our project](https://github.com/idena-network/idena-go). We ran a test with 1k nodes. One node went down with this panic. We use ipfs for unixfs.add, unixfs.get, pin.add, pin.rm. Before the panic, our log contains read operation from ipfs.

**Comment by Stebalien** [comment] 2020-05-18 07:44
This will happen when the context is canceled. The issue is that we:

1. Run queryFn in a goroutine as the "followup".
2. Abort early of the context is canceled or the "stop" condition is triggered.

Instead, we should just cancel the query and wait till all the query routines return.

https://github.com/libp2p/go-libp2p-kad-dht/blob/08ab423f2fc5f3c3e3e9452fc2358dbc0610d369/query.go#L131

**Comment by Stebalien** [comment] 2020-05-29 23:04
Fixed in https://github.com/ipfs/go-ipfs/pull/7382.

**Closed by Stebalien** 2020-05-29 23:04 UTC
Labels: P0, dif/easy, kind/bug, status/in-progress
