### ISSUE TITLE
Transfer speed on local network is poor

### ISSUE THREAD

**Issue by matthewrobertbell** [ipfs/go-ipfs#2448] opened 2016-03-06 18:34 UTC
Hi,
I tested two laptops on a local wifi network, and attempted transferring a 1GB file between them, using IPFS. The speed tended to vary between 5 - 10mbit, usually closer to the former.

I get much better speeds between the laptops using other protocols, and torrents over wifi from the internet give me the full internet connection line speed of ~40 mbit.

If IPFS not being aggressive enough in the resources / number of connections it uses?

I noticed that the laptops appear to be connected over ipv6 on the local network, could this be an issue?

Thanks for your work.

**Comment by whyrusleeping** [comment] 2016-03-07 18:54
@mattseh i've noticed this myself too. I plan on investigating overall transfer speed soon, and putting up a test in CI that will let us monitor transfer speed over the course of different commits (so we can make sure nothing slows down)

**Comment by mattseh** [comment] 2016-03-07 18:57
An additional observation: I didn't notice CPU hitting 100%+ on either (dual core) laptop.

**Comment by whyrusleeping** [comment] 2016-03-07 18:58
It used to at some point, this is likely a regression. getting a test to verify transfer speed should be the next step here.

**Comment by whyrusleeping** [comment] 2016-03-07 23:43
@mattseh one really random thing you could try for me: could you run both daemons with `IPFS_REUSEPORT` set to `false` ?

**Comment by mattseh** [comment] 2016-03-08 09:15
As an environment variable?

**Comment by lgierth** [comment] 2016-03-08 14:02
Yes as an env variable: `IPFS_REUSEPORT=false ipfs daemon`

**Comment by Stebalien** [comment] 2019-04-30 07:07
Closing due to age. We've fixed several issues that could have been causing this since then (transfer speed is now pretty high on a local network, in my experience).

**Closed by Stebalien** 2019-04-30 07:07 UTC
Labels: bug
