### ISSUE TITLE
ipfs deamon command fail

### ISSUE THREAD

**Issue by yishuiliunian** [ipfs/go-ipfs#4731] opened 2018-02-23 05:55 UTC
the command  failed
~~~
ipfs deamon 
~~~

with log:

~~~
Initializing daemon...
Swarm listening on /ip4/10.66.66.41/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmXYxadGxRcKikecQzsR2V8cukCaebLUWzphjaSXhB3drm
Swarm announcing /ip4/10.66.66.41/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use
~~~

but i check the network port, the 5001 is not used.

~~~
STONEDONG-MB4 :: Application Support/ipfs-desktop/logs % lsof -i tcp:5001
STONEDONG-MB4 :: Application Support/ipfs-desktop/logs %
~~~

**Comment by Mehcta** [comment] 2018-02-23 07:00
Спс а теперь по русски

**Comment by VictorBjelkholm** [comment] 2018-02-23 08:45
@yishuiliunian could you also paste the output of `ipfs version --all`?

@Mehcta Please use english on this issue tracker / Пожалуйста, используйте английский на этом трекер

**Comment by yishuiliunian** [comment] 2018-02-23 09:32
@VictorBjelkholm  

it may the newest
~~~
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/darwin
Golang version: go1.9.2
~~~

**Comment by VictorBjelkholm** [comment] 2018-02-23 09:54
@yishuiliunian thanks. Can you also check with running `lsof` with sudo? Might be some process that is listening that you don't own.

**Comment by tyvdh** [comment] 2018-06-27 16:59
I'm getting this as well.

```
$ sudo lsof -i tcp:5001
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ipfs    2109 root   11u  IPv4  62213      0t0  TCP localhost:5001 (LISTEN)
```

I used `ipfs shutdown` which then returns nothing for `sudo lsof -i tcp:5001` however when I try and start back up the daemon it catches on the port error again.

```
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use
```

**Comment by tyvdh** [comment] 2018-06-27 17:00
ftr I'm using https://dist.ipfs.io/go-ipfs/v0.4.15/go-ipfs_v0.4.15_linux-arm.tar.gz with my Raspberry Pi B+

**Comment by magik6k** [comment] 2018-07-03 17:18
@tyvdh can you try running the daemon with `IPFS_REUSEPORT=false ipfs daemon`? (reboot might be needed)

**Comment by tyvdh** [comment] 2018-07-03 19:13
@magik6k Definitely seems to be working better!

**Comment by Stebalien** [comment] 2018-07-25 04:08
That should have absolutely nothing to do with this issue... Could you try running without the `IPFS_REUSEPORT` again (just to make sure)?

**Comment by singhswg** [comment] 2018-08-01 21:42
@tyvdh  Were you able to resolve this? Apparently `IPFS_REUSEPORT=false ipfs daemon` didnt work for me. And I am doing this on Azure VM. Any pointers?

**Comment by magik6k** [comment] 2018-08-01 22:05
@singhswg what's the exact error message you're getting?

**Comment by singhswg** [comment] 2018-08-01 22:26
@magik6k I am trying to run a IPFS deamon on a Azure VM, and I get this error

`Error: serveHTTPApi: manet.Listen(/ip4/<---IP--->/tcp/5001) failed: listen tcp4 <---IP--->:5001: bind: cannot assign requested address`

Nothing is running on this port, I confirmed doing `lsof -i tcp:5001` as root. I am using a static Azure IP.

**Comment by magik6k** [comment] 2018-08-01 22:39
@singhswg Can you confirm that the address you are trying to assign actually exists on the machine (check `ip addr`)?

Btw, exposing unfiltered :5001 to the internet is probably a bad idea since it's the admin port which allows you to execute every command you can with the `ipfs [...]`

**Comment by singhswg** [comment] 2018-08-01 22:43
@magik6k Yes i am aware but thanks for the heads up!

No I cant see the IP, neither does ping work. I guess maybe it's something with Azure VMs...

**Comment by Stebalien** [comment] 2018-08-02 22:44
Check the `Addresses.API` config option. It looks like your machine's IP may not match it.

I'm going to close this for now as I don't think there's anything we can do on our side. Feel free to ask follow up questions or reopen this issue if you feel otherwise.

**Closed by Stebalien** 2018-08-02 22:44 UTC

**Comment by xianminx** [comment] 2022-10-03 06:26
For reference to anyone coming to the same problem. 

In my case, I have deprecated Cisco Anyconnect installed on my macOS. Just kill the process helps. 
(kindly remind, use `sudo` to run ` lsof -i tcp:5001` as cisco service is running with root privilege. 


```sh
ipfs daemon
Initializing daemon...
go-ipfs version: 0.13.0
Repo version: 12
System version: amd64/darwin
Golang version: go1.18.3
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/192.168.1.190/tcp/4001
Swarm listening on /ip4/192.168.1.190/udp/4001/quic
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/::1/udp/4001/quic
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic
Swarm announcing /ip4/192.168.1.190/tcp/4001
Swarm announcing /ip4/192.168.1.190/udp/4001/quic
Swarm announcing /ip6/::1/tcp/4001
Swarm announcing /ip6/::1/udp/4001/quic

Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use
```
```sh
sudo lsof -i tcp:5001
Password:
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
acwebseca   768  root   45u  IPv4 0xb6d7b0364a5f173b      0t0  TCP localhost:commplex-link (LISTEN)
acwebseca   768  root   47u  IPv6 0xb6d7b0364842cddb      0t0  TCP localhost:commplex-link (LISTEN)
acwebseca   768  root   53u  IPv6 0xb6d7b0364844addb      0t0  TCP localhost:commplex-link->localhost:61506 (ESTABLISHED)
Microsoft 20725 lucas   50u  IPv6 0xb6d7b0364844fadb      0t0  TCP localhost:61506->localhost:commplex-link (ESTABLISHED)
which acwebseca
acwebseca not found
ps aux |grep acwebseca
root               768   0.0  0.0 34209816   6400   ??  S     1Jan22   1:38.45 /opt/cisco/anyconnect/bin/acwebsecagent -console
lucas            34791   0.0  0.0 34122844    872 s001  S+    2:17PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn acwebseca
ps aux |grep acwebseca
root               768   0.0  0.0 34209840   6944   ??  S     1Jan22   1:38.46 /opt/cisco/anyconnect/bin/acwebsecagent -console
lucas            34829   0.0  0.0 34122844    844 s001  R+    2:17PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn acwebseca

```

```sh
sudo kill 768
sudo lsof -i -P  | grep 5001
Microsoft 20725          lucas   50u  IPv6 0xb6d7b0364844fadb      0t0    TCP localhost:61506->localhost:5001 (CLOSE_WAIT)


```
```sh
ipfs daemon
Initializing daemon...
go-ipfs version: 0.13.0
Repo version: 12
System version: amd64/darwin
Golang version: go1.18.3
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/192.168.1.190/tcp/4001
Swarm listening on /ip4/192.168.1.190/udp/4001/quic
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/::1/udp/4001/quic
Swarm listening on /p2p-circuit
Swarm announcing /ip4/111.197.252.95/udp/11005/quic
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic
Swarm announcing /ip4/192.168.1.190/tcp/4001
Swarm announcing /ip4/192.168.1.190/udp/4001/quic
Swarm announcing /ip6/::1/tcp/4001
Swarm announcing /ip6/::1/udp/4001/quic
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

```
