### ISSUE TITLE
Bugs related to codecs that return EOF on encode/decode (EOF error are ignored by CLI so we would need to either fix that or wrap the errors)

### ISSUE THREAD

**Issue by warpfork** [ipfs/go-ipfs#8378] opened 2021-08-24 16:23 UTC

**Comment by warpfork** [comment] 2021-08-24 18:06
@aschmahmann suggested codecs may be returning EOF when they shouldn't?  Or maybe they should be returning UnexpectedEOF rather than EOF in some cases?

I do believe there may be upstream bugs here, but info on which codecs, and what exactly the misbehavior is, would help.

**Comment by warpfork** [comment] 2021-08-24 18:07
Possibly relatedly, I've also recently found at least one bug upstream where a codec returns not _enough_ EOF errors: https://github.com/ipld/go-ipld-prime/issues/230

**Comment by aschmahmann** [comment] 2021-08-25 08:12
A couple of examples of this are:
    - `echo "test" | ipfs dag put --input-enc=git-raw` doesn't error or return a CID
    - `echo "" | ipfs dag put --input-enc=dag-json --format=dag-json`

**Comment by mvdan** [comment] 2021-09-03 12:28
At least on Go 1.17, I can't reproduce the dag-json one:

```
$ go version
go version go1.17 linux/amd64
$ ./cmd/ipfs/ipfs --version
ipfs version 0.9.1
$ printf '' | ./cmd/ipfs/ipfs dag put --input-enc=dag-json --format=dag-json
Error: no input parser for "dag-json"
$ printf '\n' | ./cmd/ipfs/ipfs dag put --input-enc=dag-json --format=dag-json
Error: no input parser for "dag-json"
$ ./cmd/ipfs/ipfs --version
ipfs version 0.11.0-dev
$ printf '' | ./cmd/ipfs/ipfs dag put --input-enc=dag-json --format=dag-json
Error: EOF
$ printf '\n' | ./cmd/ipfs/ipfs dag put --input-enc=dag-json --format=dag-json
Error: EOF
```

And it seems like master (701828d300b465500a1393e036ab28e559f4cf69) errors correctly. Am I missing something?

The git-raw case is the same story; on 0.9.1 it errors with "no input parser", and on master it correctly fails:

```
$ ./cmd/ipfs/ipfs --version
ipfs version 0.11.0-dev
$ echo "test" | ./cmd/ipfs/ipfs dag put --input-enc=git-raw
Error: EOF
```

**Comment by mvdan** [comment] 2021-09-03 12:53
For the sake of completeness, I went through the trouble of installing Go 1.16.7, and it has the same results as Go 1.17 above.

**Comment by aschmahmann** [comment] 2021-09-03 20:03
@mvdan are you running a daemon or just running the ipfs offline? If you run `ipfs daemon` and then those commands you should notice the problems.

To be more precise the EOF errors are ignored by the CLI when it is using the HTTP API behind the scenes (e.g. https://github.com/ipfs/go-ipfs-cmds/blob/4ade007405e5d3befb14184290576c63cc43a6a3/http/responseemitter.go#L175).

So these are both giving you EOFs, but EOF doesn't really indicate an error which is why the HTTP API skips it.

**Comment by mvdan** [comment] 2021-09-03 20:40
Ah, oops. I guess you can file that under "repro steps unclear" :) I wonder why I'm not getting a clear error along the lines of "IPFS daemon not found".

I'll take another look.

**Comment by mvdan** [comment] 2021-09-03 21:50
Thanks, I can reproduce now. TIL that the ipfs CLI can work in "offline mode" as well as "online mode" with a daemon.

I've looked through the code, and I think I agree with Eric. The codec decoder is returning io.EOF when it should be returning io.ErrUnexpectedEOF. The latter is clearly fatal; the former is usually just a "no more input" signal.

It's perhaps wrong for go-ipfs-cmds to ignore io.EOF as a nil error, but changing that will likely break other stuff. Much easier to make the ipld-prime codecs return better errors, which we probably want to do anyway.

**Comment by mvdan** [comment] 2021-09-04 16:42
Alright, the upstream fix for dag-json is https://github.com/ipld/go-ipld-prime/pull/241, and for git-raw it's https://github.com/ipfs/go-ipld-git/pull/53. When those are merged, we should be able to just pull master from both of them and be ready for a release. If we need those to also be releases, we can also do that.

I imagine that regression tests for `ipfs dag put` would be a bit overkill, as I'm already adding tests upstream. But I'm happy to also write some here if necessary.

**Comment by BigLep** [comment] 2021-09-07 18:25
@mvdan: I think once merged, lets bump the version of go-ipld-version that go-ipfs depends on and I think we're good.  @aschmahmann can weight in, but he's out until 2021-09-09.

**Comment by mvdan** [comment] 2021-09-08 09:53
Sounds good @BigLep. Both upstream PRs are merged, and I've filed https://github.com/ipfs/go-ipfs/pull/8417 for updating the dependencies. Should be all good to go, modulo a review and tagging the upstream modules.

**Closed** 2021-09-23 17:01 UTC
