### ISSUE TITLE
go-ipfs "resetting" the network

### ISSUE THREAD

**Issue by Flingafu** [ipfs/go-ipfs#6072] opened 2019-03-11 10:25 UTC
I have been using Orion 1.1.3. Anytime I import or upload locally, regardless of the speed, it will strangle out all my other network connections seemingly at random. In addition to that even just connecting as peers seems to result in some catastrophic failure to the network for about 30 seconds. I have 2 computers setup on the same network and I can ping at about 4 ms. When I went to connect them for the first time, within seconds of connecting as peers I saw all the symptoms of my network going down and was able to repeat the result connecting vise versa. both have just the standard filestore size and the traffic that was happening at the time was negligible. One of the devs working on orion said this sounded potentially like an issue related to ipfs-go and to report it here!

**Comment by tiotrom** [comment] 2019-03-11 20:40
I can confirm on Linux (Manjaro Gnome) using it with Orion appimage. Connection can totally drop for about 30s usually when we establish a connection between us - like I share something with someone else, and he/she accesses it.

**Comment by Stebalien** [comment] 2019-03-11 22:02
Unfortunately, this is a duplicate of https://github.com/ipfs/go-ipfs/issues/3320. We've been chipping away at this problem for years but the only solution at the moment is to get a better router.

**Closed by Stebalien** 2019-03-11 22:02 UTC
Labels: duplicate
