### ISSUE TITLE
Crash under high CLI concurrency

### ISSUE THREAD

**Issue by ribasushi** [ipfs/go-ipfs#8314] opened 2021-07-29 08:56 UTC
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

built from source

### Version

```Text
go-ipfs version: 0.9.1-dc2715af6
Repo version: 11
System version: arm64/linux
Golang version: go1.16.6
```

### Config

```json
N/A
```

### Description

Crash on high CLI concurrency

```
2021-07-29T08:53:30.128Z	ERROR	cmds/http	http/handler.go:94	a panic has occurred in the commands handler!
2021-07-29T08:53:30.128Z	ERROR	cmds/http	http/handler.go:95	runtime error: invalid memory address or nil pointer dereference
2021-07-29T08:53:30.129Z	ERROR	cmds/http	http/handler.go:96	stack trace:
goroutine 6461455 [running]:
runtime/debug.Stack(0x400000ff20, 0x19d4402, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x88
github.com/ipfs/go-ipfs-cmds/http.(*handler).ServeHTTP.func1()
	/srv/cargo/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.6.0/http/handler.go:96 +0x100
panic(0x19d4460, 0x2ad2140)
	/usr/local/go/src/runtime/panic.go:971 +0x424
encoding/json.(*encodeState).marshal.func1(0x4011030f48)
	/usr/local/go/src/encoding/json/encode.go:328 +0x94
panic(0x19d4460, 0x2ad2140)
	/usr/local/go/src/runtime/panic.go:965 +0x154
encoding/json.(*encodeState).marshal.func1(0x4011030d28)
	/usr/local/go/src/encoding/json/encode.go:328 +0x94
panic(0x19d4460, 0x2ad2140)
	/usr/local/go/src/runtime/panic.go:965 +0x154
github.com/libp2p/go-libp2p-core/peer.AddrInfo.MarshalJSON(0x40324cb8c0, 0x26, 0x4018699800, 0xc, 0xc, 0xffff8850ca60, 0x4011030778, 0xbe2ff4, 0x1a440c0, 0x4028d3d5e0)
	/srv/cargo/go/pkg/mod/github.com/libp2p/go-libp2p-core@v0.8.5/peer/addrinfo_serde.go:18 +0x8c
encoding/json.marshalerEncoder(0x4039f48400, 0x1a440c0, 0x4028d3d5e0, 0x196, 0x1a40100)
	/usr/local/go/src/encoding/json/encode.go:479 +0x90
encoding/json.arrayEncoder.encode(0x1e7f4c8, 0x4039f48400, 0x1919b60, 0x402eef2ca8, 0x97, 0xbe0100)
	/usr/local/go/src/encoding/json/encode.go:915 +0xbc
encoding/json.sliceEncoder.encode(0x401bcd1300, 0x4039f48400, 0x1919b60, 0x402eef2ca8, 0x97, 0x401b790100)
	/usr/local/go/src/encoding/json/encode.go:888 +0xc0
encoding/json.(*encodeState).reflectValue(0x4039f48400, 0x1919b60, 0x402eef2ca8, 0x97, 0x402eef0100)
	/usr/local/go/src/encoding/json/encode.go:360 +0x74
encoding/json.interfaceEncoder(0x4039f48400, 0x199cf00, 0x401b79aa20, 0x94, 0x401b790100)
	/usr/local/go/src/encoding/json/encode.go:716 +0x90
encoding/json.mapEncoder.encode(0x1e7f4b8, 0x4039f48400, 0x19c76a0, 0x401c1c1b60, 0x15, 0x100)
	/usr/local/go/src/encoding/json/encode.go:813 +0x2a4
encoding/json.(*encodeState).reflectValue(0x4039f48400, 0x19c76a0, 0x401c1c1b60, 0x15, 0x4011030100)
	/usr/local/go/src/encoding/json/encode.go:360 +0x74
encoding/json.(*encodeState).marshal(0x4039f48400, 0x19c76a0, 0x401c1c1b60, 0x536c0100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:332 +0xf0
encoding/json.Marshal(0x19c76a0, 0x401c1c1b60, 0x1c02f70, 0x5, 0x4039a80ad8, 0x2e, 0x19de200)
	/usr/local/go/src/encoding/json/encode.go:161 +0x48
github.com/libp2p/go-libp2p-core/routing.(*QueryEvent).MarshalJSON(0x401ce179c0, 0x19de200, 0x401ce179c0, 0xfffec0192e28, 0x401ce179c0, 0x401ce17901)
	/srv/cargo/go/pkg/mod/github.com/libp2p/go-libp2p-core@v0.8.5/routing/query_serde.go:10 +0x25c
encoding/json.marshalerEncoder(0x4018d3a680, 0x19de200, 0x401ce179c0, 0x16, 0x2c40100)
	/usr/local/go/src/encoding/json/encode.go:479 +0x90
encoding/json.(*encodeState).reflectValue(0x4018d3a680, 0x19de200, 0x401ce179c0, 0x16, 0x4011030100)
	/usr/local/go/src/encoding/json/encode.go:360 +0x74
encoding/json.(*encodeState).marshal(0x4018d3a680, 0x19de200, 0x401ce179c0, 0x19f0100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:332 +0xf0
encoding/json.(*Encoder).Encode(0x4031712410, 0x19de200, 0x401ce179c0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:206 +0x5c
github.com/ipfs/go-ipfs-cmds/http.(*responseEmitter).Emit(0x40126c9340, 0x19de200, 0x401ce179c0, 0x0, 0x0)
	/srv/cargo/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.6.0/http/responseemitter.go:135 +0x20c
github.com/ipfs/go-ipfs/core/commands.glob..func52(0x40126c91f0, 0x201b938, 0x40126c9340, 0x1ace0c0, 0x40042d2000, 0x0, 0x0)
	/srv/cargo/go-ipfs/core/commands/dht.go:192 +0x214
github.com/ipfs/go-ipfs-cmds.(*Command).call(0x2aeade0, 0x40126c91f0, 0x201b938, 0x40126c9340, 0x1ace0c0, 0x40042d2000, 0x1afaf80, 0x201b938)
	/srv/cargo/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.6.0/command.go:173 +0x1a0
github.com/ipfs/go-ipfs-cmds.(*Command).Call(0x2aeade0, 0x40126c91f0, 0x201b938, 0x40126c9340, 0x1ace0c0, 0x40042d2000)
	/srv/cargo/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.6.0/command.go:143 +0x50
github.com/ipfs/go-ipfs-cmds/http.(*handler).ServeHTTP(0x4004702160, 0xffff88430cd8, 0x40317123c0, 0x4006847100)
	/srv/cargo/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.6.0/http/handler.go:192 +0x644
github.com/ipfs/go-ipfs-cmds/http.prefixHandler.ServeHTTP(0x1c11826, 0x7, 0x1ff4188, 0x4004702160, 0xffff88430cd8, 0x40317123c0, 0x4006847100)
	/srv/cargo/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.6.0/http/apiprefix.go:24 +0x12c
github.com/rs/cors.(*Cors).Handler.func1(0xffff88430cd8, 0x40317123c0, 0x4006847100)
	/srv/cargo/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x19c
net/http.HandlerFunc.ServeHTTP(0x40047021a0, 0xffff88430cd8, 0x40317123c0, 0x4006847100)
	/usr/local/go/src/net/http/server.go:2049 +0x40
net/http.(*ServeMux).ServeHTTP(0x4003d1bd00, 0xffff88430cd8, 0x40317123c0, 0x4006847100)
	/usr/local/go/src/net/http/server.go:2428 +0x190
github.com/ipfs/go-ipfs/core/corehttp.CheckVersionOption.func1.1(0xffff88430cd8, 0x40317123c0, 0x4006847100)
	/srv/cargo/go-ipfs/core/corehttp/commands.go:184 +0x250
net/http.HandlerFunc.ServeHTTP(0x4004702100, 0xffff88430cd8, 0x40317123c0, 0x4006847100)
	/usr/local/go/src/net/http/server.go:2049 +0x40
net/http.(*ServeMux).ServeHTTP(0x4003d1bc40, 0xffff88430cd8, 0x40317123c0, 0x4006847100)
	/usr/local/go/src/net/http/server.go:2428 +0x190
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1(0xffff88430cd8, 0x4031712370, 0x4006847100)
	/srv/cargo/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:198 +0xc4
net/http.HandlerFunc.ServeHTTP(0x4003d769f0, 0xffff88430cd8, 0x4031712370, 0x4006847100)
	/usr/local/go/src/net/http/server.go:2049 +0x40
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func2(0xffff88430cd8, 0x4031712370, 0x4006847100)
	/srv/cargo/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:172 +0x68
net/http.HandlerFunc.ServeHTTP(0x4003d76b10, 0xffff88430cd8, 0x4031712370, 0x4006847100)
	/usr/local/go/src/net/http/server.go:2049 +0x40
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2(0xffff88430cd8, 0x4031712370, 0x4006847100)
	/srv/cargo/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:76 +0x94
net/http.HandlerFunc.ServeHTTP(0x4003d76c30, 0xffff88430cd8, 0x4031712370, 0x4006847100)
	/usr/local/go/src/net/http/server.go:2049 +0x40
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x2014b30, 0x402066b6c0, 0x4006847100)
	/srv/cargo/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:101 +0xbc
net/http.HandlerFunc.ServeHTTP(0x4003d76e10, 0x2014b30, 0x402066b6c0, 0x4006847100)
	/usr/local/go/src/net/http/server.go:2049 +0x40
net/http.(*ServeMux).ServeHTTP(0x4003d1bc00, 0x2014b30, 0x402066b6c0, 0x4006847100)
	/usr/local/go/src/net/http/server.go:2428 +0x190
github.com/ipfs/go-ipfs/core/corehttp.makeHandler.func1(0x2014b30, 0x402066b6c0, 0x4006847100)
	/srv/cargo/go-ipfs/core/corehttp/corehttp.go:54 +0x80
net/http.HandlerFunc.ServeHTTP(0x4003dfe640, 0x2014b30, 0x402066b6c0, 0x4006847100)
	/usr/local/go/src/net/http/server.go:2049 +0x40
net/http.serverHandler.ServeHTTP(0x4003d82700, 0x2014b30, 0x402066b6c0, 0x4006847100)
	/usr/local/go/src/net/http/server.go:2867 +0xbc
net/http.(*conn).serve(0x40346e1360, 0x201b580, 0x401ea58340)
	/usr/local/go/src/net/http/server.go:1932 +0x71c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2993 +0x318

```

**Comment by aschmahmann** [comment] 2021-07-30 15:47
last time we looked at this it was pretty hard to track down, but @ribasushi says he can reproduce this with reasonable frequency. Let's put up a test branch with more debugging output to try to get to the bottom of this.

**Comment by petar** [comment] 2021-08-02 18:42
@ribasushi Use this branch as a first iteration in narrowing down the source of the bug: https://github.com/libp2p/go-libp2p-kad-dht/tree/fix/niladdr

**Comment by BigLep** [comment] 2021-08-03 00:54
I see we have the branch for helping debug - cool.

If others already know, but it would help me understand the usecase.  I certainly want to get this fixed, but want to make sure we have the priority right.

**Comment by ribasushi** [comment] 2021-08-03 06:23
@BigLep this is currently a major inconvenience bordering on a  blocker for the operation of web.3storage and nft.sorage.

**Comment by Jorropo** [comment] 2021-08-03 06:28
@ribasushi that sounds like a classical race condition nil deref.

Can you maybe try making a `-race` binary and see if that crash too ? (it might not since `-race` makes perfs bad and limit the number of goroutines)

**Comment by BigLep** [comment] 2021-08-05 12:56
@ribasushi has a workaround in place.  He has a 100% reproducible case, and will share logs/info after handling other priorities.

**Comment by tsoeiroecore** [comment] 2022-01-24 18:20
Hey guys, any updates on this? I'm facing similar issues in a highly concurrent environment.

**Comment by BigLep** [comment] 2022-01-24 18:38
@tsoeiroecore : this stalled previously in part due to not having a repro case.  Do you have one?

**Comment by BigLep** [comment] 2022-03-03 13:10
We don't have a reproducible case at our disposal, including things like the shape of the DAGs or a good way for someone to predictably reproduce the issue.  I've labeled this as needing autor-input.  If don't receive anything in the next week, we'll close for now.

**Comment by BigLep** [comment] 2022-03-25 15:23
Closing since don't have the reproducible case.

**Closed by BigLep** 2022-03-25 15:23 UTC
Labels: kind/bug, need/author-input, P1
