### ISSUE TITLE
Allow to chose ipns allowed resolve methods

### ISSUE THREAD

**Issue by Jorropo** [ipfs/go-ipfs#6519] opened 2019-07-16 15:24 UTC
I'm working on an anonymous i2p transport but I got a problem, ipns allows you to resolve using dns usenet wich could break anonymity that why I need to be able disable dns resolve method of ipns, but ipns is cool and the resolving via pubsub could still works.

I think it could maybe appear as a list of allowed resolve method in config :
```
  "ipns": {
    "resolvers": [
      "dns",
      "pubsub"
    ]
  }
```
The problem of that is if a newer resolver is added that will require to add this resolver here. A banned resolver field could fix this but the problem just change side, anonymous user will have problem of usenet resolving even if that not wanted.
But I think the problem is bigger for regular users, they just get a weaker resolving and maybe not resolving some link while anonymous user may get in trouble of browsing some content.
(I don't realy no which one is the best, but one of both is needed.)
I also think some special bundle of ipfs for i2p wouldn't be simple for user and bug fixing would be harder.

**Comment by Stebalien** [comment] 2019-11-16 02:27
Duplicate of https://github.com/ipfs/go-ipfs/issues/5945.

**Closed by Stebalien** 2019-11-16 02:27 UTC
Labels: enhancement
