### ISSUE TITLE
Cant access to ipns

### ISSUE THREAD

**Issue by nezzard** [ipfs/go-ipfs#3791] opened 2017-03-16 14:09 UTC
Hi, pls tell me, what i'm doing wrong?

I'm add to ipfs 
https://gateway.ipfs.io/ipfs/QmQNR7wcR8eTxHExSq9RDihovVGqPTNyYny5SvwuLY62Qz/
Than i made ipfs name publish QmQNR7wcR8eTxHExSq9RDihovVGqPTNyYny5SvwuLY62Qz
After that i tried to open https://ipfs.io/ipns/QmUv4itVoY3kTLuZ5GfHPKQnwz6qsvACTicQg1b3ZDTyeo/
but nothing happened

**Comment by Kubuxu** [comment] 2017-03-16 14:24
Has the name publish finished? Also can you post result of: `ipfs swarm peers`.

**Comment by Kubuxu** [comment] 2017-03-16 14:26
Are you sure it is your peerID? I can't find your node announcing your presence. Can you confirm it with `ipfs id`.

**Comment by nezzard** [comment] 2017-03-16 14:45
`[root@hmil ~]# ipfs id
{
	"ID": "QmUv4itVoY3kTLuZ5GfHPKQnwz6qsvACTicQg1b3ZDTyeo",
	"PublicKey": "CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDDa8HsSjYZwz7LyejUrj63Xs18wOtzHQNtRZtk8Q1MX9LEcA5HAHew3qNNvPyGeJlZnd7xMUy9eq/zp6q0QsrO4FmJwjtgzK1gfVMi1XrlQRyUsT96cVOnJIdHSePYiArRkx7wQWwgY5l6HLmAqkZQNh/sqIFLfpSZXxKJedAra0GYioDTmRqeHywU06g8skHn89j3dDcso/3jIeC2brMf1gie0TQ5bOzTZ+u1kQMMmTdwux+0PcmfXR/k/NgNgfKkEI4YXXkMZky1NNhZc9s4/0SjAr60Yj3zA0UfDHJtxkgK9sn44rPzbp4ODuXe6KjB9655LZPoYU2L6eW6t3P1AgMBAAE=",
	"Addresses": [
		"/ip4/127.0.0.1/tcp/4001/ipfs/QmUv4itVoY3kTLuZ5GfHPKQnwz6qsvACTicQg1b3ZDTyeo",
		"/ip4/195.28.183.165/tcp/4001/ipfs/QmUv4itVoY3kTLuZ5GfHPKQnwz6qsvACTicQg1b3ZDTyeo",
		"/ip4/10.8.0.1/tcp/4001/ipfs/QmUv4itVoY3kTLuZ5GfHPKQnwz6qsvACTicQg1b3ZDTyeo",
		"/ip6/::2/tcp/4001/ipfs/QmUv4itVoY3kTLuZ5GfHPKQnwz6qsvACTicQg1b3ZDTyeo",
		"/ip6/::1/tcp/4001/ipfs/QmUv4itVoY3kTLuZ5GfHPKQnwz6qsvACTicQg1b3ZDTyeo",
		"/ip4/195.28.183.165/tcp/4001/ipfs/QmUv4itVoY3kTLuZ5GfHPKQnwz6qsvACTicQg1b3ZDTyeo"
	],
	"AgentVersion": "go-ipfs/0.4.6/",
	"ProtocolVersion": "ipfs/0.1.0"
}
`

**Comment by nezzard** [comment] 2017-03-16 14:47
Swarm peers
`/ip4/104.236.151.122/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx
/ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z
/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64
/ip4/107.170.240.199/tcp/1024/ipfs/QmeU8f1sySSqNABN8PN5R5e3Y6DxjHw4yRiETNWZ1kswi8
/ip4/162.243.248.213/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm
/ip4/173.49.18.119/tcp/26506/ipfs/QmWABRCqWoYCGyGV2PZ2T3D9upV39yMgkmFCprXVsKvAZr
/ip4/178.19.251.249/tcp/4401/ipfs/QmR2FRyigN82VJc3MFZNz79L8Hunc3XvfAxU3eA3McRPHg
/ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3
/ip4/194.1.195.61/tcp/4001/ipfs/QmeTCderRhpjwhSnPYuNA1ArY3hhac2sMxdG8JBJnLAizo
/ip4/34.192.181.130/tcp/1024/ipfs/QmanN178KJV2FpBThgwBZxxsU8WLQ195SsfH8wufYpap78
/ip4/37.187.2.230/tcp/4001/ipfs/QmXt1oWkdrn1gfD5ftJBNJ9NLZEhhsGRHuAUd86jwgXjWj
/ip4/50.232.212.144/tcp/14294/ipfs/QmVG6rdtLnQnCSDDbSWiYp7HWFibT3RJ1oBTnhiXKZwpyt
/ip4/52.10.17.237/tcp/1024/ipfs/QmPgJVL1NSrxQ9mVa3Ne9Z4AMgVa4DGCUtu2iEH26HiJ4t
/ip4/52.170.218.157/tcp/9001/ipfs/QmRZvZiZrhJdZoDruT7w2QLKTdniThNwrpNeFFdZXAzY1s
/ip4/52.32.109.74/tcp/1163/ipfs/QmaWcGneeMEx6unN8iJCVCxP7Qcv4T91pjuZj9drJrdih1
/ip4/84.217.19.85/tcp/55862/ipfs/QmXKd1pJxTqTWNgGENcX2daiGLgWRPDDsXJe8eecQCr6Vh
/ip4/88.153.7.82/tcp/43350/ipfs/QmWTyP5FFpykrfocJ14AcQcwnuSdKAnVASWuFbtqCw3RPT
`

**Comment by nezzard** [comment] 2017-03-16 18:45
It's can be because i changed gateway port ?
"Gateway": "/ip4/127.0.0.1/tcp/8877"

**Comment by Kubuxu** [comment] 2017-03-16 19:57
No it shouldn't.

**Comment by Kubuxu** [comment] 2017-03-16 19:58
@whyrusleeping this issue is interesting.

`ipfs dht findpeer QmUv4itVoY3kTLuZ5GfHPKQnwz6qsvACTicQg1b3ZDTyeo` doesn't give me anything.

**Comment by whyrusleeping** [comment] 2017-03-16 21:29
@Kubuxu odd... same here. For other random addresses too

**Comment by Kubuxu** [comment] 2017-03-16 21:34
maybe the new search is not full compatible? It might be hitting other peers that don't have the data.

**Comment by whyrusleeping** [comment] 2017-03-16 21:36
@Kubuxu I think i ran that from an 0.4.6 daemon

**Comment by nezzard** [comment] 2017-03-16 21:37
The probles was is a firewall, i add to iptables port, and all works

I have one question, can you explain me, how does it work?
For example, i added txt file, than i start daemon, and delete this txt file.
Will ipfs always keep this txt file?

**Comment by Kubuxu** [comment] 2017-03-16 22:18
Yes

**Comment by whyrusleeping** [comment] 2017-03-16 22:36
@nezzard If you add a file, and start your daemon, then remove the file before anyone else accesses it, the file will be gone from the network.

Take a look at: https://github.com/ipfs/faq/issues/8 and https://github.com/ipfs/faq/issues/9

**Comment by Kubuxu** [comment] 2017-03-16 22:39
As the issue is resolved. I am closing.

**Closed by Kubuxu** 2017-03-16 22:39 UTC
