### ISSUE TITLE
dht_test timeout

### ISSUE THREAD

**Issue by chriscool** [ipfs/go-ipfs#1873] opened 2015-10-20 19:22 UTC
I sometimes get the following go test failure:

```
$ go test github.com/ipfs/go-ipfs/routing/dht
--- FAIL: TestConnectCollision (5.14s)
        dht_test.go:798: Timeout received!
time="10:28:33:000" level=error msg="TestBogusPrivateKey.Sign -- this better be a test!" module=boguskey 
FAIL
FAIL    github.com/ipfs/go-ipfs/routing/dht     11.984s
```

**Comment by noffle** [comment] 2016-02-19 00:14
I've been unable to reproduce locally, even with a much smaller timeout. :(

What OS are you running? What commit HEAD?

Can you reliably reproduce if you rerun the test enough times? If so, consider adding
```go
pprof.Lookup("goroutine").WriteTo(os.Stderr, 1)
```
before each timeout message in the test (you'll need to import `runtime/pprof` and `os`). This'll give a goroutine stack trace that might help us deduce where it's getting stuck.

**Comment by whyrusleeping** [comment] 2016-02-19 00:51
this was a much older bug, if we havent seen it in a while, its likely been resolved inadvertently

**Comment by noffle** [comment] 2016-02-19 00:59
All right -- closing then. @chriscool: please re-open if you see it again!

**Closed by noffle** 2016-02-19 00:59 UTC
Labels: test_failure

**Comment by chriscool** [comment] 2016-02-19 02:34
Ok, thanks!
