### ISSUE TITLE
Add custom protocal information to peer info

### ISSUE THREAD

**Issue by lvtlover** [ipfs/go-ipfs#6264] opened 2019-04-26 09:37 UTC
#### Description:

As discussed here https://discuss.ipfs.io/t/how-to-find-nodes-handling-a-custom-protocol/5236/7 .

Having the ability (option) to get more information from peers listing/finding functions would effectively make it easier in that "discovery" use case but also when trying to direct connect peers (ex: STUN for free), building DHT like systems over the IPFS network and I think a lot of other cases.

**Comment by Stebalien** [comment] 2019-05-15 23:47
For active discovery, take a look at https://github.com/libp2p/go-libp2p-discovery/ and https://github.com/libp2p/specs/tree/master/rendezvous, https://github.com/libp2p/libp2p/issues/66.

Closing as a duplicate of https://github.com/libp2p/go-libp2p-kad-dht/issues/302.

**Closed** 2019-05-15 23:47 UTC
Labels: enhancement
