### ISSUE TITLE
`ipfs files rm` fails

### ISSUE THREAD

**Issue by Luflosi** [ipfs/go-ipfs#7172] opened 2020-04-16 14:31 UTC
#### Version information:
go-ipfs version: 0.4.23-6ce9a355f
Repo version: 7
System version: amd64/linux
Golang version: go1.14

Using the latest Web UI bafybeigxqbvc6qxk2wkdyzpkh7mr7zh5pxbvpjb6a6mxdtpwhlqaf4qj5a.

#### Description:
When adding the IGIS git repo CID to the files using the Web UI, it can never be removed again, not with the Web UI and not with the command line. At least I don't know of any obvious way to do so.

Steps to reproduce:

1. Open the Web UI
2. Click on "Explore" on the left
3. Click on "IGIS git repo"
4. Copy the CID (z8mWaJHXieAVxxLagBpdaNWFEBKVWmMiE)
5. Click on "Files" on the left
6. Click "Add"
7. Click "From IPFS"
8. Paste the CID
9. Click "Add"
10. An error message "Failed to add files to IPFS. Please try again." is displayed but the CID was added anyways
11. Trying to remove the CID using the Web UI again fails
12. Executing `ipfs files rm /z8mWaJHXieAVxxLagBpdaNWFEBKVWmMiE` fails with "Error: unrecognized node type in cache node"

I would expect to either be able to remove anything I added again or to not be able to add something that shouldn't be added.

**Comment by Stebalien** [comment] 2020-04-16 20:13
I can confirm. Git "objects" aren't files, that's why this isn't working. However,

1. We shouldn't be adding the file in the first place.
2. We shouldn't fail to remove the file.

**Comment by lidel** [comment] 2021-07-01 15:37
I believe this is a duplicate of https://github.com/ipfs/go-ipfs/issues/7999
The fix here is to add `--force` flag:

```
$ ipfs files rm --force  /z8mWaJHXieAVxxLagBpdaNWFEBKVWmMiE
```

**Closed by lidel** 2021-07-01 15:37 UTC
Labels: P1, kind/bug, topic/MFS

**Comment by Luflosi** [comment] 2021-07-05 22:12
Your command worked, thank you.
However, I think it should not be possible to add objects like that in the first place.
