### ISSUE TITLE
The whole home WI-FI crashed down when running IPFS daemon. Recovered after turning IPFS off.

### ISSUE THREAD

**Issue by RyanZhu1024** [ipfs/go-ipfs#3216] opened 2016-09-12 23:58 UTC
Version/Platform/Processor information (from `ipfs version --all`):
ipfs version 0.4.2
OSX 10.11.6
2.3 GHz Intel Core i7

Type (bug, feature, meta, test failure, question): bug
Area (api, commands, daemon, fuse, etc): daemon
Priority (from P0: operations on fire, to P4: functioning): P4

Description:

When I started IPFS daemon with the go version, my whole home network will crash down. I can't ping from the machine running IPFS and I can't even open webs from my phone through WIFI. Please help to fix this.

**Comment by Kubuxu** [comment] 2016-09-13 12:11
We had already similar issue, you can start by disabling mDNS in config: `ipfs config --bool Discovery.MDNS.Enabled false`

**Comment by lgierth** [comment] 2016-09-13 20:45
Yes, what @Kubuxu said -- in addition:

- model, revision, and firmware version of your router
- did it kill only the wifi or the whole router, i.e. were you still able to use ethernet/cable? Or did it maybe kill the internet connection, but not the router itself?

**Comment by lgierth** [comment] 2016-09-13 20:48
(gonna mark this with the NAT label just for now)

**Comment by RyanZhu1024** [comment] 2016-09-13 22:36
- I'm using a power line adapter connecting 2 routers at home. One is netgear ac 1750, and the other one is not an American brand, which is running on Openwrt.
- It seems like it kiledl some part of the network, as I can't open any websites, google or Facebook or even `ping`, but i can check my messages through Wechat, which is not using http protocol to connect. I didn't try the ethernet and the it's not happening all the time. Now i'm running ipfs daemon in a docker on my Mac, until now, everything is still fine.

**Comment by lgierth** [comment] 2016-09-13 23:15
> but i can check my messages through Wechat, which is not using http protocol to connect.

This sounds like it might be a problem with the firewall's connection tracking / flow control?

**Comment by lgierth** [comment] 2016-09-13 23:16
> Now i'm running ipfs daemon in a docker on my Mac, until now, everything is still fine.

Are you still getting about the same number of peers? `ipfs swarm peers | wc -l`. If you're getting fewer, it might just not be enough to trigger the issue

**Comment by RyanZhu1024** [comment] 2016-09-17 18:15
@lgierth I'm not sure if it's firewall or something, since I don't firewall opened on my MacOS and router.

I don't get fewer peers. after running `swarm peers`, still got a lot of peers.

**Comment by Stebalien** [comment] 2020-02-20 17:55
Duplicate of https://github.com/ipfs/go-ipfs/issues/3320.

**Closed** 2020-02-20 20:15 UTC
Labels: backlog, bug, nat
