### ISSUE TITLE
build go-ipfs from source error

### ISSUE THREAD

**Issue by xiedeacc** [ipfs/go-ipfs#7649] opened 2020-09-04 07:16 UTC
I follow [wiki](https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md) to build ipfs on windows 10 use mysy and tdm-gcc, go 1.14.4. cmd says 

D:\code\go\src\github.com\ipfs\go-ipfs>make install
go version go1.14.4 windows/amd64
bin/check_go_version 1.14.4
plugin/loader/preload.sh > plugin/loader/preload.go
-u系统找不到指定的文件(system cannot found specify file)。
go fmt plugin/loader/preload.go >/dev/null
go install -trimpath -ldflags="-X "github.com/ipfs/go-ipfs".CurrentCommit=2ae5c52f4-dirty" ./cmd/ipfs
# github.com/ipfs/go-ipfs/plugin/loader
plugin\loader\preload.go:10:10: undefined: pluginipldgit
plugin\loader\preload.go:11:10: undefined: pluginbadgerds
plugin\loader\preload.go:12:10: undefined: pluginflatfs
plugin\loader\preload.go:13:10: undefined: pluginlevelds
make: *** [cmd/ipfs/Rules.mk:37: cmd/ipfs-install] Error 2

it seems plugin/loader/preload.sh > plugin/loader/preload.go generat error, mysy bash compatibe problem?
it seems awk 'NF' "$DIR/preload_list" | sed '/^#/d' was not assigned to IPFS_PLUGINS, lead an empty import in preload.go

================================================
below is preload.go

package loader

import ()

// DO NOT EDIT THIS FILE
// This file is being generated as part of plugin build process
// To change it, modify the plugin/loader/preload.sh

func init() {
	Preload(pluginipldgit.Plugins...)
	Preload(pluginbadgerds.Plugins...)
	Preload(pluginflatfs.Plugins...)
	Preload(pluginlevelds.Plugins...)
}

**Comment by Jorropo** [comment] 2020-09-04 15:05
Plugins are not supported on windows (only *nix), try on linux, OSX if you want them.
I'm not sure what that happend, logicaly these file should be ignored on windows.

**Comment by aschmahmann** [comment] 2020-09-04 15:46
@xiedeacc I suspect this is a general support/machine configuration question and not a bug, I'm able to use `make install` on Windows 10 using msys2 just fine (perhaps your PATH is setup to use the wrong versions of bash or awk). If so this is best handled on discuss.ipfs.io as it makes it easier for other users to find the information in the future (closed GitHub issues aren't very searchable).

I'm going to close this issue for now, but feel free to reopen if there's an actual bug you are reporting. Feel free to repost on discuss.ipfs.io and tag me if you'd like me to respond there.

-----

@Jorropo as described at https://github.com/ipfs/go-ipfs/blob/f55d3e8a150d905059e80892362dc48c4603705c/docs/plugins.md#installing-plugins there are both external and preloaded plugin types. While external plugins are not support by the Golang team for Windows preloaded plugins should work just fine. In particular, those four plugins are preloaded with all go-ipfs installations by default.

**Closed by aschmahmann** 2020-09-04 15:46 UTC
Labels: kind/bug, need/triage
