### ISSUE TITLE
RepoSize incorrect with symlink

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4408] opened 2017-11-21 06:31 UTC
Interesting sharness error:

```
make: *** [test/sharness/t0088-repo-stat-symlink.sh] Error 1
make: *** Waiting for unfinished jobs....
*** test/sharness/t0088-repo-stat-symlink.sh ***
# TEST_VERBOSE=1
# TEST_NO_FUSE=1
# TEST_NO_PLUGIN=
# TEST_EXPENSIVE=1
# TEST_OS=LINUX
expecting success: 
  mkdir sym_link_target &&
  ln -s sym_link_target .ipfs

ok 1 - create symbolic link for IPFS_PATH

expecting success: 
    export IPFS_PATH="$(pwd)/.ipfs" &&
    ipfs init --profile=test -b=1024 > /dev/null
  
ok 2 - ipfs init succeeds

expecting success: 
    mkdir mountdir ipfs ipns &&
    test_config_set Mounts.IPFS "$(pwd)/ipfs" &&
    test_config_set Mounts.IPNS "$(pwd)/ipns" ||
    test_fsh cat "\"$IPFS_PATH/config\""
  
ipfs config  "Mounts.IPFS" "/go/src/github.com/ipfs/go-ipfs/test/sharness/trash directory.t0088-repo-stat-symlink.sh/ipfs"
ipfs config  "Mounts.IPNS" "/go/src/github.com/ipfs/go-ipfs/test/sharness/trash directory.t0088-repo-stat-symlink.sh/ipns"
ok 3 - prepare config -- mounting

expecting success: 
  export IPFS_PATH="sym_link_target" &&
  reposize_direct=$(ipfs repo stat | grep RepoSize | awk '{ print $2 }') &&
  export IPFS_PATH=".ipfs" &&
  reposize_symlink=$(ipfs repo stat | grep RepoSize | awk '{ print $2 }') &&
  test $reposize_symlink -ge $reposize_direct

not ok 4 - 'ipfs repo stat' RepoSize is correct with sym link
#	
#	  export IPFS_PATH="sym_link_target" &&
#	  reposize_direct=$(ipfs repo stat | grep RepoSize | awk '{ print $2 }') &&
#	  export IPFS_PATH=".ipfs" &&
#	  reposize_symlink=$(ipfs repo stat | grep RepoSize | awk '{ print $2 }') &&
#	  test $reposize_symlink -ge $reposize_direct
#	

# failed 1 among 4 test(s)
1..4
test/sharness/Rules.mk:31: recipe for target 'test/sharness/t0088-repo-stat-symlink.sh' failed
```

**Comment by kevina** [comment] 2017-11-28 02:32
Related p.r.: https://github.com/ipfs/go-ipfs/pull/4305/files

**Comment by kevina** [comment] 2017-11-28 18:20
I can't reproduce this and the builds now seam to be passing.

In order to see what is going on I would need to add something like
```
echo "reposize_symlink: $reposize_symlink  reposize_direct: reposize_direct"
```
to see why the numbers are not matching as there is no indication of any other errors.

**Comment by magik6k** [comment] 2017-11-28 19:08
Just bumped into this https://circleci.com/gh/ipfs/go-ipfs/8414#tests/containers/1

**Comment by kevina** [comment] 2017-11-28 19:21
By guess is the repo size is decreasing (instead of increating) slightly.  #4434 should help get to the bottom of this.

**Comment by kevina** [comment] 2017-11-28 19:23
@magik6k #4434 was just merged, could you rebase and see if it still fails?

**Comment by Stebalien** [comment] 2017-11-30 04:16
I just ran into this:

```
expecting success: 
  export IPFS_PATH="sym_link_target" &&
  reposize_direct=$(ipfs repo stat | grep RepoSize | awk '{ print $2 }') &&
  export IPFS_PATH=".ipfs" &&
  reposize_symlink=$(ipfs repo stat | grep RepoSize | awk '{ print $2 }') &&
  echo "reposize_symlink: $reposize_symlink;  reposize_direct: $reposize_direct" &&
  test $reposize_symlink -ge $reposize_direct

reposize_symlink: 128958;  reposize_direct: 129619
```

So, it looks like the repo size is decreasing (by 661 bytes in this case).

**Comment by kevina** [comment] 2017-11-30 04:19
Yeah, that what I thought would happen.  We need to rethink the test or introduce a fuze factor...

Why it changes in size could be any number of things.

**Closed** 2017-12-03 17:05 UTC
Labels: test failure
